return {
  {
    key = "card_animation_mode", type = "choice", label = "KARTENANIMATION",
    default = "natural",
    choices = {{"KLASSISCH", "classic"}, {"NATUERLICH", "natural"}},
    description = "NATUERLICH aktiviert neue menschliche Lauf- und Ruhebewegungen. KLASSISCH stellt sofort die bisherige Kartenanimation wieder her. Originalgrafiken bleiben ueber HD-MENSCHEN erreichbar.",
  },
  {
    key = "human_acting_pilot", type = "toggle", label = "DIALOGPOSEN (TEST)",
    default = true,
    description = "Figuren-Test: Eich und Blau schauen im Alabastia-Startdialog zum Gespraechspartner. Rots Mutter sitzt auf ihrem Stuhl und dreht im Gespraech den Kopf. Benoetigt NATUERLICH und HD-MENSCHEN; Figurenraster AUS. Lind und die Mutter in Neuborkia blinzeln und atmen im direkt gestarteten Gespraech. Die Besucherin gegenueber atmet im Gespraech. Weitere Figuren folgen. KLASSISCH oder HD-MENSCHEN AUS setzt die Darstellung zurueck.",
  },
  {
    key = "hd_walking_sprites",
    type = "toggle",
    label = "HD-MENSCHEN",
    default = true,
    description = "Ersetzt Spieler und NPCs durch die freigegebenen transparenten Ascendant-4x3-Figuren. AUS stellt die unveraenderten Vanilla-Sprites wieder her.",
  },
  {
    key = "hd_pokemon_followers",
    type = "toggle",
    label = "HD-BEGLEITER",
    default = true,
    description = "Nutzt die neuen 3x4-Pokemon-Lauffiguren nur fuer den aktiven Begleiter. KASC/JASC/Wilds behalten Auswahl, Bewegung und Besitz.",
  },
  {
    key = "follower_sprite_source",
    type = "choice",
    label = "BEGLEITER-OPTIK",
    default = "hd",
    choices = {
      { "GO-HD ANIMIERT", "hd" },
      { "POKEMMO PIXEL", "pokemmo" },
    },
    description = "Waehlt nur die sichtbaren Begleiter-Karten. GO-HD-RENDERKARTEN stammen aus den gelieferten Pokemon-GO-Modellrendern; POKEMMO nutzt kompakte animierte Pixelkarten samt Normal/Shiny-, Geschlechts- und Formvarianten. Fehlt eine PokeMMO-Variante, folgt die GO-HD-Renderkarte. Beide Quellen behalten dieselbe festgelegte Pokemon-Groessenklasse.",
  },
  {
    key = "pikachu_head_ride",
    type = "toggle",
    label = "PIKACHU AUF KOPF",
    default = false,
    description = "Optionale VASC-HD-Einlage: Pikachu springt gelegentlich kurz auf den Trainerkopf und wieder zurueck. Benoetigt HD-Menschen und animierte GO-HD-Begleiter. Nur Darstellung, keine Kollision oder Spielerbewegung. Bei Menues, Dialogen, Kartenwechsel, Radfahren oder Surfen wird abgebrochen.",
  },
  {
    key = "dynamic_follower_spacing",
    type = "toggle",
    label = "GROESSENABSTAND",
    default = true,
    description = "Setzt die sichtbare Begleiterkette mit groessenabhaengiger Randfreiheit auf bereits gelaufene, begehbare Spurpunkte. Auch grosse und mehrere Pokemon folgen damit um Ecken statt durch Hindernisse versetzt zu werden. Bewegung, Kollision und Besitzer bleiben unveraendert.",
  },
  {
    key = "pokemon_collision_mode",
    type = "choice",
    label = "MON-KOLLISION",
    default = "normal",
    visible_if = { key="pokemon_collision_mode", not_equals="soft" },
    choices = {
      { "NORMAL", "normal" },
      { "FREI", "passable" },
    },
    description = "FREI macht erkannte Begleiter und kompatible Stadt-/Haus-Pokemon durchlaufbar. Fremdverwaltete Wilds-/Ambient-Pokemon behalten ohne sichere Besitzer-Schnittstelle ihre Originalkollision, damit sie nicht verschwinden. WEICH benoetigt eine Ausweich-Schnittstelle des Besitzers und blockiert sonst. NORMAL stellt die Originalkollision wieder her. Menschen, Story-Trigger und Grasbegegnungen bleiben unveraendert.",
  },
  {
    -- Preserve an existing soft choice without offering it to new selections.
    -- Mutually exclusive schema rows use the same stored key; no migration.
    key = "pokemon_collision_mode", type = "choice", label = "MON-KOLLISION",
    default = "normal",
    visible_if = { key="pokemon_collision_mode", equals="soft" },
    choices = {
      { "WEICH: GESPERRT", "soft" },
      { "NORMAL", "normal" },
      { "FREI", "passable" },
    },
    description = "Die gespeicherte WEICH-Wahl bleibt erhalten, ist ohne Besitzer-Schnittstelle aber nicht verfuegbar: Pokemon blockieren weiter. NORMAL oder FREI waehlen. Ein einmaliges Blocken wird hier nicht vorgetaeuscht; Wilds-/Story-Besitzer behalten ihre Schutzregeln.",
  },
  {
    key = "living_follower_animation",
    type = "toggle",
    label = "POKEMON-ANIMATION",
    default = true,
    description = "Animiert Begleiter, Stadt-, Haus- und Wilds-Pokemon passend als Lauf, Flug, Kriechen, Schwimmen oder ruhiges Atmen. AUS behaelt die gelieferten Ruheposen.",
  },
  {
    key = "hd_pokemon_grass",
    type = "toggle",
    label = "HD-WILDE MONS",
    default = true,
    description = "Nutzt die neuen 3x4-Lauffiguren fuer bereits vorhandene sichtbare Wild-Pokemon in Gras und Hoehlen. Spawns und Begegnungen bleiben unveraendert.",
  },
  {
    key = "grass_pokemon_sprite_source", type = "choice",
    label = "WILD-OPTIK", default = "hd",
    choices = {
      { "GO-HD ANIMIERT", "hd" },
      { "POKEMMO PIXEL", "pokemmo" },
    },
    description = "Waehlt sichtbare Gras-/Hoehlen-Pokemon. Fehlende PokeMMO-Varianten fallen einzeln auf Ascendant HD zurueck.",
  },
  {
    key = "hd_pokemon_city",
    type = "toggle",
    label = "HD-STADT-MONS",
    default = true,
    description = "Ersetzt fest platzierte bzw. pseudoartige Pokemon-NPCs in Orten, wenn ihre Art eindeutig bekannt ist.",
  },
  {
    key = "city_pokemon_sprite_source", type = "choice",
    label = "STADT-OPTIK", default = "hd",
    choices = {
      { "GO-HD ANIMIERT", "hd" },
      { "POKEMMO PIXEL", "pokemmo" },
    },
    description = "Waehlt die animierte Quelle fuer fest platzierte Pokemon in Staedten und Innenraeumen.",
  },
  {
    key = "hd_pokemon_wilds_towns",
    type = "toggle",
    label = "HD-WILDS-ORTE",
    default = true,
    description = "Nutzt die neuen 3x4-Lauffiguren nur fuer die friedlichen Stadt-Pokemon von Wilds. Wilds behaelt Anzahl, Artwahl und Verhalten.",
  },
  {
    key = "wilds_town_pokemon_sprite_source", type = "choice",
    label = "WILDS-OPTIK", default = "hd",
    choices = {
      { "GO-HD ANIMIERT", "hd" },
      { "POKEMMO PIXEL", "pokemmo" },
    },
    description = "Waehlt die animierte Quelle fuer friedliche Wilds-Pokemon in Orten; Wilds behaelt Spawn und Verhalten.",
  },
  {
    key = "pokemon_model_source",
    type = "choice",
    label = "MODELL-QUELLE",
    default = "auto",
    choices = {
      { "AUTO: ST2 / GO", "auto" },
      { "NUR STADIUM 2", "stadium_only" },
      { "GO-HD ZUERST", "go_first" },
      { "NUR GO-HD", "go_only" },
      { "NUR HD-2D", "sprite_only" },
    },
    description = "AUTO laesst bei #001-251 ein oeffentlich gemeldetes POKÉMON STADIUM 2-Modell vor und nutzt danach die eingebauten GO-HD-RENDERKARTEN. GO-HD sind animierte Karten aus den gelieferten Pokemon-GO-Modellrendern, keine live geriggten GO-Modelle. Eine ausdrueckliche POKEMMO-Auswahl pro Kontext bleibt immer sichtbar und unterdrueckt dort das POKÉMON STADIUM 2-Mesh. Diese Mod veraendert keine Voxel-Ascendant-Datei.",
  },
  {
    key = "pokemon_card_style",
    type = "choice",
    label = "POKEMON-BILDSTIL",
    default = "off",
    choices = {
      { "ORIGINAL", "off" },
      { "FEINE KONTUR", "outline" },
      { "ANIME DEZENT", "anime" },
      { "COMIC KONTUR", "comic" },
    },
    description = "Optional fuer glatte GO-HD-Karten: ANIME mit feiner Kontur und sanften Schatten; COMIC mit kraeftigerer dunkler Kontur und klareren Helligkeitsstufen. Farbtone und Saettigung bleiben erhalten. Keine neuen 3D-Lichtnormalen oder veraenderten Koerperformen. PokeMMO-Pixel, Wuerfelraster und das abgenommene Feuerigel bleiben unveraendert.",
  },
  {
    key = "actor_voxel_grid",
    type = "choice",
    label = "FIGUREN-RASTER",
    default = "off",
    choices = {
      { "AUS", "off" },
      { "NUR MENSCHEN", "characters" },
      { "NUR POKEMON", "pokemon" },
      { "BEIDE", "both" },
    },
    description = "Stellt Menschen und/oder Pokemon aus kleinen 3D-Zellen dar. Natuerlich animierte Menschen erhalten geschlossene, farbige Oberflaechen ohne schwarze Rasterfugen. Klassisch behaelt das bisherige Raster. Terrain- und Kampfraster bleiben unabhaengig.",
  },
  {
    key = "actor_voxel_cubes",
    type = "choice",
    label = "3D-WUERFELSTAERKE",
    default = "off",
    choices = {
      { "AUS / FLACH", "off" },
      { "DEZENT", "subtle" },
      { "MITTEL", "balanced" },
      { "STARK", "strong" },
      { "EXTREM", "extreme" },
    },
    description = "Regelt bei aktivem FIGUREN-VOXELRASTER Tiefe und Anzahl der miteinander verbundenen Wuerfelstufen. MITTEL entspricht ungefaehr dem bisherigen 3D-Schalter; EXTREM baut den deutlichsten Minecraft-Koerper.",
  },
  {
    key = "atmospheric_sprite_shading",
    type = "toggle",
    label = "SZENENLICHT",
    default = false,
    description = "EIN faerbt Figuren mit VASCs Tageszeit und Wetter. AUS zeigt ihre originalen Modell- und Spritefarben, zum Beispiel Pikachus klares Gelb.",
  },
  {
    key = "voxel_character_finish",
    type = "toggle",
    label = "MENSCHEN-RELIEF",
    default = true,
    description = "Laesst Voxel Ascendant die HD-Figuren in seiner beleuchteten 3D-Figurenebene darstellen. AUS behaelt die HD-Zuordnung, ueberlaesst die Darstellung aber dem normalen Renderer.",
  },
  {
    key = "voxel_pokemon_finish",
    type = "toggle",
    label = "POKEMON-RELIEF",
    default = true,
    description = "Gibt nur den neuen Pokemon-Lauffiguren in VASC ein flaches, beleuchtetes Facettenrelief. AUS zeigt dieselben 3x4-Figuren als unveraenderte Karten.",
  },
}
