#!/usr/bin/env python3
"""Compact Kanto in Motion's HD Pokemon sheet metadata for Terrarium.

Reads KIM's generated data/hd_pokemon_sprites.lua (#1-151) and
data/hd_pokemon_national.lua (#152-386) and writes data/hd_sheet_meta.lua:

    return { front = { normal = { ["001"] = {w, h, cols, frames, scale}, ... },
                       shiny  = { ... } },
             back  = { ... } }

Keys are file stems: "001", or "154-m" / "154-f" for gender variants. Every
KIM record uses 50 ms frames (verified), so durations are not stored.

Usage: port_kim_meta.py <path-to-KIM-folder> [<out-file>]
"""
import re
import sys
from pathlib import Path

REC = re.compile(
    r'"assets/battle/hd-pokemon/(?P<side>front|back)/(?P<color>normal|shiny)/'
    r'(?P<stem>\d{3}(?:-[mf])?)\.png", width = (?P<w>\d+), height = (?P<h>\d+), '
    r'columns = (?P<c>\d+), frames = (?P<f>\d+), durations = \{(?P<d>[0-9,]*)\}, '
    r'displayScale = (?P<s>[0-9.]+)')


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    kim = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parents[1] / "data" / "hd_sheet_meta.lua"
    table = {"front": {"normal": {}, "shiny": {}}, "back": {"normal": {}, "shiny": {}}}
    count = 0
    for name in ("hd_pokemon_sprites.lua", "hd_pokemon_national.lua"):
        text = (kim / "data" / name).read_text(encoding="utf-8")
        for m in REC.finditer(text):
            durs = {int(x) for x in m["d"].split(",") if x}
            if durs != {50} or len(m["d"].split(",")) != int(m["f"]):
                raise SystemExit(f"non-uniform/mismatched durations for {m['stem']}: unsupported")
            table[m["side"]][m["color"]][m["stem"]] = (
                int(m["w"]), int(m["h"]), int(m["c"]), int(m["f"]), float(m["s"]))
            count += 1
    lines = [
        "-- Generated by tools/port_kim_meta.py from Kanto in Motion v1.6.0 data tables.",
        "-- Sheet geometry for the HD animated Pokemon art (JDChaos, Battle Sprites Reloded).",
        "-- Record = {frameW, frameH, columns, frames, displayScale}; 50 ms per frame.",
        "-- displayScale = KIM's HD-pixel -> Game-Boy-pixel factor for that species.",
        "return {",
    ]
    for side in ("front", "back"):
        lines.append(f"  {side} = {{")
        for color in ("normal", "shiny"):
            lines.append(f"    {color} = {{")
            for stem in sorted(table[side][color]):
                w, h, c, f, s = table[side][color][stem]
                lines.append(f'      ["{stem}"] = {{{w},{h},{c},{f},{s:.6f}}},')
            lines.append("    },")
        lines.append("  },")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {count} records -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
