-- Sheet geometry for National Dex 387-493 (and any extra/replacement sheet).
-- Same format as hd_sheet_meta.lua: {frameW, frameH, columns, frames, displayScale [, ms]}
-- Generated by tools/build_gen4_sheets.py. Entries here override the KIM table.
-- A sheet with no row here is drawn as one static frame at a default scale.
return {
  front = { normal = {}, shiny = {} },
  back  = { normal = {}, shiny = {} },
}
