-- Exact native Gen1 component masks, reviewed against the original block atlas.
local function phase(map,x,y,n)
 -- Native furnishings often repeat every four tiles; include the block index
 -- so those regular rows still receive different stable variants.
 local seed=x*3+y*7+math.floor(x/4)+math.floor(y/4)
 for i=1,#map.id do seed=seed+map.id:byte(i)end
 return seed%n
end
local function plant(map,x,y)
 local types=map.def.tileset=='FACILITY' and {0,3} or map.def.tileset=='POKECENTER' and {0,2} or {0,1,2,3}
 return 'indoor_plant_'..types[phase(map,x,y,#types)+1]
end
local function grave(map,x,y)return 'memorial_stone_'..phase(map,x,y,3)end
return {
 -- The same FACILITY debris mask is industrial equipment in the power plant
 -- but rubble in the ruined mansion. Never replace its switch-statue masks.
 {kind='mansion_rubble_0',sets={FACILITY=true},maps={POKEMON_MANSION_1F=true,
  POKEMON_MANSION_2F=true,POKEMON_MANSION_3F=true,POKEMON_MANSION_B1F=true},complete=true,
  tiles={{83,84},{54,38}},variant=function(map,x,y)return 'mansion_rubble_'..phase(map,x,y,3)end},
 {kind='power_generator_0',sets={FACILITY=true},maps={POWER_PLANT=true},complete=true,
  tiles={{83,84},{54,38}},variant=function(map,x,y)return 'power_generator_'..phase(map,x,y,3)end},
 {kind='shop_bicycle_0',sets={CLUB=true},maps={BIKE_SHOP=true},complete=true,
  tiles={{11,12,14},{27,28,9}},variant=function(map,x,y)return 'shop_bicycle_'..phase(map,x,y,4)end},
 {kind='shop_bicycle_0',sets={CLUB=true},maps={BIKE_SHOP=true},complete=true,
  tiles={{1,2,3},{17,18,19}},variant=function(map,x,y)return 'shop_bicycle_'..phase(map,x,y,4)end},
 {kind='wood_chair_north',sets={CLUB=true},maps={BIKE_SHOP=true},tiles={{29,13},{21,22}}},
 {kind='shop_counter_run',sets={CLUB=true},maps={BIKE_SHOP=true},tiles={{7,8}}},
 {kind='shop_counter_end',sets={CLUB=true},maps={BIKE_SHOP=true},x=10,y=7,tiles={{23,24}}},
 {kind='shop_counter_front',sets={CLUB=true},maps={BIKE_SHOP=true},complete=true,
  tiles={{54,16,16,5},{23,24,23,24}}},
 {kind='trade_transfer_station',sets={CLUB=true},maps={TRADE_CENTER=true},complete=true,
  tiles={{71,72,73,74},{23,24,23,24}}},
 {kind='link_club_seat',sets={CLUB=true},maps={TRADE_CENTER=true,COLOSSEUM=true},complete=true,
  tiles={{42,43},{38,39}}},
 {kind='link_battle_console',sets={CLUB=true},maps={COLOSSEUM=true},complete=true,
  tiles={{15,64,65,15},{59,60,61,62},{55,56,57,58}}},
 -- Story-specific damaged objects run before the intact component masks.
 {kind='damaged_home_table',sets={HOUSE=true},maps={CERULEAN_TRASHED_HOUSE=true},complete=true,
  tiles={{38,39,39,41},{54,47,47,57},{80,81,47,57},{82,83,58,59}}},
 {kind='toppled_home_chair',sets={HOUSE=true},maps={CERULEAN_TRASHED_HOUSE=true},complete=true,
  tiles={{28,29},{68,69}}},
 {kind='toppled_home_plant',sets={HOUSE=true},maps={CERULEAN_TRASHED_HOUSE=true},complete=true,
  tiles={{42,43,44,37},{12,13,53,56}}},
 {kind='fallen_home_picture',sets={HOUSE=true},maps={CERULEAN_TRASHED_HOUSE=true},tiles={{34}}},
 {kind='home_track_dark',sets={HOUSE=true},maps={CERULEAN_TRASHED_HOUSE=true},tiles={{55}}},
 {kind='home_track_scuff',sets={HOUSE=true},maps={CERULEAN_TRASHED_HOUSE=true},tiles={{40}}},
 {["kind"]="indoor_plant_0",["sets"]={["HOUSE"]=true},["tiles"]={{10,11},{8,9},{26,27},{24,25}},variant=plant},
 {["kind"]="indoor_plant_0",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{68,69},{8,9},{70,71},{24,25}},variant=plant},
 {["kind"]="indoor_plant_0",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{32,33},{48,49},{34,35},{50,51}},variant=plant},
 {["kind"]="indoor_plant_0",["sets"]={["GATE"]=true,["FOREST_GATE"]=true,["MUSEUM"]=true},["tiles"]={{5,6},{21,22},{37,38},{53,54}},variant=plant},
 {["kind"]="indoor_plant_0",["sets"]={["FACILITY"]=true},["tiles"]={{5,6},{21,22},{7,15},{23,31}},variant=plant},
 {["kind"]="indoor_plant_0",["sets"]={["MANSION"]=true},["tiles"]={{68,69},{8,9},{70,71},{24,25}},variant=plant},
 {["kind"]="wood_chair_north",["sets"]={["HOUSE"]=true},["tiles"]={{2,3},{18,19}}},
 {["kind"]="wood_chair_north",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{2,3},{18,19}}},
 {["kind"]="wood_chair_north",["sets"]={["INTERIOR"]=true},["tiles"]={{61,62},{59,60}}},
 {["kind"]="wood_chair_north",["sets"]={["GATE"]=true,["FOREST_GATE"]=true,["MUSEUM"]=true},["tiles"]={{2,3},{18,19}},variant=function(map,x,y)
  -- This native occupant faces right toward the rest-house table.
  if map.id=='SAFARI_ZONE_WEST_REST_HOUSE' and x==0 and y==4 then return 'wood_chair_west' end
  return 'wood_chair_north'
 end},
 {["kind"]="wood_chair_north",["sets"]={["MANSION"]=true},["tiles"]={{2,3},{18,19}}},
 {["kind"]="wood_stool",["sets"]={["SHIP"]=true},["tiles"]={{7,8},{23,24}}},
 {["kind"]="home_pc",["sets"]={["HOUSE"]=true},["tiles"]={{64,65},{32,33},{66,67},{30,31}}},
 {["kind"]="home_pc",["sets"]={["REDS_HOUSE_1"]=true},["tiles"]={{64,65},{32,33},{66,67},{50,51}}},
 {["kind"]="office_terminal",["sets"]={["MANSION"]=true},["tiles"]={{36,37,52,53},{64,65,66,67}}},
 {["kind"]="office_terminal",["sets"]={["INTERIOR"]=true},["tiles"]={{11,12,13,14},{27,28,29,30}}},
 {["kind"]="dining_table",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{38,39,40,41},{54,55,56,57},{44,42,42,43},{60,58,58,59}}},
 {["kind"]="dining_table",["sets"]={["HOUSE"]=true},["tiles"]={{38,39,39,41},{54,47,47,57},{54,47,47,57},{60,58,58,59}}},
 {["kind"]="writing_table",["sets"]={["HOUSE"]=true},["tiles"]={{38,39,39,41},{70,71,47,57},{86,87,47,57},{60,58,58,59}}},
 {["kind"]="console_cabinet",["sets"]={["FACILITY"]=true},["tiles"]={{13,14},{74,75},{76,77}}},
 {["kind"]="wall_recorder",["sets"]={["FACILITY"]=true},["tiles"]={{13,14},{76,77}}},
 {["kind"]="memorial_stone_0",["sets"]={["CEMETERY"]=true},["tiles"]={{5,6},{21,22}},variant=grave},
 {["kind"]="plain_bed",["sets"]={["FACILITY"]=true},["tiles"]={{40,41},{56,57},{56,57},{25,26}}},
 {["kind"]="plain_bed",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{45,46},{61,62},{61,62},{63,47}}},
 {["kind"]="woven_rug_32",["sets"]={["HOUSE"]=true},["tiles"]={{4,4,4,4},{20,20,20,20}}},
 {["kind"]="woven_rug_16",["sets"]={["HOUSE"]=true},["tiles"]={{4,4},{20,20}}},
 {["kind"]="woven_rug_32",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{4,4,4,4},{20,20,20,20}}},
 {["kind"]="woven_rug_16",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{4,4},{20,20}}},
 {["kind"]="woven_rug_32",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{12,12,12,12},{28,28,28,28}}},
 {["kind"]="woven_rug_16",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{12,12},{28,28}}},
 {["kind"]="woven_rug_32",["sets"]={["INTERIOR"]=true},["tiles"]={{4,4,4,4},{20,20,20,20}}},
 {["kind"]="woven_rug_16",["sets"]={["INTERIOR"]=true},["tiles"]={{4,4},{20,20}}},
 {["kind"]="counter_unit",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{8}}},
 {["kind"]="counter_unit",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{24}}},
 {["kind"]="counter_unit",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{25}}},
 {["kind"]="counter_unit",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{56}}},
 {["kind"]="counter_unit",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{16}}},
 {["kind"]="counter_unit",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{41}}},
 {["kind"]="counter_unit",["sets"]={["MANSION"]=true},["tiles"]={{54}}},
 {["kind"]="counter_unit",["sets"]={["MANSION"]=true},["tiles"]={{57}}},
 {["kind"]="table_edge",["sets"]={["HOUSE"]=true},["tiles"]={{38}}},
 {["kind"]="table_surface",["sets"]={["HOUSE"]=true},["tiles"]={{39}}},
 {["kind"]="table_edge",["sets"]={["HOUSE"]=true},["tiles"]={{41}}},
 {["kind"]="table_surface",["sets"]={["HOUSE"]=true},["tiles"]={{47}}},
 {["kind"]="table_edge",["sets"]={["HOUSE"]=true},["tiles"]={{54}}},
 {["kind"]="table_edge",["sets"]={["HOUSE"]=true},["tiles"]={{57}}},
 {["kind"]="table_surface",["sets"]={["HOUSE"]=true},["tiles"]={{58}}},
 {["kind"]="table_edge",["sets"]={["HOUSE"]=true},["tiles"]={{59}}},
 {["kind"]="table_edge",["sets"]={["HOUSE"]=true},["tiles"]={{60}}},
 {["kind"]="table_edge",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{38}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{39}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{40}}},
 {["kind"]="table_edge",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{41}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{42}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{43}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{44}}},
 {["kind"]="table_edge",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{54}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{55}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{56}}},
 {["kind"]="table_edge",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{57}}},
 {["kind"]="table_surface",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{58}}},
 {["kind"]="table_edge",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{59}}},
 {["kind"]="table_edge",["sets"]={["REDS_HOUSE_1"]=true,["REDS_HOUSE_2"]=true},["tiles"]={{60}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{63}}},
 {["kind"]="table_surface",["sets"]={["INTERIOR"]=true},["tiles"]={{64}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{72}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{74}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{75}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{76}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{77}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{78}}},
 {["kind"]="table_edge",["sets"]={["INTERIOR"]=true},["tiles"]={{79}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{9}}},
 {["kind"]="table_surface",["sets"]={["SHIP"]=true},["tiles"]={{10}}},
 {["kind"]="table_surface",["sets"]={["SHIP"]=true},["tiles"]={{11}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{12}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{25}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{26}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{28}}},
 {["kind"]="table_surface",["sets"]={["SHIP"]=true},["tiles"]={{44}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{59}}},
 {["kind"]="table_edge",["sets"]={["SHIP"]=true},["tiles"]={{60}}},
 {["kind"]="waiting_bench",["sets"]={["POKECENTER"]=true,["MART"]=true},["tiles"]={{90,91},{20,40}}},
 {kind="indoor_plant_0",sets={LAB=true},tiles={{44,45},{60,61},{46,47},{62,63}},variant=plant},
 {kind="woven_rug_32",sets={INTERIOR=true},tiles={{70,70,70,70},{71,71,71,71}}},
 {kind="woven_rug_32",sets={LOBBY=true},tiles={{4,4,4,4},{20,20,20,20}}},
 {kind="terrace_table",sets={LOBBY=true},tiles={{9,39,39,25},{54,55,55,57},{70,55,55,71},{85,86,87,55}}},
 {kind="wood_stool",sets={LOBBY=true},tiles={{7,8},{23,24}}},
 {kind="waiting_bench",sets={POKECENTER=true,MART=true},tiles={{90,91},{25,24}}},
 {kind="table_edge",sets={INTERIOR=true},tiles={{73}}},
 {kind="table_edge",sets={INTERIOR=true},tiles={{80}}},
 {kind="table_edge",sets={INTERIOR=true},tiles={{81}}},
 {kind="table_edge",sets={INTERIOR=true},tiles={{82}}},
 {kind="counter_unit",sets={POKECENTER=true,MART=true},tiles={{4}}},
 {kind="counter_unit",sets={POKECENTER=true,MART=true},tiles={{5}}},
 {kind="counter_unit",sets={POKECENTER=true,MART=true},tiles={{20}}},
 {kind="counter_unit",sets={POKECENTER=true,MART=true},tiles={{21}}},
 {kind="counter_unit",sets={POKECENTER=true,MART=true},tiles={{10}}},
 {kind="club_terminal",sets={CLUB=true},tiles={{32,33},{34,35},{36,37},{38,39}}},
 {kind="wood_stool",sets={CLUB=true},tiles={{48,49},{50,51}}},
 {kind="open_book_table",sets={SHIP=true},tiles={{68,69}}},
 {kind="dining_place",sets={SHIP=true},tiles={{64,65},{80,81}}},
 {kind="office_station",sets={INTERIOR=true},complete=true,tiles={{11,12,13,14},{27,28,29,30},{43,44,91,92},{59,60,31,31}}},
 {kind="cell_separator",sets={INTERIOR=true},maps={BILLS_HOUSE=true},complete=true,tiles={{16,7,8,9,10,16},{32,23,24,25,26,37},{48,39,40,41,42,53},{69,55,56,57,58,69},{31,80,1,2,15,31}}},
 {kind="office_station",sets={MANSION=true},complete=true,tiles={{36,37,52,53},{64,65,66,67},{2,3,85,86},{18,19,17,17}}},
 {kind="counter_corner",sets={GATE=true,FOREST_GATE=true,MUSEUM=true},tiles={{32,33},{50,51}}},
 {kind="woven_rug_32",sets={GATE=true,FOREST_GATE=true,MUSEUM=true},tiles={{4,4,4,4},{20,20,20,20}}},
 {kind="woven_rug_16",sets={GATE=true,FOREST_GATE=true,MUSEUM=true},tiles={{4,4},{20,20}}},
 {kind="counter_front",sets={GATE=true,FOREST_GATE=true,MUSEUM=true},tiles={{7},{50}}},
 {kind="console_tall",sets={FACILITY=true},complete=true,tiles={{13,14},{29,30},{74,75},{76,77}}},
 {kind="utility_table",sets={FACILITY=true},tiles={{13,2,2,14},{29,53,53,30},{29,53,53,30},{68,69,69,68}}},
 -- These computer tiles are reused as a continuous maze barrier in Rocket.
 {kind="facility_terminal",sets={FACILITY=true},tiles={{9,10},{25,26}},variant=function(map)
  if map.id=='SILPH_CO_1F'then return 'fountain_rim' end
  if map.id=='POKEMON_MANSION_1F' or map.id=='POKEMON_MANSION_2F'
    or map.id=='POKEMON_MANSION_3F' or map.id=='POKEMON_MANSION_B1F' then
   return 'mansion_storage_cabinet'
  end
  return (map.id=='ROCKET_HIDEOUT_B2F' or map.id=='ROCKET_HIDEOUT_B3F')
   and 'facility_partition' or 'facility_terminal'
 end},
 -- Warden's private exhibit is not the fossil lab or a movable boulder.
 {kind="warden_desk",sets={LAB=true},maps={WARDENS_HOUSE=true},complete=true,
  tiles={{64,65,65,66},{80,72,73,82},{6,7,8,9},{22,23,38,1}}},
 {kind="warden_display",sets={LAB=true},maps={WARDENS_HOUSE=true},complete=true,
  tiles={{87,88,88,89},{28,71,71,29},{36,24,25,37},{42,34,34,43}}},
 {kind="warden_specimen_0",sets={LAB=true},maps={WARDENS_HOUSE=true},
  tiles={{50,51},{67,68}},variant=function(map,x,y)return 'warden_specimen_'..phase(map,x,y,3)end},
 {kind="captain_chair",sets={SHIP=true},complete=true,tiles={{84,85},{66,67},{23,24}}},
 {kind="observation_binoculars",sets={GATE=true},maps={ROUTE_11_GATE_2F=true,
  ROUTE_12_GATE_2F=true,ROUTE_15_GATE_2F=true,ROUTE_16_GATE_2F=true,ROUTE_18_GATE_2F=true},
  tiles={{36,36},{52,52},{57,57}}}
}
