-- Complete, declarative ownership ledger for the byte-exact A21 Gen-2 tree.
-- Source bytes remain untouched; this table only assigns each imported file
-- to exactly one change surface so later fixes cannot overlap silently.
-- Keep additions outside the imported A21 baseline in Gen2SegmentCards.files.
-- FieldActorAppearance is one such addition; counting it here makes the
-- baseline invariant fail and prevents the entire Gen-2 mod from activating.

local M = {}

local OWNER = {
  ["gen2/DRAMALESS_LICENSE.txt"] = "vasc.gen2.bootstrap",
  ["gen2/MATCHING_GEN1RECOMP.txt"] = "vasc.gen2.bootstrap",
  ["gen2/UPSTREAMS.md"] = "vasc.gen2.bootstrap",
  ["gen2/WILDS_LICENSE.txt"] = "vasc.gen2.bootstrap",
  ["gen2/data/arena_scenery.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/data/battle_arenas.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/data/pokeball_mesh.lua"] = "vasc.gen2.voxel-world",
  ["gen2/data/vasc_battle_animations.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/data/voxel_heights.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/AmbientAudio.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/AndroidFullFrameFlip.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/AntiAlias.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/AscendantHudTheme.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/BattleAnimationCompat.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleArena.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleBackdrop.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleBillboard.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleCam.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleCinematic.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleControllerUI.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleDOF.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleEffectAnchors.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleHud.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattlePics.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattlePokemonControl.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleScene.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleStadium3DFx.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleStadiumAnimations.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BattleStadiumEffects.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/BuildBudget.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/Buildings.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/CamControl.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/CanvasPresentation.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/CategorizedModSettings.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/ChunkMesher.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/ContentJson.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/DayNight.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/DayTint.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/DeviceProfile.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/DioramaZoom.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/DirectModSettingsMenu.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/EmbeddedWildsMain.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/EngineCompat.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/FirstPerson.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2ArenaSkyResolver.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Gen2BattleCardHost.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Gen2BattleCommandNavigation.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Gen2BattleHpPresentation.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Gen2CaptureBallPresentation.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Gen2Comfort.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2CrystalFronts.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/Gen2KascQol.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/Gen2MapWarmup.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2MeshCache.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2MobileSceneryGate.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2NeighborWarmup.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2PerformancePolicy.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/Gen2PublicExports.lua"] = "vasc.gen2.bootstrap",
  ["gen2/lib/Gen2TrainerArt.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Gen2VascBattleAnimations.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Gen2WorldMap.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GlassMask.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GoldCameraControls.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GoldColorAtlas.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GoldComposeBridge.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GoldFieldMovePresentation.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/GoldFlyCinematic.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/GoldPartyFollower.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/GoldPipelineBridge.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GoldSubmenuBattleStyle.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/GoldVoxelBridge.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/GoldWildsBridge.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/HorizonWall.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/InteriorCutaway.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/LocalContent.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/LocalMusic.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/LocalSprites.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/LugiaGeoDump.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/LugiaRescue.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Mat4.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/MeshParts.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/ModMenuBattleStyle.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/ModSetting.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/ModSettingsPersistence.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/OpenWorldStreaming.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/OpenWorldZoom.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/OverworldBattle.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/OverworldCapture.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/OverworldStadium.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/OverworldStadiumConfig.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/PanoramaBackdrop.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/PartyModelPreview.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/PauseMenuBattleStyle.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/PixelCanvas.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/Pokedex.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/PokemonHeights.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/PokemonLocomotion.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/PokemonModelProvider.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/PresetRuntime.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/PublicFacade.lua"] = "vasc.gen2.bootstrap",
  ["gen2/lib/Quality.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/ShadowMap.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/ShadowPolicy.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Shadows.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/SharedVascMenuPresentation.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/Sky.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/SkyEvents.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/SpeciesFishingCinematic.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/SpriteBillboards.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/SpriteHooks.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/SpritePacks.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Stadium.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumBuild.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumFragment.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumFx.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumInstall.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumMon.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumPack.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumRig.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumRom.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumRom2.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumRomMenu.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/StadiumRomPick.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumScreen.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/StadiumStage.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/Structures.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/TerrainAtlas.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/TextBoxBattleStyle.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/ThirdPerson.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/TileShape.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/TitleMenuVascStyle.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/TransitionReveal.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/UiBackplates.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/UserFiles.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/VR.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VRRig.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VascBattleAnimPlayer.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/VascEnvironment.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VascMenuGen2.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/VascRendererOptions.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/Voxel3D.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VoxelDiskCache.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VoxelGrid.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VoxelScene.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VoxelScenePatch.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/VoxelState.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/WallDecals.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/WarpPrefetch.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Water.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/Weather.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/WeatherFootsteps.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/WeatherTweak.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/WorldCurve.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/WorldPlacement.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/ambient_cries.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/ambient_pokemon.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/animated_sprites.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/behavior.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/behavior_tick.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/adapters/gen2/Gen2BattleLifecycle.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/adapters/gen2/Gen2BattleRenderer.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/cave_reachability.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/cell_occupancy.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/cards/battle_router/Gen2BattleLifecycleCard.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/cards/battle_router/Gen2BattleRouterCard.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/cards/battle_router/Gen2DefaultBattleProviderCard.lua"] = "vasc.gen2.battle-presentation",
  ["gen2/lib/config.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/debug_hud.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/debug_log.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/debug_overlay.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/dev_overlay.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/diagnostics.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/encounter_index.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/encounter_pick.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/enhanced_world_sprite.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/compatibility.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/constants.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/control_engine.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/diagnostics.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/follower/init.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/interaction.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/lifecycle.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/selection.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/settings.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/sprite_service.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/follower/state.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/followers_water_compat.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/gold_visible_encounter_guard.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/grass.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/grass_occlusion.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/json_decode.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/luminance_sheet.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/movement.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/palette_watch.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/preview_browser.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/render_diagnostics.lua"] = "vasc.gen2.device-diagnostics",
  ["gen2/lib/runtime_sheets.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/safari_compat.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/settings_menus.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/spawn_fx.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/spawn_logic.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/spawn_regions.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/spawn_render.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/spawn_state.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/sprite_providers.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/sprite_resolver.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/sprite_scale.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/sprite_style_menu.lua"] = "vasc.gen2.menu-ui",
  ["gen2/lib/surface.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/tile.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/voxel_adapter.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/water_display.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/water_shadow_renderer.lua"] = "vasc.gen2.voxel-world",
  ["gen2/lib/water_spawn.lua"] = "vasc.gen2.field-wilds",
  ["gen2/lib/water_sprite_registry.lua"] = "vasc.gen2.field-wilds",
  ["gen2/main.lua"] = "vasc.gen2.bootstrap",
  ["gen2/options.lua"] = "vasc.gen2.bootstrap",
}

function M.filesFor(owner, extras)
  local result, seen = {}, {}
  for path, assigned in pairs(OWNER) do
    if assigned == owner then result[#result + 1], seen[path] = path, true end
  end
  for _, path in ipairs(extras or {}) do
    -- The complete A21 ledger is authoritative for gen2/**. Extras add only
    -- root adapters/Card infrastructure that are outside that imported tree.
    if OWNER[path] == nil and not seen[path] then
      result[#result + 1], seen[path] = path, true
    end
  end
  table.sort(result)
  return result
end

function M.owner(path) return OWNER[path] end
function M.count()
  local count = 0
  for _ in pairs(OWNER) do count = count + 1 end
  return count
end

return M
