-- Options for Voxel Ascendant's integrated Johto runtime.
-- Includes the embedded Wilds of Kanto roaming-spawn controls so this ZIP is standalone.
local platform = love and love.system and love.system.getOS and love.system.getOS()
local controlsTransparency = (platform == "iOS" or platform == "Android") and 40 or 20
return {
  {key="terarriumBehindRed",type="toggle",label="TERRARIUM: BEHIND TRAINER",default=false,description="View the Terrarium from behind the player instead of its side."},
  {key="terarriumIdleAnimation",type="toggle",label="TERRARIUM: IDLE MOTION",default=true,description="Gently rock the Terrarium while waiting in the command menu."},
  {key="terarriumIdleSound",type="toggle",label="TERRARIUM: IDLE SOUND",default=true,description="Play a quiet sound during idle motion."},
  {key="terarriumBallStyle",type="choice",label="TERRARIUM: BALL DESIGN",default="auto",choices={{"AUTO","auto"},{"POKE BALL","poke"},{"GREAT BALL","great"},{"ULTRA BALL","ultra"},{"MASTER BALL","master"},{"SAFARI BALL","safari"},{"RED APRICORN","apri_red"},{"BLUE APRICORN","apri_blue"},{"YELLOW APRICORN","apri_yellow"},{"GREEN APRICORN","apri_green"},{"PINK APRICORN","apri_pink"},{"BLACK APRICORN","apri_black"},{"WHITE APRICORN","apri_white"}},description="Choose the Terrarium shell."},
  {key="terarriumBackground",type="choice",label="TERRARIUM: BACKGROUND",default="auto",choices={{"AUTO","auto"},{"NIGHT","night"},{"FOREST","forest"},{"STONE","stone"},{"GALLERY","gallery"}},description="Choose the setting around the Terrarium."},
  {key="terarriumDome",type="choice",label="TERRARIUM: GLASS DOME",default="off",choices={{"OFF","off"},{"CLEAR","clear"},{"BLUE","blue"},{"PINK","rose"},{"GOLD","gold"}},description="Optional glass dome above the Terrarium."},
  {key="liveDisplay",type="toggle",label="LIVE DISPLAY",default=false,description="Show FPS, frame time and memory statistics."},
  {key="liveClock",type="toggle",label="CLOCK",default=true,description="Local device clock in the optional live display."},
  {key="liveFps",type="toggle",label="FPS + FRAME TIME",default=true,description="Frame rate and frame time in the optional live display."},
  {key="liveCpu",type="toggle",label="CPU FRAME TIME",default=true,description="CPU frame time in the optional live display."},
  {key="liveGpu",type="toggle",label="GPU TEXTURE MEMORY",default=true,description="Texture memory in the optional live display."},

  {
    key = "voxel3d",
    type = "toggle",
    label = "3D VOXEL WORLD",
    default = true,
    description = "Enables VASC's Gen-2 voxel terrain, Johto shapes and connected-map renderer. Turn this OFF for Gold/Silver/Crystal's untouched 2D overworld. Menu and battle presentation remain independently selectable under SKINS & OVERLAYS.",
  },
  {
    key = "gen2WorldMap",
    type = "toggle",
    label = "JOHTO ATLAS",
    default = true,
    description = "Shows Johto in VASC's widescreen Pokegear map. Additional native story content appears only after the game has legitimately unlocked it; FLY still lists only already visited destinations and the game owns every visited flag, spawn point and warp.",
  },
  {
    key = "stadium3dSprites",
    type = "toggle",
    label = "3D POKéMON MODELS",
    default = false,
    description = "OFF (default) uses the standing native Gold/Silver/Crystal front and back sprites in roaming, followers, menus and VASC battles; JASC and a Stadium ROM are not required. ON is an optional Stadium 2 model layer. The human player's first-/third-person model is controlled separately below.",
  },
  {
    key = "pokemonModelSkin",
    type = "choice",
    label = "POKéMON MODEL",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "CRYSTAL", "crystal" },
      { "STADIUM 1", "stadium1" },
      { "STADIUM 2", "stadium2" },
    },
    description = "Chooses the Pokemon actor only for MAP, ARENA or DISCS battles. CRYSTAL keeps the cartridge card. AUTO preserves the existing local Stadium 2 path. Stadium 1/2 require a compatible optional provider or a locally built legal ROM pack and fail closed to Crystal when unavailable. Native/OFF battles are never replaced.",
  },
  {
    key = "player3dModel",
    type = "toggle",
    label = "3D PLAYER MODEL",
    default = true,
    description = "Controls the human player model only. ON allows red_3d_player / 3D Character Selector to draw the currently selected 3D player skin inside the voxel world. OFF forces the player back to Gold's normal 2D trainer sprite/card while leaving Stadium Pokemon models, followers, battles, Pokedex previews, voxel terrain and OPEN WORLD untouched.",
  },
  {
    key = "openWorld",
    type = "toggle",
    label = "OPEN WORLD",
    default = false,
    description = "OFF (default) keeps the performance-friendly 3D streamer: current Gold map + directly connected neighbours. ON expands that same seamless outdoor renderer only as far as the active camera can use it: 1ST/3RD PERSON and close diorama views keep the direct ring, while pulling the diorama farther back progressively admits up to four cardinal map rings. Internal seams stay masked and the outside voxel border/apron prevents an empty edge. Zooming back in releases far meshes and per-map color atlases; unrelated remote Johto/Kanto terrain is never built merely because it exists in the ROM.",
  },
  {
    key = "voxelDiskCache",
    type = "toggle",
    label = "VOXEL DISK CACHE",
    default = true,
    description = "Caches expanded Gen-2 BODY and border meshes on fallback renderers in engine-owned, playthrough-scoped storage. Modern hardware instancing keeps compact GPU instance bundles instead and intentionally skips those expanded disk writes. Stale or incomplete fallback entries fail open to the normal asynchronous builder; disable only for cache diagnostics.",
  },
  {
    key = "grid",
    type = "toggle",
    label = "V-GRID",
    default = false,
    description = "Draws one-pixel voxel seams in the Gen-2 overworld. This is the VASC overworld grid control; battles have an independent BTL GRID switch.",
  },
  {
    key = "battleGrid",
    type = "toggle",
    label = "BTL GRID",
    default = true,
    description = "Draws voxel seams during live 3D battles independently of the overworld V-GRID setting.",
  },
  {
    key = "curve",
    type = "choice",
    label = "V-CURVE",
    default = 0,
    choices = {
      { "OFF", 0 },
      { "1", 1 },
      { "2", 2 },
      { "3", 3 },
    },
    description = "Curves distant terrain toward the horizon. Higher values increase the diorama/world-roll effect.",
  },
  {
    key = "water",
    type = "choice",
    label = "WATER",
    default = "full",
    choices = {
      { "FULL", "full" },
      { "SKY", "sky" },
      { "OFF", "off" },
    },
    description = "FULL enables depth-aware reflections; SKY keeps the cheaper sky reflection; OFF uses the basic water fallback.",
  },
  {
    key = "aa",
    type = "choice",
    label = "AA",
    default = 0,
    choices = {
      { "OFF", 0 },
      { "2X", 2 },
      { "4X", 4 },
    },
    description = "Supersamples the 3D pass. Higher values improve edges at a substantial GPU cost.",
  },
  {
    key = "sceneResolution",
    type = "choice",
    label = "3D RESOLUTION",
    default = "balanced",
    choices = { { "1080P", "balanced" }, { "NATIVE", "native" }, { "720P", "economy" } },
    description = "World and battle resolution: 1080P balances clarity and GPU cost; NATIVE uses the full view size; 720P reduces load. HUD stays sharp.",
  },
  {
    key = "renderScale",
    type = "choice",
    label = "SCENERY DETAIL",
    default = 2,
    choices = {
      { "1/2", 2 },
      { "FULL", 1 },
      { "1/3", 3 },
      { "1/4", 4 },
    },
    description = "Scenery detail budget for stars, fog and clouds. Use 3D RESOLUTION to change world and battle sharpness.",
  },
  {
    key = "shadowQuality",
    type = "choice",
    label = "SHADOWS",
    default = "low",
    choices = {
      { "LOW", "low" },
      { "OFF", "off" },
      { "HIGH", "high" },
      { "SOFT", "soft" },
    },
    description = "Controls 3D shadow-map cost and filtering. SOFT is intended for capable desktop GPUs; OFF is the safest mobile fallback.",
  },
  {
    key = "cameraControl",
    type = "choice",
    label = "VOXEL VIEW OWNER",
    default = "stadium",
    choices = {
      { "VOXEL ASCENDANT", "stadium" },
      { "VOXEL ASCENDANT (AUTO)", "auto" },
      { "CHARACTER SELECTOR", "selector" },
    },
    description = "VOXEL ASCENDANT owns DIORAMA, 3RD PERSON and 1ST PERSON by default. VOXEL ASCENDANT (AUTO) preserves the older saved compatibility value while keeping the local camera authoritative. CHARACTER SELECTOR is the explicit opt-in handoff to red_3d_player's public voxel camera ladder.",
  },
  {
    key = "cameraMode",
    type = "choice",
    label = "VOXEL VIEW",
    default = "full",
    choices = {
      { "FULL", "full" },
      { "15", "angle15" },
      { "35", "angle35" },
      { "50", "angle50" },
      { "75", "angle75" },
      { "1ST PERSON", "first" },
      { "3RD PERSON", "third" },
    },
    description = "The complete VASC voxel-view ladder: FULL preset, literal 15/35/50/75-degree orbit views, first person and third person. Old DIORAMA saves migrate to FULL. The V quick menu supports touch and R1 + START; desktop V or F6 walks the complete ladder. First/third person support mouse-look and controller right-stick look.",
  },
  {
    key = "worldZoomRange",
    type = "choice",
    label = "OPEN WORLD ZOOM LIMIT",
    default = "world",
    choices = {
      { "STANDARD 2.2X", "standard" },
      { "FAR 4X", "far" },
      { "WORLD 8X", "world" },
      { "EXTREME 12X", "extreme" },
    },
    description = "Maximum DIORAMA camera distance available through wheel/trackpad/pinch zoom. STANDARD keeps the old 2.2x limit; FAR reaches 4x; WORLD reaches 8x; EXTREME reaches 12x. Startup remains 1x. With OPEN WORLD enabled, the actual current distance also controls residency: close views keep one connected ring and wider views grow through two, three and at most four rings, then release them again when you zoom in. FAR/WORLD/EXTREME still unlock one engine-native 0.25-scale survey rung for Character Selector/native ZOOM compatibility.",
  },
  {
    key = "cameraSlider",
    type = "toggle",
    label = "ANDROID CAMERA SLIDER",
    default = true,
    description = "Shows the DIORAMA / 3RD / 1ST touch slider at the top of the screen on Android. Turn this OFF to completely hide the slider and release its touch area for camera look/pinch gestures.",
  },
  {
    key = "shortcutToast",
    type = "toggle",
    label = "SHORTCUT NOTICE",
    default = true,
    description = "Shows a short ORAS-style receipt in the upper-left after a successful VASC or host display shortcut, such as GAME SPEED or the V/F6 voxel camera ladder. The notice is presentation-only and can be disabled here.",
  },
  {
    key = "screenFlip",
    type = "toggle",
    label = "FLIP SCREEN 180 DEGREES",
    default = false,
    description = "Android emergency reverse-landscape helper. Rotates the ENTIRE finished Gold game frame 180 degrees after all rendering, including voxel world, menus, battle UI, overlays and on-screen touch controls. Touch coordinates are remapped by the same 180-degree transform so buttons still line up. Use this as a compatibility workaround on Android devices that insist on the wrong landscape side.",
  },
  {
    key = "vascMenuSkin",
    type = "choice",
    label = "VASC MENU",
    default = "oras_fullscreen",
    choices = {
      { "ORAS FULLSCREEN", "oras_fullscreen" },
    },
    description = "Presentation only for the shared VASC/KASC settings hub. ORAS FULLSCREEN is the responsive glass surface with permanent focused-row help. The legacy 160 by 144 renderer remains internal as an emergency fallback, not a selectable menu choice. Bag, PC, Box and ordinary Gold/Silver/Crystal menus are never changed by this option.",
  },
  {
    key = "qol_ui_skin",
    type = "choice",
    label = "OVERWORLD MENUS",
    default = "oras",
    choices = {
      { "ORAS GLASS", "oras" },
      { "GAME DEFAULT", "standard" },
    },
    description = "Shared VASC presentation for Gold, Silver and Crystal's native dialogue, choice, title, START and ordinary list surfaces. ORAS GLASS changes only drawing; input, pagination, callbacks and game rules remain engine-owned. GAME DEFAULT restores the untouched edition UI live. The separate VASC MENU option owns only the Voxel Ascendant settings hub.",
  },
  {
    key = "qol_bag_skin",
    type = "choice",
    label = "BAG MENU",
    default = "oras_wide",
    choices = {
      { "D/P ORAS WIDE", "oras_wide" },
      { "FRLG ORAS WIDE", "frlg_wide" },
      { "GAME DEFAULT", "external" },
    },
    description = "Draw-only presentation for Gold, Silver and Crystal's real PACK. D/P ORAS WIDE is the default; FRLG ORAS WIDE is the alternate reviewed VASC layout. GAME DEFAULT delegates to the exact native PACK renderer. Items, pockets, counts, registration, use, giving, tossing and callbacks always remain game-owned, and every presentation error fails open to the native PACK.",
  },
  {
    key = "qol_bag_color",
    type = "choice",
    label = "BAG ACCENT",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "RED", "red" },
      { "BLUE", "blue" },
      { "GREEN", "green" },
    },
    description = "Accent colour for either selected VASC wide Bag. AUTO keeps the reviewed neutral trainer accent. This setting is ignored by GAME DEFAULT and never changes PACK behaviour.",
  },
  {
    key = "qol_bag_body",
    type = "choice",
    label = "BAG EDITION COLOR",
    default = "auto",
    choices = {
      { "AUTO EDITION", "auto" },
      { "ORAS ORIGINAL", "oras" },
      { "GOLD", "gold" },
      { "SILVER", "silver" },
      { "CRYSTAL", "crystal" },
    },
    description = "Body colour for either selected VASC wide Bag. AUTO follows the active Gold, Silver or Crystal edition; ORAS ORIGINAL keeps the source artwork. GAME DEFAULT remains untouched.",
  },
  {
    key = "qol_bag_form",
    type = "choice",
    label = "BAG FORM",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "ROUND", "round" },
      { "HANDLE", "handle" },
    },
    description = "Bag silhouette for either selected VASC wide Bag. AUTO uses the reviewed round Johto default. This is presentation-only and is ignored by GAME DEFAULT.",
  },
  {
    key = "pokedexStyle",
    type = "choice",
    label = "POKéDEX",
    default = "modern",
    choices = {
      { "VASC WIDESCREEN", "modern" },
      { "GAME DEFAULT", "game" },
    },
    description = "VASC WIDESCREEN presents the native 251-entry Gen-2 Pokédex in the responsive Ascendant layout. GAME DEFAULT restores Gold, Silver or Crystal's exact Pokédex screens and ordering. Seen/caught flags, entries, cries, area data, input and return callbacks always remain game-owned; postgame region labels stay hidden until Hall of Fame.",
  },
  {
    key = "modernDexSpriteSource",
    type = "choice",
    label = "DEX SPRITES",
    default = "crystal",
    choices = {
      { "CRYSTAL FRONTS", "crystal" },
      { "ACTIVE 3D / SPRITE", "active" },
      { "GAME ORIGINAL", "game" },
    },
    description = "Image source only inside VASC WIDESCREEN Pokédex. CRYSTAL FRONTS uses VASC's bundled coloured Crystal menu fronts; ACTIVE may use the optional Stadium 2 preview and safely falls back to the game sprite; GAME ORIGINAL always uses the active cartridge front. Battles, team, boxes and overworld sprites are not changed.",
  },
  {
    key = "pokemonUiPcBox", type = "choice", label = "PC BOX UI",
    default = "asc_box",
    choices = { { "ASC BOX", "asc_box" }, { "GAME DEFAULT", "game_default" } },
    description = "ASC BOX uses the shared storage grid, party strip and search. GAME DEFAULT restores the native Gen2 box list. Pokemon, mail, eggs and saved boxes stay in the same storage.",
  },
  {
    key = "pokemonUiPartyMenu",
    type = "choice",
    label = "START TEAM UI",
    default = "oras",
    choices = {
      { "ORAS GLASS", "oras" },
      { "GAME DEFAULT", "standard" },
    },
    description = "Presentation of the normal Gold/Silver/Crystal party and summary screens opened from START. ORAS GLASS changes drawing only; the native party callbacks, field moves, switching and save data remain authoritative.",
  },
  {
    key = "pokemonUiBattleParty",
    type = "choice",
    label = "BATTLE TEAM UI",
    default = "oras",
    choices = {
      { "ORAS GLASS", "oras" },
      { "GAME DEFAULT", "standard" },
    },
    description = "Presentation of the team/switch selector during ordinary Gen-2 battles. ORAS GLASS presents the native Gen2PartyMenu semantics in the shared ORAS fullscreen team view; GAME DEFAULT opens Gold/Silver/Crystal's unchanged party screen. Tutorial, contest and other special battle screens always fail open to the game UI.",
  },
  {
    key = "pokemonUiLegacyBank",
    type = "choice",
    label = "LEGACY BANK UI",
    default = "follow_global",
    choices = {
      { "FOLLOW GLOBAL", "follow_global" },
      { "ASC BOX", "asc_box" },
      { "GAME DEFAULT", "game_default" },
    },
    description = "Prepared public UI hook for a future JASC Legacy Bank. ASC BOX presents only an externally registered authoritative bank host; GAME DEFAULT always yields to that companion's own screen. Without a registered bank host this row is dormant; the ordinary PC has its own PC BOX UI setting.",
  },
  { key="battle_textbox_x", type="choice", label="TEXTBOX X", default=0,
    choices={{"-60%", -60}, {"-55%", -55}, {"-50%", -50}, {"-45%", -45}, {"-40%", -40}, {"-35%", -35}, {"-30%", -30}, {"-25%", -25}, {"-20%", -20}, {"-15%", -15}, {"-10%", -10}, {"-5%", -5}, {"0%", 0}, {"+5%", 5}, {"+10%", 10}, {"+15%", 15}, {"+20%", 20}, {"+25%", 25}, {"+30%", 30}, {"+35%", 35}, {"+40%", 40}, {"+45%", 45}, {"+50%", 50}, {"+55%", 55}, {"+60%", 60}},
    description="Move the battle textbox horizontally. Default: 0%." },
  { key="battle_textbox_y", type="choice", label="TEXTBOX Y", default=0,
    choices={{"-60%", -60}, {"-55%", -55}, {"-50%", -50}, {"-45%", -45}, {"-40%", -40}, {"-35%", -35}, {"-30%", -30}, {"-25%", -25}, {"-20%", -20}, {"-15%", -15}, {"-10%", -10}, {"-5%", -5}, {"0%", 0}, {"+5%", 5}, {"+10%", 10}, {"+15%", 15}, {"+20%", 20}, {"+25%", 25}, {"+30%", 30}, {"+35%", 35}, {"+40%", 40}, {"+45%", 45}, {"+50%", 50}, {"+55%", 55}, {"+60%", 60}},
    description="Move the battle textbox vertically (negative = up). Default: 0%." },
  { key="battle_controls_scale", type="choice", label="BUTTON SIZE", default=1,
    choices={{"50%", 0.5}, {"75%", 0.75}, {"90%", 0.9}, {"100%", 1}, {"110%", 1.1}, {"125%", 1.25}, {"150%", 1.5}},
    description="Scale battle buttons and move selection independently. Default: 100%." },
  { key="battle_controls_x", type="choice", label="BUTTON X", default=0,
    choices={{"-40%", -40}, {"-35%", -35}, {"-30%", -30}, {"-25%", -25}, {"-20%", -20}, {"-15%", -15}, {"-10%", -10}, {"-5%", -5}, {"0%", 0}, {"+5%", 5}, {"+10%", 10}, {"+15%", 15}, {"+20%", 20}, {"+25%", 25}, {"+30%", 30}, {"+35%", 35}, {"+40%", 40}},
    description="Move battle controls horizontally as a percentage of the viewport. Default: 0%." },
  { key="battle_controls_y", type="choice", label="BUTTON LIFT", default=0,
    choices={{"0%", 0}, {"5%", 5}, {"10%", 10}, {"15%", 15}, {"20%", 20}, {"25%", 25}, {"30%", 30}, {"35%", 35}, {"40%", 40}, {"45%", 45}, {"50%", 50}, {"55%", 55}, {"60%", 60}},
    description="Raise battle controls and automatically complete original artwork. GLASS remains selected. Default: 0%." },
  { key="battle_controls_transparency", type="choice", label="BUTTON TRANSPARENCY", default=controlsTransparency,
    choices={{"0%", 0}, {"10%", 10}, {"20%", 20}, {"30%", 30}, {"40%", 40}, {"50%", 50}, {"60%", 60}, {"70%", 70}, {"80%", 80}, {"90%", 90}},
    description="Transparency of battle controls including Mega, attacks and Back. 0% keeps the original appearance; higher values reveal more of the scene." },
  { key="battle_controls_shape", type="choice", label="BUTTON SHAPE", default="auto",
    choices={{"AUTO", "auto"}, {"ORIGINAL", "original"}, {"COMPLETE ORAS", "round"}, {"GLASS", "glass"}},
    description="AUTO completes artwork whenever the controls sit above the screen edge or are adjusted. COMPLETE ORAS always shows full artwork; GLASS selects transparent alternative buttons." },
  {
    key = "battleHudStyle",
    type = "choice",
    label = "BATTLE HUD",
    default = "oras",
    choices = {
      { "ORAS GLASS", "oras" },
      { "GAME DEFAULT", "standard" },
    },
    description = "ORAS GLASS draws VASC's readable widescreen HP, message and command presentation. GAME DEFAULT keeps Gold, Silver or Crystal's native HUD, text and controls over the selected MAP, ARENA or DISCS world; choose GAME DEFAULT under BATTLE WORLD for the complete native battle scene. Any staged-renderer error fails open to that native scene.",
  },
  {
    key = "speciesSurfPresentation",
    type = "choice",
    label = "SURF ANIMATION",
    default = "vasc",
    choices = {
      { "VASC", "vasc" },
      { "VANILLA", "vanilla" },
    },
    description = "VASC (default) shows the exact Pokémon selected for native Gen-2 SURF. VANILLA uses Gold, Silver or Crystal's unchanged Surf animation. Eligibility, movement, music and saves always remain game-owned.",
  },
  {
    key = "fieldKitPresentation",
    type = "toggle",
    label = "FIELD KIT / JETSKI",
    default = false,
    description = "Optional Johto Field Kit presentation. ON may replace an explicitly kit-driven Surf presentation with VASC's jetski; OFF (default) never invents a kit user. Native field-move rules and callbacks are not changed.",
  },
  {
    key = "speciesFlyPresentation",
    type = "choice",
    label = "FLY ANIMATION",
    default = "vasc",
    choices = {
      { "VASC", "vasc" },
      { "VANILLA", "vanilla" },
    },
    description = "VASC (default) shows the exact Pokémon selected for native Gen-2 FLY. VANILLA uses Gold, Silver or Crystal's unchanged Fly animation. Destination, warp, callback and music ownership stay with the game.",
  },
  {
    key = "fishingPresentation",
    type = "choice",
    label = "FISHING CINEMATIC",
    default = "vasc",
    choices = {
      { "VASC", "vasc" },
      { "VANILLA", "vanilla" },
    },
    description = "VASC (default) draws the rod, line, bobber and catch pull around native Gen-2 fishing. VANILLA uses the unchanged game animation. Rod results, encounters and catches are never modified.",
  },
  {
    key = "qolExpBar",
    type = "choice",
    label = "BATTLE EXP BAR",
    default = "blue",
    choices = {
      { "OFF", "off" },
      { "BLACK", "black" },
      { "BLUE", "blue" },
    },
    description = "Adds a read-only experience bar to VASC's ORAS battle status card. BLUE is the default; BLACK changes only the bar colour and OFF hides it. Native experience gain and level-up timing are untouched.",
  },
  {
    key = "qolCaughtIndicator",
    type = "choice",
    label = "CAUGHT INDICATOR",
    default = "red",
    choices = {
      { "OFF", "off" },
      { "GREY", "grey" },
      { "RED", "red" },
    },
    description = "Shows a small read-only Poké Ball marker on the enemy card when the species is already registered as caught. RED is the default; GREY changes its colour and OFF hides it. Pokédex flags are only read, never written.",
  },
  {
    key = "battleGender",
    type = "toggle",
    label = "BATTLE GENDER",
    default = true,
    description = "Shows the native Gen-2 gender symbol next to a battler's name in VASC's ORAS HUD. ON is the default; OFF hides it. This does not affect breeding, stats or battle rules.",
  },
  {
    key = "statusValues",
    type = "choice",
    label = "STATUS VALUES",
    default = "off",
    choices = {
      { "OFF", "off" },
      { "DVs", "dv" },
      { "DVs + STAT EXP", "full" },
    },
    description = "Read-only detail for ORAS summary and wild-battle presentation. DVs shows the native Gen-2 determinant values; FULL also shows available Stat Exp. OFF is the default. No Pokémon data is changed.",
  },
  {
    key = "qolLocationBanners",
    type = "choice",
    label = "LOCATION BANNERS",
    default = 2,
    choices = {
      { "OFF", "off" },
      { "1 SECOND", 1 },
      { "2 SECONDS", 2 },
      { "3 SECONDS", 3 },
    },
    description = "Shows a responsive VASC place banner after a real Gen-2 map transition. Two seconds is the default; OFF hides it. The setting changes presentation only.",
  },
  {
    key = "qolEasyInteractions",
    type = "toggle",
    label = "EASY INTERACTIONS",
    default = true,
    description = "Gen-2-native convenience adapter for safe facing interactions. ON is the default and may streamline an existing legal interaction; OFF restores only the native inputs. It never grants a move, item, badge, warp or field permission.",
  },
  {
    key = "qolRegisteredItem",
    type = "toggle",
    label = "REGISTERED ITEM / SELECT",
    default = true,
    description = "Uses Gold, Silver and Crystal's native PACK SEL assignment and SELECT-button field-item path. ON is the KASC-compatible default; OFF pauses registering and SELECT use without deleting the saved assignment. Item ownership, legality, consumption and effects stay game-owned.",
  },
  {
    key = "qolCatchBoxNotice",
    type = "toggle",
    label = "CATCH BOX NOTICE",
    default = true,
    description = "After a real full-party capture is stored, adds the exact destination box number to the native catch messages. ON is the default; OFF keeps only Gold, Silver or Crystal's BILL's PC message. Party and box placement are never changed.",
  },
  {
    key = "qolFastBoxSwitch",
    type = "toggle",
    label = "FAST BOX SWITCH",
    default = true,
    description = "Lets LEFT/RIGHT switch directly between storage boxes in the native WITHDRAW list. ON is the KASC-compatible default; OFF disables only that shortcut. Navigation required by MOVE POKéMON remains available so no storage operation can be stranded.",
  },
  {
    key = "qolModernBallSkins",
    type = "toggle",
    label = "MODERN BALL SKINS",
    default = true,
    description = "Applies distinct modern four-colour palettes to the real Gen-2 thrown-ball sprite. ON is the default; OFF restores native ball palettes from the next throw. Sprite timing, ball effects, catch rates, shakes and results are untouched.",
  },
  {
    key = "partyFollower",
    type = "toggle",
    label = "LEAD PARTY FOLLOWER",
    default = true,
    description = "Makes the selected party slot follow directly behind the player. Slot 1 is the default, so using PARTY -> SWITCH changes the leader immediately. With 3D POKéMON MODELS off, the follower uses the native GSC sprite provider; Stadium 2 remains an optional layer. Turn OFF to remove party followers.",
  },
  {
    key = "battle3dWorld",
    type = "choice",
    label = "BATTLE WORLD",
    default = true,
    choices = {
      { "MAP", true },
      { "ARENA", "arena" },
      { "DISCS", "discs" },
      { "TERRARIUM", "terarrium" },
      { "GAME DEFAULT", false },
    },
    description = "MAP keeps the exact voxel encounter view. ARENA uses a reviewed/authored map stage. DISCS uses the portable Stadium platforms. GAME DEFAULT restores Gold, Silver or Crystal's complete native battle scene. The quick menu can switch this during command or move selection without restarting the battle.",
  },
  {
    key = "battleSmartCamera",
    type = "toggle",
    label = "STADIUM BATTLE CAMERA",
    default = true,
    description = "ON (default): staged MAP, ARENA and DISCS battles use their cinematic camera contract. OFF holds the authored battle-start view. The quick menu applies this during command or move selection.",
  },
  {
    key = "deviceProfile",
    type = "choice",
    label = "VASC DEVICE PROFILE",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "LIGHT", "light" },
      { "BALANCED", "balanced" },
      { "HIGH", "high" },
      { "ULTRA", "ultra" },
      { "CUSTOM", "custom" },
    },
    description = "Current VASC performance preset. AUTO selects LIGHT, BALANCED or HIGH from the engine's initial hardware tier; ULTRA is always an explicit opt-in. LIGHT keeps the complete game and VASC menus while reducing only expensive renderer passes. Changing managed visual rows keeps their individual values as CUSTOM.",
  },
  {
    key = "sky",
    type = "choice",
    label = "SKY",
    default = "full",
    choices = {
      { "FULL", "full" },
      { "FLAT", "flat" },
      { "OFF", "off" },
    },
    description = "FULL enables VASC's time-aware pixel sky, sun/moon, stars and atmospheric layers. FLAT keeps only the inexpensive horizon colour; OFF disables the outdoor backdrop.",
  },
  {
    key = "clouds",
    type = "choice",
    label = "CLOUDS",
    default = "on",
    choices = {
      { "ON", "on" },
      { "OFF", "off" },
    },
    description = "World-anchored pixel clouds using the current VASC cloud atlas and day/night/weather palette.",
  },
  {
    key = "skyEvents",
    type = "choice",
    label = "SKY EVENTS",
    default = "full",
    choices = {
      { "FULL", "full" },
      { "RAINBOW", "rainbow" },
      { "FLYERS", "flyers" },
      { "OFF", "off" },
    },
    description = "Deterministic rainbows, flocks and legendary flyovers. Gen2 also gains the current weather-linked Lugia/Ho-Oh appearances without shipping game ROM art.",
  },
  {
    key = "weather",
    type = "choice",
    label = "WEATHER",
    default = "auto",
    choices = {
      { "AUTO", "auto" },
      { "CLEAR", "clear" },
      { "RAIN", "rain" },
      { "SNOW", "snow" },
      { "FOG", "fog" },
      { "STORM", "storm" },
      { "HEAT", "heat" },
      { "RAINBOW", "rainbow" },
    },
    description = "Current VASC outdoor weather director: one regional AUTO front every four minutes across map transitions, four fronts per season, plus direct rain, snow, fog, storm/lightning, heat and rainbow previews. Interiors remain clear and live overworld battles keep the map weather.",
  },
  {
    key = "weatherTweak",
    type = "choice",
    label = "WX MICRO EVENTS",
    default = "subtle",
    choices = {
      { "OFF", "off" },
      { "SUBTLE", "subtle" },
      { "FULL", "full" },
    },
    description = "Optional additive detail over canonical VASC weather. Normal rain stays untouched. SUBTLE (default) and FULL add bounded regional wind, storm leaves, hail, fireflies, fog spray, dust, ash, rare meteors, gradual surfaces, footsteps and safe brief music ducking without changing battle rules.",
  },
  {
    key = "scenery",
    type = "choice",
    label = "SCENERY / PANORAMA",
    default = "full",
    choices = {
      { "FULL", "full" },
      { "OFF", "off" },
    },
    description = "VASC's streamed-edge scenery, cave/room enclosures and distant panorama. Postgame maps use their authored profiles; Johto uses the safe generic class/tileset fallback until dedicated Johto panorama art is added.",
  },
  {
    key = "shadows",
    type = "toggle",
    label = "OBJECT SHADOWS",
    default = true,
    description = "Master switch for VASC object-anchored world and character shadows. SHADOWS quality above still controls resolution/filtering.",
  },
  {
    key = "daytime",
    type = "choice",
    label = "DAYTIME",
    default = "native",
    choices = {
      { "GAME / RTC", "native" },
      { "FREE RUN", "cycle" },
      { "DAY", "day" },
      { "NIGHT", "night" },
      { "DUSK", "dusk" },
      { "DAWN", "dawn" },
    },
    description = "GAME / RTC follows Gold, Silver or Crystal's own journey clock and keeps its palettes, encounters and VASC sky aligned. FREE RUN keeps the saved 20-minute VASC cycle; the other choices pin a phase.",
  },
  {
    key = "stadiumRomFile",
    type = "choice",
    label = "STADIUM 2 ROM FILE (GEN 2)",
    default = "choose",
    choices = {
      { "CHOOSE", "choose" },
    },
    description = "Choose your legally obtained Pokemon Stadium 2 ROM to build 3D models for National Dex 1-251.",
  },
  -- ------- Core gameplay
  {
    key = "enabled",
    label = "Show Wild Mons",
    type = "toggle",
    default = true,
    description = "Spawn visible wild Pokemon in eligible overworld encounter areas.",
  },
  {
    key = "sprite_style",
    label = "Sprite Style",
    type = "choice",
    default = "followers",
    choices = {
      { "Poke Followers / GSC", "followers" },
      { "HGSS / PokeMMO", "pokemmo" },
      { "Pokédex", "pokedex" },
    },
    description = "Overworld sprite style for wild Pokémon and followers. Poke Followers / GSC is the built-in default. Water Pokémon still use Swimming or Levitates sprites when available.",
  },
  {
    key = "sprite_fade",
    label = "Sprite Fade",
    type = "choice",
    default = "solid",
    choices = {
      { "Solid", "solid" },
      { "Faded", "faded" },
    },
    description = "Opacity of normal visible wild Pokémon. Solid is fully opaque. Faded uses the classic semi-transparent wild look. Does not affect followers, Town Pokémon, silhouettes, or UI.",
  },
  {
    key = "follow_control",
    label = "Control Mode",
    type = "choice",
    default = "trainer",
    choices = {
      { "Trainer", "trainer" },
      { "Pokémon", "pokemon" },
    },
    description = "Choose whether you control the trainer or the selected Pokémon.",
  },
  {
    key = "trainer_trail",
    label = "Trainer Trail",
    type = "toggle",
    default = false,
    description = "When controlling a Pokémon, the trainer follows behind.",
  },
  {
    key = "follower_count",
    label = "Followers",
    type = "choice",
    default = 1,
    choices = {
      { "0", 0 },
      { "1", 1 },
      { "2", 2 },
      { "3", 3 },
      { "4", 4 },
      { "5", 5 },
      { "6", 6 },
    },
    description = "Number of additional party Pokémon following the active leader.",
  },
  {
    key = "spawn_density",
    label = "Spawn Amount",
    type = "choice",
    default = "normal",
    choices = {
      { "Low", "low" },
      { "Normal", "normal" },
      { "High", "high" },
      { "Very High", "very_high" },
    },
    description = "Controls how many visible overworld Pokémon can appear. This also affects visible water Pokémon.",
  },
  {
    key = "random_encounters",
    label = "Classic Step Enc",
    type = "toggle",
    default = false,
    description = "OFF is the visible-only mode: normal grass/cave step encounters are blocked so every ordinary encounter comes from a Pokemon you can see and touch. Turn ON only if you also want classic invisible random steps.",
  },
  {
    key = "water_spawns",
    label = "Water Mons",
    type = "choice",
    default = "swimming_sprites",
    choices = {
      { "Swim Sprites", "swimming_sprites" },
      { "Hid Silhouette", "hidden_silhouettes" },
      { "Silhouettes", "silhouettes" },
      { "Classic Enc", "classic_encounters" },
      { "Disabled", "disabled" },
    },
    description = "How water Pokémon appear: swimming sprites (default), hidden dark circles, tinted silhouettes, classic random encounters only, or fully disabled.",
  },
  {
    key = "cave_spawns",
    label = "Cave Spawns",
    type = "choice",
    default = "reachable",
    choices = {
      { "Reachable Only", "reachable" },
      { "Mixed", "mixed" },
    },
    description = "Cave Pokémon spawn only on tiles the player can reach, or Mixed (~20% atmospheric scenery in inaccessible cave pockets).",
  },
  {
    key = "town_pokemon",
    label = "Town Pokémon",
    type = "toggle",
    default = true,
    description = "Adds peaceful Pokémon to safe towns and interiors. They behave like NPCs and cannot start battles.",
  },
  {
    key = "pokemon_grass_render_mode",
    label = "Grass View",
    type = "choice",
    default = "immersed",
    choices = {
      { "Above", "above" },
      { "Immersed", "immersed" },
    },
    description = "Draw wild Pokemon fully above tall grass, or partially hidden inside it like the player and trainers.",
  },
  {
    key = "wild_silhouettes",
    label = "Enc Silhouette",
    type = "toggle",
    default = false,
    description = "Black out overworld wild Pokémon in encounter zones (grass/cave/water) as silhouettes, keeping their shapes. Derived from the coloured art at load — no extra sprite files.",
  },
  {
    key = "enable_idle",
    label = "Idle Mons",
    type = "toggle",
    default = true,
    description = "Allow Idle Look behaviour (stand still, glance around).",
  },
  {
    key = "enable_wander",
    label = "Roam Mons",
    type = "toggle",
    default = true,
    description = "Allow wander behaviour within a connected encounter region.",
  },
  {
    key = "enable_aggressive",
    label = "Chase Mons",
    type = "toggle",
    default = true,
    description = "Allow aggressive Pokemon that spot, chase, and force a battle.",
  },
  {
    key = "enable_hidden",
    label = "Hidden Mons",
    type = "toggle",
    default = false,
    description = "Disabled for Gold/Silver visible-roaming mode; encounter Pokemon are shown on the map.",
  },

  -- ------- Developer (only Dev Overlay + Test Spawn)
  {
    key = "dev_overlay",
    label = "Dev Overlay",
    type = "toggle",
    default = false,
    description = "Shows each wild Pokémon's behaviour and facing direction above it.",
  },
}
