-- Copyright (c) 2026 Cedric. All rights reserved.
-- Source-available under the Gen2Recomped License (see LICENSE.md): you may
-- read, build and privately modify this file; you may not redistribute it or
-- use it commercially.  Cartridge-derived data is excluded and is not the
-- copyright holder's to license.

-- WHAT IS BURIED IN AN UNDERGROUND WALL, and how likely each thing is.
--
-- These are pokeplatinum's `sMiningObjects` (src/underground/mining.c), its
-- `MiningObjectID` enum and its `sMiningItems` map (src/underground.c), written
-- out as data.  NO CARTRIDGE BYTES ARE STORED HERE: the table is compiled into
-- an ARM9 overlay rather than sitting in a NARC, so there is no file to read and
-- these are names and numbers for a table the player's own ROM contains -- the
-- same footing as Gen4Behaviors' name list.
--
-- FOUR WEIGHTS PER ROW, and they are not four spellings of one number.  The
-- cartridge picks by the PARITY OF THE TRAINER ID and whether the National Dex
-- has been obtained (Mining_GetWeightOfItem):
--
--     if (isNationalDexObtained) {
--         weight += isTrainerIDOdd ? oddTIDNatDexWeight : evenTIDNatDexWeight;
--     } else {
--         weight += isTrainerIDOdd ? oddTIDWeight : evenTIDWeight;
--     }
--
-- The four columns total 1017, 1015, 987 and 1019 -- four different numbers, so
-- an implementation that collapsed them into one would be wrong in a way no
-- single dig would reveal.  Armor Fossil and Skull Fossil are the clearest case:
-- each has weight 0 on one TID parity and 25 on the other, which is how a save
-- gets one of the pair and not the other.
--
-- OCCUPANCY IS GENERATED BY SIMULATING THE CARTRIDGE'S OWN READ, not by
-- transcribing the shape initialisers.  `Mining_AreCoordinatesWithinObjectShape`
-- indexes `shape[row * (width / 2) + column]` -- a FLAT read whose stride is the
-- record's cell width -- and that is not always the declared array's stride.
-- Checked across all 43 shapes and 85 rows, exactly one disagrees:
--
--   `sDampRockShape` is declared `[3][4]` with rows of three, so the compiler
--   pads each row to four bytes, while the record says `width = 3 * 2` and the
--   read strides by three.  The 'o' the initialiser puts at row 2 column 1 sits
--   at byte 9; the stride-3 read reaches bytes 0..8 and never sees it, landing
--   on zero padding at bytes 3 and 7 instead -- neither of which is 'o'.  THE
--   DAMP ROCK IS A SOLID 3x3 IN THE GAME.  Transcribing the initialiser would
--   have given it a notch it does not have.
--
-- The other 42 shapes agree either way, which is the control: if the read were
-- being modelled wrongly, they would not.
--
-- `nil` occupancy means a full rectangle (`shape == NULL`, which the cartridge
-- short-circuits to TRUE).  A row string is one character per CELL, '1' solid
-- and '0' a hole.

local Gen4Mining = {}

-- #define MINING_GAME_WIDTH 13 / _HEIGHT 10 / MAX_BURIED_ITEMS 4 (mining.c).
-- The grid is in cells; a record's width/height are in HALF-cells in the
-- cartridge (written `N * 2`) and are stored here already halved.
Gen4Mining.GRID_WIDTH = 13
Gen4Mining.GRID_HEIGHT = 10
Gen4Mining.MAX_BURIED_ITEMS = 4

-- #define MAX_BURIED_OBJECTS 8 (mining.c).  The TOTAL slots, treasures and
-- rocks together -- which is why the rock loop's own `if (objectsPlaced > 12)
-- break;` is dead code and the cartridge says so: placement starts failing at
-- eight, so the count cannot reach thirteen.
Gen4Mining.MAX_BURIED_OBJECTS = 8

-- MINING_PLATES_START / _MAX (underground.c) -- MINING_TREASURE_FLAME_PLATE
-- through MINING_TREASURE_IRON_PLATE, the sixteen Arceus plates.  A plate is
-- once-per-save: `Underground_HasPlateNeverBeenMined` tests bit
-- `id - PLATES_FIRST` of `minedPlates`, and a plate already mined is re-rolled
-- rather than placed.  Everything outside this range answers TRUE unconditionally.
Gen4Mining.PLATES_FIRST = 44
Gen4Mining.PLATES_LAST = 59

function Gen4Mining.isPlate(id)
  return id ~= nil and id >= Gen4Mining.PLATES_FIRST and id <= Gen4Mining.PLATES_LAST
end

-- MINING_TREASURE_OVAL_STONE, which `Underground_ConvertTreasureToBagItem`
-- subtracts before indexing `sMiningItems`, and MINING_ROCK_1 -- which is the
-- same number as MINING_TREASURE_MAX, and that identity is load-bearing:
-- `Mining_PickItem` and `Mining_GetTotalItemWeight` both stop at the first row
-- whose itemID equals MINING_TREASURE_MAX, so the FOURTEEN ROCK ROWS ARE NOT IN
-- THE WEIGHTED POOL.  Rocks are placed by a separate hundred-try loop.
Gen4Mining.TREASURE_START = 11
Gen4Mining.ROCK_FIRST = 60


-- itemID, the four weights, size in cells, occupancy, and the NARC member
-- names the sprites come from (not yet extracted -- see ug_parts.narc).
Gen4Mining.OBJECTS = {
  { name = "MINING_SMALL_PRISM_SPHERE", id = 1, w = 2, h = 2,
    oddTID = 30, evenTID = 22, oddTIDDex = 27, evenTIDDex = 20,
    occ = nil,
    sprite = "small_prism_sphere_NCGR", palette = "prism_sphere_NCLR" },
  { name = "MINING_SMALL_PALE_SPHERE", id = 2, w = 2, h = 2,
    oddTID = 22, evenTID = 30, oddTIDDex = 20, evenTIDDex = 27,
    occ = nil,
    sprite = "small_pale_sphere_NCGR", palette = "pale_sphere_NCLR" },
  { name = "MINING_SMALL_RED_SPHERE", id = 3, w = 2, h = 2,
    oddTID = 167, evenTID = 194, oddTIDDex = 110, evenTIDDex = 164,
    occ = nil,
    sprite = "small_red_sphere_NCGR", palette = "red_sphere_NCLR" },
  { name = "MINING_SMALL_BLUE_SPHERE", id = 4, w = 2, h = 2,
    oddTID = 194, evenTID = 167, oddTIDDex = 150, evenTIDDex = 124,
    occ = nil,
    sprite = "small_blue_sphere_NCGR", palette = "blue_sphere_NCLR" },
  { name = "MINING_SMALL_GREEN_SPHERE", id = 5, w = 2, h = 2,
    oddTID = 150, evenTID = 150, oddTIDDex = 107, evenTIDDex = 107,
    occ = nil,
    sprite = "small_green_sphere_NCGR", palette = "green_sphere_NCLR" },
  { name = "MINING_LARGE_PRISM_SPHERE", id = 6, w = 3, h = 3,
    oddTID = 15, evenTID = 13, oddTIDDex = 13, evenTIDDex = 10,
    occ = nil,
    sprite = "large_prism_sphere_NCGR", palette = "prism_sphere_NCLR" },
  { name = "MINING_LARGE_PALE_SPHERE", id = 7, w = 3, h = 3,
    oddTID = 13, evenTID = 15, oddTIDDex = 10, evenTIDDex = 13,
    occ = nil,
    sprite = "large_pale_sphere_NCGR", palette = "pale_sphere_NCLR" },
  { name = "MINING_LARGE_RED_SPHERE", id = 8, w = 3, h = 3,
    oddTID = 83, evenTID = 96, oddTIDDex = 61, evenTIDDex = 75,
    occ = nil,
    sprite = "large_red_sphere_NCGR", palette = "red_sphere_NCLR" },
  { name = "MINING_LARGE_BLUE_SPHERE", id = 9, w = 3, h = 3,
    oddTID = 96, evenTID = 83, oddTIDDex = 75, evenTIDDex = 61,
    occ = nil,
    sprite = "large_blue_sphere_NCGR", palette = "blue_sphere_NCLR" },
  { name = "MINING_LARGE_GREEN_SPHERE", id = 10, w = 3, h = 3,
    oddTID = 75, evenTID = 75, oddTIDDex = 53, evenTIDDex = 53,
    occ = nil,
    sprite = "large_green_sphere_NCGR", palette = "green_sphere_NCLR" },
  { name = "MINING_TREASURE_OVAL_STONE", id = 11, w = 3, h = 3,
    oddTID = 0, evenTID = 0, oddTIDDex = 0, evenTIDDex = 0,
    occ = nil,
    sprite = "oval_stone_NCGR", palette = "oval_stone_NCLR" },
  { name = "MINING_TREASURE_ODD_KEYSTONE", id = 12, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 2, evenTIDDex = 2,
    occ = nil,
    sprite = "odd_keystone_NCGR", palette = "odd_keystone_NCLR" },
  { name = "MINING_TREASURE_SUN_STONE", id = 13, w = 3, h = 3,
    oddTID = 4, evenTID = 1, oddTIDDex = 15, evenTIDDex = 3,
    occ = { "010", "111", "111" },
    sprite = "sun_stone_NCGR", palette = "sun_stone_NCLR" },
  { name = "MINING_TREASURE_STAR_PIECE", id = 14, w = 3, h = 3,
    oddTID = 2, evenTID = 2, oddTIDDex = 10, evenTIDDex = 10,
    occ = { "010", "111", "010" },
    sprite = "star_piece_NCGR", palette = "star_piece_NCLR" },
  { name = "MINING_TREASURE_MOON_STONE", id = 15, w = 4, h = 2,
    oddTID = 1, evenTID = 2, oddTIDDex = 1, evenTIDDex = 8,
    occ = { "0111", "1110" },
    sprite = "moon_stone_NCGR", palette = "moon_stone_NCLR" },
  { name = "MINING_TREASURE_MOON_STONE", id = 15, w = 2, h = 4,
    oddTID = 1, evenTID = 2, oddTIDDex = 2, evenTIDDex = 7,
    occ = { "10", "11", "11", "01" },
    sprite = "moon_stone_90deg_NCGR", palette = "moon_stone_NCLR" },
  { name = "MINING_TREASURE_HARD_STONE", id = 16, w = 2, h = 2,
    oddTID = 4, evenTID = 4, oddTIDDex = 20, evenTIDDex = 20,
    occ = nil,
    sprite = "hard_stone_NCGR", palette = "hard_stone_NCLR" },
  { name = "MINING_TREASURE_THUNDERSTONE", id = 17, w = 3, h = 3,
    oddTID = 4, evenTID = 1, oddTIDDex = 30, evenTIDDex = 5,
    occ = { "011", "111", "110" },
    sprite = "thunderstone_NCGR", palette = "thunderstone_NCLR" },
  { name = "MINING_TREASURE_EVERSTONE", id = 18, w = 4, h = 2,
    oddTID = 4, evenTID = 4, oddTIDDex = 20, evenTIDDex = 20,
    occ = nil,
    sprite = "everstone_NCGR", palette = "everstone_NCLR" },
  { name = "MINING_TREASURE_FIRE_STONE", id = 19, w = 3, h = 3,
    oddTID = 4, evenTID = 1, oddTIDDex = 30, evenTIDDex = 5,
    occ = nil,
    sprite = "fire_stone_NCGR", palette = "fire_stone_NCLR" },
  { name = "MINING_TREASURE_WATER_STONE", id = 20, w = 3, h = 3,
    oddTID = 1, evenTID = 4, oddTIDDex = 5, evenTIDDex = 30,
    occ = { "111", "111", "110" },
    sprite = "water_stone_NCGR", palette = "water_stone_NCLR" },
  { name = "MINING_TREASURE_LEAF_STONE", id = 21, w = 3, h = 4,
    oddTID = 1, evenTID = 2, oddTIDDex = 3, evenTIDDex = 15,
    occ = { "010", "111", "111", "010" },
    sprite = "leaf_stone_NCGR", palette = "leaf_stone_NCLR" },
  { name = "MINING_TREASURE_LEAF_STONE", id = 21, w = 4, h = 3,
    oddTID = 1, evenTID = 2, oddTIDDex = 2, evenTIDDex = 15,
    occ = { "0110", "1111", "0110" },
    sprite = "leaf_stone_90deg_NCGR", palette = "leaf_stone_NCLR" },
  { name = "MINING_TREASURE_HELIX_FOSSIL", id = 23, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "0111", "1111", "1111", "1110" },
    sprite = "helix_fossil_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_HELIX_FOSSIL", id = 23, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "1110", "1111", "1111", "0111" },
    sprite = "helix_fossil_90deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_HELIX_FOSSIL", id = 23, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "0111", "1111", "1111", "1110" },
    sprite = "helix_fossil_180deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_HELIX_FOSSIL", id = 23, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "1110", "1111", "1111", "0111" },
    sprite = "helix_fossil_270deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_DOME_FOSSIL", id = 24, w = 5, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 1, evenTIDDex = 13,
    occ = { "11111", "11111", "11111", "01110" },
    sprite = "dome_fossil_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_CLAW_FOSSIL", id = 25, w = 4, h = 5,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "0011", "0111", "0111", "1110", "1100" },
    sprite = "claw_fossil_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_CLAW_FOSSIL", id = 25, w = 5, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "11000", "11110", "01111", "00111" },
    sprite = "claw_fossil_90deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_CLAW_FOSSIL", id = 25, w = 4, h = 5,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "0011", "0111", "1110", "1110", "1100" },
    sprite = "claw_fossil_180deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_CLAW_FOSSIL", id = 25, w = 5, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 1,
    occ = { "11100", "11110", "01111", "00011" },
    sprite = "claw_fossil_270deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_ROOT_FOSSIL", id = 26, w = 5, h = 5,
    oddTID = 0, evenTID = 0, oddTIDDex = 1, evenTIDDex = 3,
    occ = { "11110", "11111", "11011", "00011", "00110" },
    sprite = "root_fossil_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_ROOT_FOSSIL", id = 26, w = 5, h = 5,
    oddTID = 0, evenTID = 0, oddTIDDex = 1, evenTIDDex = 3,
    occ = { "00111", "00111", "10011", "11111", "01110" },
    sprite = "root_fossil_90deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_ROOT_FOSSIL", id = 26, w = 5, h = 5,
    oddTID = 0, evenTID = 0, oddTIDDex = 1, evenTIDDex = 3,
    occ = { "01100", "11000", "11011", "11111", "01111" },
    sprite = "root_fossil_180deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_ROOT_FOSSIL", id = 26, w = 5, h = 5,
    oddTID = 0, evenTID = 0, oddTIDDex = 1, evenTIDDex = 3,
    occ = { "01110", "11111", "11001", "11100", "11100" },
    sprite = "root_fossil_270deg_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_OLD_AMBER", id = 27, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 2, evenTIDDex = 2,
    occ = { "0111", "1111", "1111", "1110" },
    sprite = "old_amber_NCGR", palette = "old_amber_NCLR" },
  { name = "MINING_TREASURE_OLD_AMBER", id = 27, w = 4, h = 4,
    oddTID = 0, evenTID = 0, oddTIDDex = 3, evenTIDDex = 3,
    occ = { "1110", "1111", "1111", "0111" },
    sprite = "old_amber_90deg_NCGR", palette = "old_amber_NCLR" },
  { name = "MINING_TREASURE_RARE_BONE", id = 28, w = 3, h = 6,
    oddTID = 1, evenTID = 1, oddTIDDex = 5, evenTIDDex = 5,
    occ = { "111", "010", "010", "010", "010", "111" },
    sprite = "rare_bone_NCGR", palette = "rare_bone_NCLR" },
  { name = "MINING_TREASURE_RARE_BONE", id = 28, w = 6, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 5, evenTIDDex = 5,
    occ = { "100001", "111111", "100001" },
    sprite = "rare_bone_90deg_NCGR", palette = "rare_bone_NCLR" },
  { name = "MINING_TREASURE_REVIVE", id = 29, w = 3, h = 3,
    oddTID = 8, evenTID = 8, oddTIDDex = 10, evenTIDDex = 10,
    occ = { "010", "111", "010" },
    sprite = "revive_NCGR", palette = "revive_NCLR" },
  { name = "MINING_TREASURE_MAX_REVIVE", id = 30, w = 3, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 2, evenTIDDex = 2,
    occ = nil,
    sprite = "max_revive_NCGR", palette = "revive_NCLR" },
  { name = "MINING_TREASURE_RED_SHARD", id = 31, w = 3, h = 3,
    oddTID = 13, evenTID = 13, oddTIDDex = 17, evenTIDDex = 17,
    occ = { "111", "110", "111" },
    sprite = "red_shard_NCGR", palette = "flame_plate_NCLR" },
  { name = "MINING_TREASURE_BLUE_SHARD", id = 32, w = 3, h = 3,
    oddTID = 13, evenTID = 13, oddTIDDex = 17, evenTIDDex = 17,
    occ = { "111", "111", "110" },
    sprite = "blue_shard_NCGR", palette = "splash_plate_NCLR" },
  { name = "MINING_TREASURE_YELLOW_SHARD", id = 33, w = 4, h = 3,
    oddTID = 13, evenTID = 13, oddTIDDex = 17, evenTIDDex = 17,
    occ = { "1010", "1110", "1111" },
    sprite = "yellow_shard_NCGR", palette = "zap_plate_NCLR" },
  { name = "MINING_TREASURE_GREEN_SHARD", id = 34, w = 4, h = 3,
    oddTID = 13, evenTID = 13, oddTIDDex = 17, evenTIDDex = 17,
    occ = { "1111", "1111", "1101" },
    sprite = "green_shard_NCGR", palette = "meadow_plate_NCLR" },
  { name = "MINING_TREASURE_HEART_SCALE", id = 35, w = 2, h = 2,
    oddTID = 33, evenTID = 33, oddTIDDex = 30, evenTIDDex = 30,
    occ = { "10", "11" },
    sprite = "heart_scale_NCGR", palette = "heart_scale_NCLR" },
  { name = "MINING_TREASURE_ARMOR_FOSSIL", id = 36, w = 5, h = 4,
    oddTID = 0, evenTID = 25, oddTIDDex = 0, evenTIDDex = 12,
    occ = { "01110", "01110", "11111", "01110" },
    sprite = "armor_fossil_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_SKULL_FOSSIL", id = 37, w = 4, h = 4,
    oddTID = 25, evenTID = 0, oddTIDDex = 12, evenTIDDex = 0,
    occ = { "1111", "1111", "1111", "0110" },
    sprite = "skull_fossil_NCGR", palette = "fossil_NCLR" },
  { name = "MINING_TREASURE_LIGHT_CLAY", id = 38, w = 4, h = 4,
    oddTID = 1, evenTID = 1, oddTIDDex = 5, evenTIDDex = 2,
    occ = { "1010", "1111", "1111", "0101" },
    sprite = "light_clay_NCGR", palette = "light_clay_NCLR" },
  { name = "MINING_TREASURE_IRON_BALL", id = 39, w = 3, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 2, evenTIDDex = 5,
    occ = nil,
    sprite = "iron_ball_NCGR", palette = "iron_ball_NCLR" },
  { name = "MINING_TREASURE_ICY_ROCK", id = 40, w = 4, h = 4,
    oddTID = 2, evenTID = 1, oddTIDDex = 11, evenTIDDex = 5,
    occ = { "0110", "1111", "1111", "1001" },
    sprite = "icy_rock_NCGR", palette = "icy_rock_NCLR" },
  { name = "MINING_TREASURE_SMOOTH_ROCK", id = 41, w = 4, h = 4,
    oddTID = 1, evenTID = 2, oddTIDDex = 5, evenTIDDex = 11,
    occ = { "0010", "1110", "0111", "0100" },
    sprite = "smooth_rock_NCGR", palette = "smooth_rock_NCLR" },
  { name = "MINING_TREASURE_HEAT_ROCK", id = 42, w = 4, h = 3,
    oddTID = 2, evenTID = 1, oddTIDDex = 11, evenTIDDex = 5,
    occ = { "1010", "1111", "1111" },
    sprite = "heat_rock_NCGR", palette = "heat_rock_NCLR" },
  { name = "MINING_TREASURE_DAMP_ROCK", id = 43, w = 3, h = 3,
    oddTID = 1, evenTID = 2, oddTIDDex = 5, evenTIDDex = 11,
    occ = { "111", "111", "111" },
    sprite = "damp_rock_NCGR", palette = "damp_rock_NCLR" },
  { name = "MINING_TREASURE_FLAME_PLATE", id = 44, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "flame_plate_NCLR" },
  { name = "MINING_TREASURE_SPLASH_PLATE", id = 45, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "splash_plate_NCLR" },
  { name = "MINING_TREASURE_ZAP_PLATE", id = 46, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "zap_plate_NCLR" },
  { name = "MINING_TREASURE_MEADOW_PLATE", id = 47, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "meadow_plate_NCLR" },
  { name = "MINING_TREASURE_ICICLE_PLATE", id = 48, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "icicle_plate_NCLR" },
  { name = "MINING_TREASURE_FIST_PLATE", id = 49, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "fist_plate_NCLR" },
  { name = "MINING_TREASURE_TOXIC_PLATE", id = 50, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "toxic_plate_NCLR" },
  { name = "MINING_TREASURE_EARTH_PLATE", id = 51, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "earth_plate_NCLR" },
  { name = "MINING_TREASURE_SKY_PLATE", id = 52, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "sky_plate_NCLR" },
  { name = "MINING_TREASURE_MIND_PLATE", id = 53, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "mind_plate_NCLR" },
  { name = "MINING_TREASURE_INSECT_PLATE", id = 54, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "insect_plate_NCLR" },
  { name = "MINING_TREASURE_STONE_PLATE", id = 55, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "stone_plate_NCLR" },
  { name = "MINING_TREASURE_SPOOKY_PLATE", id = 56, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "spooky_plate_NCLR" },
  { name = "MINING_TREASURE_DRACO_PLATE", id = 57, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "draco_plate_NCLR" },
  { name = "MINING_TREASURE_DREAD_PLATE", id = 58, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "dread_plate_NCLR" },
  { name = "MINING_TREASURE_IRON_PLATE", id = 59, w = 4, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "plate_NCGR", palette = "iron_plate_NCLR" },
  { name = "MINING_ROCK_1", id = 60, w = 4, h = 1,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "rock_horizontal_line_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_1", id = 60, w = 1, h = 4,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "rock_vertical_line_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_2", id = 61, w = 2, h = 2,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "rock_square_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_3", id = 62, w = 3, h = 2,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "111", "010" },
    sprite = "rock_T_shape_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_3", id = 62, w = 2, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "01", "11", "01" },
    sprite = "rock_T_shape_90deg_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_3", id = 62, w = 3, h = 2,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "010", "111" },
    sprite = "rock_T_shape_180deg_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_3", id = 62, w = 2, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "10", "11", "10" },
    sprite = "rock_T_shape_270deg_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_4", id = 63, w = 3, h = 2,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "110", "011" },
    sprite = "rock_z_shape_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_4", id = 63, w = 2, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "01", "11", "10" },
    sprite = "rock_z_shape_90deg_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_5", id = 64, w = 3, h = 2,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "011", "110" },
    sprite = "rock_s_shape_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_5", id = 64, w = 2, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = { "10", "11", "01" },
    sprite = "rock_s_shape_90deg_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_6", id = 65, w = 3, h = 3,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "rock_large_square_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_7", id = 66, w = 2, h = 4,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "rock_vertical_rectangle_NCGR", palette = "rock_NCLR" },
  { name = "MINING_ROCK_7", id = 66, w = 4, h = 2,
    oddTID = 1, evenTID = 1, oddTIDDex = 1, evenTIDDex = 1,
    occ = nil,
    sprite = "rock_horizontal_rectangle_NCGR", palette = "rock_NCLR" },
}

-- sMiningItems (underground.c), indexed by treasure id minus TREASURE_START.
-- Forty-nine entries, MINING_TREASURE_OVAL_STONE .. MINING_TREASURE_IRON_PLATE.
-- Index 11 is ITEM_NUGGET, whose row is MINING_TREASURE_NUGGET_UNUSED and has
-- no entry in sMiningObjects at all -- the map is wider than the table.
Gen4Mining.TREASURE_ITEMS = {
  [0] = "ITEM_OVAL_STONE",
  [1] = "ITEM_ODD_KEYSTONE",
  [2] = "ITEM_SUN_STONE",
  [3] = "ITEM_STAR_PIECE",
  [4] = "ITEM_MOON_STONE",
  [5] = "ITEM_HARD_STONE",
  [6] = "ITEM_THUNDERSTONE",
  [7] = "ITEM_EVERSTONE",
  [8] = "ITEM_FIRE_STONE",
  [9] = "ITEM_WATER_STONE",
  [10] = "ITEM_LEAF_STONE",
  [11] = "ITEM_NUGGET",
  [12] = "ITEM_HELIX_FOSSIL",
  [13] = "ITEM_DOME_FOSSIL",
  [14] = "ITEM_CLAW_FOSSIL",
  [15] = "ITEM_ROOT_FOSSIL",
  [16] = "ITEM_OLD_AMBER",
  [17] = "ITEM_RARE_BONE",
  [18] = "ITEM_REVIVE",
  [19] = "ITEM_MAX_REVIVE",
  [20] = "ITEM_RED_SHARD",
  [21] = "ITEM_BLUE_SHARD",
  [22] = "ITEM_YELLOW_SHARD",
  [23] = "ITEM_GREEN_SHARD",
  [24] = "ITEM_HEART_SCALE",
  [25] = "ITEM_ARMOR_FOSSIL",
  [26] = "ITEM_SKULL_FOSSIL",
  [27] = "ITEM_LIGHT_CLAY",
  [28] = "ITEM_IRON_BALL",
  [29] = "ITEM_ICY_ROCK",
  [30] = "ITEM_SMOOTH_ROCK",
  [31] = "ITEM_HEAT_ROCK",
  [32] = "ITEM_DAMP_ROCK",
  [33] = "ITEM_FLAME_PLATE",
  [34] = "ITEM_SPLASH_PLATE",
  [35] = "ITEM_ZAP_PLATE",
  [36] = "ITEM_MEADOW_PLATE",
  [37] = "ITEM_ICICLE_PLATE",
  [38] = "ITEM_FIST_PLATE",
  [39] = "ITEM_TOXIC_PLATE",
  [40] = "ITEM_EARTH_PLATE",
  [41] = "ITEM_SKY_PLATE",
  [42] = "ITEM_MIND_PLATE",
  [43] = "ITEM_INSECT_PLATE",
  [44] = "ITEM_STONE_PLATE",
  [45] = "ITEM_SPOOKY_PLATE",
  [46] = "ITEM_DRACO_PLATE",
  [47] = "ITEM_DREAD_PLATE",
  [48] = "ITEM_IRON_PLATE",
}

-- Is this cell of an object solid?  `Mining_AreCoordinatesWithinObjectShape`,
-- with the flat read already baked into `occ` above, so this is a lookup.
-- x and y are 0-based CELL offsets within the object.
function Gen4Mining.solidAt(obj, x, y)
  if not obj then return false end
  if x < 0 or y < 0 or x >= obj.w or y >= obj.h then return false end
  if obj.occ == nil then return true end
  local row = obj.occ[y + 1]
  if not row then return true end
  return row:sub(x + 1, x + 1) ~= "0"
end

-- The weight this row carries for a given save, and the two questions that
-- decide it.  `oddTID` is `TrainerInfo_ID(...) % 2`, so it is the LOW BIT of the
-- trainer id and not a comparison against anything.
function Gen4Mining.weightOf(obj, oddTID, nationalDex)
  if not obj then return 0 end
  if nationalDex then
    return oddTID and obj.oddTIDDex or obj.evenTIDDex
  end
  return oddTID and obj.oddTID or obj.evenTID
end

-- The rows `Mining_PickItem` walks: everything before the first rock row.
function Gen4Mining.weightedPool()
  if Gen4Mining._pool then return Gen4Mining._pool end
  local out = {}
  for _, obj in ipairs(Gen4Mining.OBJECTS) do
    -- The cartridge BREAKS here rather than skipping, so this must stop at the
    -- first rock row and not filter the whole table -- they are the same thing
    -- only because every rock row is at the end, which the check asserts.
    if obj.id >= Gen4Mining.ROCK_FIRST then break end
    out[#out + 1] = obj
  end
  Gen4Mining._pool = out
  return out
end

-- The rock rows, which are placed separately and are never picked by weight.
function Gen4Mining.rocks()
  if Gen4Mining._rocks then return Gen4Mining._rocks end
  local out = {}
  for _, obj in ipairs(Gen4Mining.OBJECTS) do
    if obj.id >= Gen4Mining.ROCK_FIRST then out[#out + 1] = obj end
  end
  Gen4Mining._rocks = out
  return out
end

function Gen4Mining.totalWeight(oddTID, nationalDex)
  local total = 0
  for _, obj in ipairs(Gen4Mining.weightedPool()) do
    total = total + Gen4Mining.weightOf(obj, oddTID, nationalDex)
  end
  return total
end

-- `Mining_PickItem`: subtract each row's weight from the roll until it goes
-- negative.  `roll` is 0 .. totalWeight-1, which is what MATH_Rand32(rand, n)
-- gives.  Returns the row and its index.
function Gen4Mining.pick(roll, oddTID, nationalDex)
  local pool = Gen4Mining.weightedPool()
  local counter = roll
  for i, obj in ipairs(pool) do
    counter = counter - Gen4Mining.weightOf(obj, oddTID, nationalDex)
    if counter < 0 then return obj, i end
  end
  -- The cartridge's GF_ASSERT(FALSE) and `return 0`.  Reached only if `roll`
  -- was not drawn against this exact total -- a zero-weight row cannot be
  -- picked, and with every weight zero there is nothing to pick at all.
  return nil, nil
end

-- A treasure row's bag item, or nil for a sphere or a rock.
function Gen4Mining.bagItem(obj)
  if not obj then return nil end
  if obj.id < Gen4Mining.TREASURE_START then return nil end   -- a sphere
  if obj.id >= Gen4Mining.ROCK_FIRST then return nil end      -- a rock
  return Gen4Mining.TREASURE_ITEMS[obj.id - Gen4Mining.TREASURE_START]
end

return Gen4Mining
