-- Copyright (c) 2026 Cedric. All rights reserved.
-- Source-available under the Gen2Recomped License (see LICENSE.md): you may
-- read, build and privately modify this file; you may not redistribute it or
-- use it commercially. Cartridge-derived data is excluded and is not the
-- copyright holder's to license.

-- WHAT EMERALD'S OWN ANIMATION SCRIPT SAYS EACH MOVE DOES.
--
-- Reported from play: "go through all of the pokemon emerald moves and ensure
-- theyre rendering properly a lot of them seem messed up still they should
-- render the moves like they are in the rom".  This table is what makes that
-- statement measurable instead of a matter of opinion.
--
-- GENERATED, not written: transcribed from pret/pokeemerald's
-- `data/battle_anim_scripts.s`.  pokeemerald builds byte-for-byte to the
-- retail ROM, so these ARE the cartridge's own scripts -- read from a source
-- that NAMES the functions the ROM only carries as addresses.
--
-- WHY IT IS NEEDED AT ALL, given that the import reads the real ROM.
-- `src/import/RomExtractorGen3.lua` does the harder and more correct thing: it
-- recognises a visual task by its ADDRESS and then verifies, by disassembling
-- the function, that it really is the one being claimed -- which is why the
-- shakes and blends it does extract can be trusted.  What that approach cannot
-- do is tell you what it has NOT learned: a `createvisualtask` whose pointer is
-- in no table is silently nothing at all, the move comes out quiet, and no
-- record is left that anything was dropped.  This table is the other half of
-- the measurement -- the list of everything the cartridge asks for -- and
-- `tools/gen3_move_anim_audit.lua` subtracts one from the other.
--
-- IT IS A CENSUS, NOT A RENDERER'S INPUT.  Nothing draws from this file.
--
-- EACH ROW, all of it from the script and none of it inferred:
--   sprites  particle-spawning commands, counting the `create_*_sprite`
--            wrappers, which are `createsprite` with arguments pre-filled.
--   bg       background swaps (`fadetobg`, `restorebg`, `loadbg`).
--   monbg    `monbg` calls, which lift the Pokemon onto a layer of its own so
--            a blend can hit the mon without hitting the field behind it.
--   tasks    every `createvisualtask`, IN ORDER, as { name, arg... }, with the
--            AnimTask_/SoundTask_ prefix and the priority argument dropped.
--            ORDER IS LOAD-BEARING: the ROM carries the same list as addresses
--            in the same order, so position is what lets one be matched to the
--            other without a symbol table.  A task reached through a wrapper
--            macro (`blend_color_cycle`, `invert_screen_color`) carries the
--            MACRO's arguments, which are not the task's -- the name is the
--            part to trust there.
--
-- A BRANCHING SCRIPT IS FLATTENED AS THE UNION OF ITS ARMS.  FLY, DIG, DIVE,
-- SOLARBEAM and the other two-turn moves pick an arm with `choosetwoturnanim`,
-- and a move that shakes the target only on its second turn still shakes it.
-- The question here is "does the cartridge ever do this for this move", so
-- both arms count.  That makes every row an UPPER BOUND on any single
-- playthrough of one move, and it must not be read as a per-turn script.
--
-- Keys are the dataset's own move keys, so a row can be looked up directly
-- against `moves.lua`; the cartridge's ANCIENT_POWER is the dataset's
-- ANCIENTPOWER and seventeen others differ the same way.

local Gen3AnimExpect = {}

Gen3AnimExpect.MOVES = {
  ["ABSORB"] = { sprites = 15, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "5", "1" },
    },
  },
  ["ACID"] = { sprites = 8, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "10", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "2", "0", "10", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_DEF_SIDE", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(30", "0", "31)" },
    },
  },
  ["ACID_ARMOR"] = { sprites = 0, monbg = 1,
    tasks = {
      { "AcidArmor", "ANIM_ATTACKER" },
    },
  },
  ["AERIAL_ACE"] = { sprites = 2, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "24", "6", "1", "5" },
      { "TraceMonBlended", "0", "4", "7", "3" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
    },
  },
  ["AEROBLAST"] = { sprites = 41, bg = 3, monbg = 1,
    tasks = {
      { "StartSlidingBg", "2304", "768", "0", "-1" },
      { "StartSlidingBg", "-2304", "768", "1", "-1" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "50", "1" },
    },
  },
  ["AGILITY"] = { sprites = 0, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "24", "6", "4", "4" },
      { "TraceMonBlended", "0", "4", "7", "10" },
    },
  },
  ["AIR_CUTTER"] = { sprites = 1, monbg = 1,
    tasks = {
      { "AirCutterProjectile", "32", "-24", "6 * 256", "2", "128" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "2", "0", "8", "1" },
    },
  },
  ["AMNESIA"] = { sprites = 1, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
    },
  },
  ["ANCIENTPOWER"] = { sprites = 14, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "30", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["ARM_THRUST"] = { sprites = 4,
    tasks = {
      { "RotateMonSpriteToSide", "8", "5", "ANIM_ATTACKER", "0" },
      { "RotateMonSpriteToSide", "8", "5", "ANIM_ATTACKER", "1" },
      { "ShakeMon", "ANIM_TARGET", "4", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "4", "0", "6", "1" },
    },
  },
  ["AROMATHERAPY"] = { sprites = 15, monbg = 1,
    tasks = {
      { "StatusClearedEffect", "1" },
    },
  },
  ["ASSIST"] = { sprites = 5,
  },
  ["ASTONISH"] = { sprites = 3,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "5", "1" },
      { "StretchTargetUp" },
    },
  },
  ["ATTRACT"] = { sprites = 15,
    tasks = {
      { "SwayMon", "0", "12", "4096", "4", "ANIM_ATTACKER" },
      { "HeartsBackground" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=4", "num_blends=4", "initial_blend_y=0", "target_blend_y=10", "color=RGB(31", "25", "27)" },
    },
  },
  ["AURORA_BEAM"] = { sprites = 40, bg = 2,
    tasks = {
      { "RotateAuroraRingColors", "130" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "17", "1" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "40", "1" },
    },
  },
  ["BARRAGE"] = { sprites = 1,
    tasks = {
      { "BarrageBall" },
      { "ShakeMon", "ANIM_TARGET", "0", "4", "20", "1" },
      { "ShakeMon", "ANIM_DEF_PARTNER", "0", "4", "20", "1" },
    },
  },
  ["BARRIER"] = { sprites = 1,
  },
  ["BATON_PASS"] = { sprites = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_BATTLERS", "delay=1", "num_blends=2", "initial_blend_y=0", "target_blend_y=11", "color=RGB(31", "22", "30)" },
    },
  },
  ["BEAT_UP"] = { sprites = 8, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["BELLY_DRUM"] = { sprites = 12,
    tasks = {
      { "MusicNotesRainbowBlend" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "8", "2", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "8", "2", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "8", "2", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "8", "2", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "8", "2", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "8", "2", "1" },
      { "MusicNotesClearRainbowBlend" },
    },
  },
  ["BIDE"] = { sprites = 5, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=11", "color=RGB_RED" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "32", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "2", "0", "11", "RGB_RED" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "32", "1" },
      { "ShakeMonInPlace", "ANIM_ATTACKER", "2", "0", "12", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "16", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "2", "11", "0", "RGB_RED" },
    },
  },
  ["BIND"] = { sprites = 0,
    tasks = {
      { "SwayMon", "0", "6", "3328", "4", "ANIM_ATTACKER" },
      { "ScaleMonAndRestore", "10", "-5", "5", "ANIM_TARGET", "0" },
      { "ScaleMonAndRestore", "10", "-5", "5", "ANIM_TARGET", "0" },
    },
  },
  ["BITE"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "4", "7", "1" },
    },
  },
  ["BLAST_BURN"] = { sprites = 25, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "ShakeMon", "ANIM_TARGET", "12", "0", "20", "1" },
      { "ShakeBattlePlatforms", "x_offset=2", "y_offset=0", "shakes=10", "delay=1" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
    },
  },
  ["BLAZE_KICK"] = { sprites = 10, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "7", "RGB_WHITE" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "14", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "0", "RGB_WHITE" },
    },
  },
  ["BLIZZARD"] = { sprites = 39, bg = 3, monbg = 1,
    tasks = {
      { "GetAttackerSide" },
      { "StartSlidingBg", "-2304", "0", "1", "-1" },
    },
  },
  ["BLOCK"] = { sprites = 1,
  },
  ["BODY_SLAM"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMonInPlace", "ANIM_TARGET", "4", "0", "12", "1" },
    },
  },
  ["BONEMERANG"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "5", "0", "5", "1" },
    },
  },
  ["BONE_CLUB"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "5", "1" },
    },
  },
  ["BONE_RUSH"] = { sprites = 2, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
    },
  },
  ["BOUNCE"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "11", "1" },
    },
  },
  ["BRICK_BREAK"] = { sprites = 21, monbg = 2,
    tasks = {
      { "WindUpLunge", "ANIM_ATTACKER", "-24", "0", "24", "10", "24", "3" },
      { "WindUpLunge", "ANIM_ATTACKER", "-24", "0", "24", "10", "24", "3" },
    },
  },
  ["BUBBLE"] = { sprites = 14, monbg = 1,
  },
  ["BUBBLEBEAM"] = { sprites = 24, monbg = 1,
    tasks = {
      { "SwayMon", "0", "3", "3072", "8", "ANIM_TARGET" },
    },
  },
  ["BULK_UP"] = { sprites = 1,
    tasks = {
      { "GrowAndShrink" },
    },
  },
  ["BULLET_SEED"] = { sprites = 10,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "30", "1" },
    },
  },
  ["CALM_MIND"] = { sprites = 3, monbg = 1,
    tasks = {
      { "BlendBattleAnimPalExclude", "ANIM_ATTACKER", "0", "0", "16", "RGB_BLACK" },
      { "SetAllNonAttackersInvisiblity", "TRUE" },
      { "SetAllNonAttackersInvisiblity", "FALSE" },
      { "BlendBattleAnimPalExclude", "ANIM_ATTACKER", "0", "16", "0", "RGB_BLACK" },
    },
  },
  ["CAMOUFLAGE"] = { sprites = 0, monbg = 1,
    tasks = {
      { "SetCamouflageBlend", "F_PAL_ATTACKER", "3", "0", "14" },
      { "AttackerFadeToInvisible", "step_delay=4" },
      { "SetCamouflageBlend", "F_PAL_ATTACKER", "0", "0", "0" },
      { "AttackerFadeFromInvisible", "step_delay=1" },
    },
  },
  ["CHARGE"] = { sprites = 5, monbg = 1,
    tasks = {
      { "ElectricChargingParticles", "ANIM_ATTACKER", "60", "2", "12" },
    },
  },
  ["CHARM"] = { sprites = 3,
    tasks = {
      { "RockMonBackAndForth", "ANIM_ATTACKER", "2", "0" },
    },
  },
  ["CLAMP"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "5", "1" },
    },
  },
  ["COMET_PUNCH"] = { sprites = 4, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["CONFUSE_RAY"] = { sprites = 2, bg = 2, monbg = 1,
    tasks = {
      { "AdjustPanningVar", "SOUND_PAN_ATTACKER", "SOUND_PAN_TARGET", "2", "0" },
      { "BlendColorCycleByTag", "tag=ANIM_TAG_YELLOW_BALL", "delay=0", "num_blends=6", "initial_blend_y=0", "target_blend_y=14", "color=RGB(31", "10", "0)" },
    },
  },
  ["CONFUSION"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "SetPsychicBackground" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "10", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=8", "color=RGB_WHITE" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "15", "1" },
      { "ScaleMonAndRestore", "-4", "-4", "15", "ANIM_TARGET", "1" },
    },
  },
  ["CONSTRICT"] = { sprites = 4,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["CONVERSION"] = { sprites = 16, monbg = 1,
    tasks = {
      { "FlashAnimTagWithColor", "tag=ANIM_TAG_CONVERSION", "delay=1", "num_blends=1", "color1=RGB(31", "31", "13)", "blend_y1=12", "color2=RGB_BLACK", "blend_y2=0" },
      { "ConversionAlphaBlend" },
    },
  },
  ["CONVERSION_2"] = { sprites = 16, monbg = 1,
    tasks = {
      { "Conversion2AlphaBlend" },
    },
  },
  ["COSMIC_POWER"] = { sprites = 2, bg = 2,
    tasks = {
      { "PlaySE2WithPanning", "SE_M_COSMIC_POWER", "0" },
      { "BlendNonAttackerPalettes", "0", "0", "15", "RGB_BLACK" },
      { "StartSlidingBg", "0", "128", "0", "-1" },
      { "PlaySE1WithPanning", "SE_M_MORNING_SUN", "SOUND_PAN_ATTACKER" },
      { "BlendNonAttackerPalettes", "0", "15", "0", "RGB_BLACK" },
    },
  },
  ["COTTON_SPORE"] = { sprites = 9, monbg = 1,
  },
  ["COUNTER"] = { sprites = 8, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "18", "6", "1", "4" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "25", "1" },
    },
  },
  ["COVET"] = { sprites = 3,
    tasks = {
      { "RockMonBackAndForth", "ANIM_ATTACKER", "2", "0" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
    },
  },
  ["CRABHAMMER"] = { sprites = 12, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "4", "8", "1" },
    },
  },
  ["CROSS_CHOP"] = { sprites = 4, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "7", "0", "9", "1" },
    },
  },
  ["CRUNCH"] = { sprites = 6, bg = 2, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "7", "5", "2" },
      { "ShakeMon", "ANIM_TARGET", "0", "8", "4", "2" },
    },
  },
  ["CRUSH_CLAW"] = { sprites = 5, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "18", "1" },
    },
  },
  ["CURSE"] = { sprites = 3, monbg = 2,
    tasks = {
      { "CurseStretchingBlackBg" },
      { "ShakeMon2", "ANIM_ATTACKER", "4", "0", "10", "0" },
      { "ShakeMon2", "ANIM_ATTACKER", "4", "0", "10", "0" },
      { "ShakeMon2", "ANIM_ATTACKER", "4", "0", "10", "0" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "14", "1" },
      { "SwayMon", "0", "10", "1536", "3", "ANIM_ATTACKER" },
      { "DrawFallingWhiteLinesOnAttacker" },
      { "BlendColorCycle", "priority=5", "selector=F_PAL_ATTACKER", "delay=4", "num_blends=2", "initial_blend_y=0", "target_blend_y=10", "color=RGB_RED" },
    },
  },
  ["CUT"] = { sprites = 1, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
    },
  },
  ["DEFENSE_CURL"] = { sprites = 1,
    tasks = {
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_ATTACKER" },
      { "DefenseCurlDeformMon" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_ATTACKER" },
    },
  },
  ["DESTINY_BOND"] = { sprites = 0, bg = 2,
    tasks = {
      { "DestinyBondWhiteShadow", "0", "48" },
      { "ShakeMonInPlace", "ANIM_ATTACKER", "2", "0", "24", "1" },
      { "BlendBattleAnimPalExclude", "6", "1", "0", "12", "RGB(29", "29", "29)" },
      { "BlendBattleAnimPalExclude", "6", "1", "12", "0", "RGB(29", "29", "29)" },
    },
  },
  ["DETECT"] = { sprites = 3,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "0", "9", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "2", "9", "0", "RGB_WHITE" },
    },
  },
  ["DIG"] = { sprites = 25, monbg = 1,
    tasks = {
      { "DigDownMovement", "FALSE" },
      { "DigDownMovement", "TRUE" },
      { "DigUpMovement", "FALSE" },
      { "DigUpMovement", "TRUE" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["DISABLE"] = { sprites = 1, monbg = 1,
    tasks = {
      { "GrowAndGrayscale" },
    },
  },
  ["DIVE"] = { sprites = 50, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "17", "1" },
    },
  },
  ["DIZZY_PUNCH"] = { sprites = 18, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "7", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "7", "1" },
    },
  },
  ["DOOM_DESIRE"] = { sprites = 2, monbg = 1,
    tasks = {
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_TARGET" },
      { "ScaleMonAndRestore", "-4", "-4", "15", "ANIM_ATTACKER", "1" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_TARGET" },
    },
  },
  ["DOUBLESLAP"] = { sprites = 2, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["DOUBLE_EDGE"] = { sprites = 8,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "18", "6", "2", "4" },
      { "RotateMonSpriteToSide", "8", "-256", "ANIM_ATTACKER", "0" },
      { "RotateMonSpriteToSide", "8", "-256", "ANIM_TARGET", "0" },
      { "ShakeMonInPlace", "ANIM_ATTACKER", "4", "0", "12", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "4", "0", "12", "1" },
      { "RotateMonSpriteToSide", "8", "-256", "ANIM_ATTACKER", "1" },
      { "RotateMonSpriteToSide", "8", "-256", "ANIM_TARGET", "1" },
    },
  },
  ["DOUBLE_KICK"] = { sprites = 1, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "4", "0", "6", "1" },
    },
  },
  ["DOUBLE_TEAM"] = { sprites = 0, monbg = 1,
    tasks = {
      { "DoubleTeam" },
    },
  },
  ["DRAGONBREATH"] = { sprites = 11, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "1", "0", "9", "RGB_RED" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "21", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "1", "9", "0", "RGB_RED" },
    },
  },
  ["DRAGON_CLAW"] = { sprites = 32,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "4", "0", "8", "RGB(31", "19", "0)" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "15", "1" },
      { "PlaySE1WithPanning", "SE_M_RAZOR_WIND", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_RAZOR_WIND", "SOUND_PAN_TARGET" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "4", "8", "0", "RGB(31", "19", "0)" },
    },
  },
  ["DRAGON_DANCE"] = { sprites = 6, monbg = 1,
    tasks = {
      { "DragonDanceWaver" },
      { "BlendPalInAndOutByTag", "ANIM_TAG_HOLLOW_ORB", "RGB(0", "0", "19)", "14", "0", "3" },
    },
  },
  ["DRAGON_RAGE"] = { sprites = 11,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "40", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "25", "1" },
    },
  },
  ["DREAM_EATER"] = { sprites = 28, bg = 2, monbg = 1,
    tasks = {
      { "SetPsychicBackground" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "15", "1" },
      { "ScaleMonAndRestore", "-6", "-6", "15", "ANIM_TARGET", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "2", "25", "1" },
    },
  },
  ["DRILL_PECK"] = { sprites = 4,
    tasks = {
      { "DrillPeckHitSplats" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "18", "1" },
    },
  },
  ["DYNAMICPUNCH"] = { sprites = 7, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "5", "0", "7", "1" },
      { "ShakeMon2", "ANIM_TARGET", "5", "0", "28", "1" },
    },
  },
  ["EARTHQUAKE"] = { sprites = 2,
    tasks = {
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "10", "50" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "10", "50" },
    },
  },
  ["EGG_BOMB"] = { sprites = 6,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "16", "1" },
    },
  },
  ["EMBER"] = { sprites = 6,
  },
  ["ENCORE"] = { sprites = 5,
    tasks = {
      { "CreateSpotlight" },
      { "HardwarePaletteFade", "BLDCNT_TGT1_BG3 | BLDCNT_TGT1_OBJ | BLDCNT_TGT1_BD | BLDCNT_EFFECT_DARKEN", "3", "0", "10", "FALSE" },
      { "PlaySE2WithPanning", "SE_M_ENCORE2", "SOUND_PAN_TARGET" },
      { "SwayMon", "1", "8", "1536", "5", "ANIM_TARGET" },
      { "HardwarePaletteFade", "BLDCNT_TGT1_BG3 | BLDCNT_TGT1_OBJ | BLDCNT_TGT1_BD | BLDCNT_EFFECT_DARKEN", "3", "10", "0", "TRUE" },
      { "RemoveSpotlight" },
    },
  },
  ["ENDEAVOR"] = { sprites = 2,
    tasks = {
      { "SquishAndSweatDroplets", "ANIM_ATTACKER", "2" },
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB(31", "21", "0)", "12", "1", "2" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "8", "1", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "8", "1", "0" },
    },
  },
  ["ENDURE"] = { sprites = 15,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=11", "color=RGB_RED" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "32", "1" },
    },
  },
  ["ERUPTION"] = { sprites = 8,
    tasks = {
      { "EruptionLaunchRocks" },
      { "EruptionLaunchRocks" },
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "8", "60" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "8", "60" },
    },
  },
  ["EXPLOSION"] = { sprites = 11,
    tasks = {
      { "ShakeMon2", "ANIM_PLAYER_LEFT", "8", "0", "40", "1" },
      { "ShakeMon2", "ANIM_PLAYER_RIGHT", "8", "0", "40", "1" },
      { "ShakeMon2", "ANIM_OPPONENT_LEFT", "8", "0", "40", "1" },
      { "ShakeMon2", "ANIM_OPPONENT_RIGHT", "8", "0", "40", "1" },
      { "ShakeMon2", "ANIM_ATTACKER_FORCE", "8", "0", "40", "1" },
      { "BlendBattleAnimPal", "F_PAL_BG", "1", "16", "16", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_BG", "3", "16", "0", "RGB_WHITE" },
    },
  },
  ["EXTRASENSORY"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "SetPsychicBackground" },
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB(27", "27", "0)", "12", "1", "1" },
      { "ExtrasensoryDistortion", "0" },
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB(27", "27", "0)", "12", "1", "1" },
      { "ExtrasensoryDistortion", "1" },
      { "TransparentCloneGrowAndShrink", "ANIM_ATTACKER" },
      { "ExtrasensoryDistortion", "2" },
    },
  },
  ["EXTREMESPEED"] = { sprites = 3, bg = 3, monbg = 1,
    tasks = {
      { "GetAttackerSide" },
      { "StartSlidingBg", "-2304", "0", "1", "-1" },
      { "AttackerStretchAndDisappear" },
      { "SetAttackerInvisibleWaitForSignal" },
      { "ExtremeSpeedImpact" },
      { "SpeedDust" },
      { "ExtremeSpeedMonReappear" },
    },
  },
  ["FACADE"] = { sprites = 0,
    tasks = {
      { "SquishAndSweatDroplets", "ANIM_ATTACKER", "3" },
      { "FacadeColorBlend", "ANIM_ATTACKER", "72" },
    },
  },
  ["FAINT_ATTACK"] = { sprites = 1, bg = 2, monbg = 3,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "18", "6", "1", "3" },
      { "AttackerFadeToInvisible", "step_delay=1" },
      { "SetAttackerInvisibleWaitForSignal" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "9", "1" },
      { "InitAttackerFadeFromInvisible" },
      { "AttackerFadeFromInvisible", "step_delay=1" },
    },
  },
  ["FAKE_OUT"] = { sprites = 1,
    tasks = {
      { "FakeOut" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "5", "1" },
      { "StretchTargetUp" },
    },
  },
  ["FAKE_TEARS"] = { sprites = 8,
    tasks = {
      { "BlendParticle", "ANIM_TAG_SMALL_BUBBLES", "0", "4", "4", "RGB(12", "11", "31)" },
      { "RockMonBackAndForth", "ANIM_ATTACKER", "2", "1" },
    },
  },
  ["FALSE_SWIPE"] = { sprites = 8,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["FEATHERDANCE"] = { sprites = 8, monbg = 1,
  },
  ["FIRE_BLAST"] = { sprites = 60,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG", "3", "0", "8", "RGB_BLACK" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "20", "1" },
      { "BlendBattleAnimPal", "F_PAL_BG", "2", "8", "0", "RGB_BLACK" },
    },
  },
  ["FIRE_PUNCH"] = { sprites = 13, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "9", "RGB_RED" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "15", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "9", "0", "RGB_RED" },
    },
  },
  ["FIRE_SPIN"] = { sprites = 18,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "2", "47", "1" },
    },
  },
  ["FISSURE"] = { sprites = 14, bg = 2,
    tasks = {
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "10", "50" },
      { "HorizontalShake", "ANIM_TARGET", "10", "50" },
      { "PositionFissureBgOnBattler", "ANIM_TARGET", "5", "-1" },
    },
  },
  ["FLAIL"] = { sprites = 1, monbg = 1,
    tasks = {
      { "FlailMovement", "ANIM_ATTACKER" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "30", "1", "0" },
    },
  },
  ["FLAMETHROWER"] = { sprites = 22, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "46", "1" },
      { "StartSinAnimTimer", "100" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "43", "1" },
    },
  },
  ["FLAME_WHEEL"] = { sprites = 16, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "5", "0", "8", "1" },
      { "BlendMonInAndOut", "ANIM_TARGET", "RGB_RED", "12", "1", "1" },
    },
  },
  ["FLASH"] = { sprites = 0,
    tasks = {
      { "Flash" },
    },
  },
  ["FLATTER"] = { sprites = 41,
    tasks = {
      { "PlaySE2WithPanning", "SE_M_ENCORE2", "SOUND_PAN_TARGET" },
      { "CreateSpotlight" },
      { "HardwarePaletteFade", "BLDCNT_TGT1_BG3 | BLDCNT_TGT1_OBJ | BLDCNT_TGT1_BD | BLDCNT_EFFECT_DARKEN", "3", "0", "10", "FALSE" },
      { "PlaySE1WithPanning", "SE_M_FLATTER", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_FLATTER", "SOUND_PAN_TARGET" },
      { "HardwarePaletteFade", "BLDCNT_TGT1_BG3 | BLDCNT_TGT1_OBJ | BLDCNT_TGT1_BD | BLDCNT_EFFECT_DARKEN", "3", "10", "0", "TRUE" },
      { "RemoveSpotlight" },
    },
  },
  ["FLY"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
    },
  },
  ["FOCUS_ENERGY"] = { sprites = 15,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=11", "color=RGB_WHITE" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "32", "1" },
    },
  },
  ["FOCUS_PUNCH"] = { sprites = 15, bg = 6, monbg = 3,
    tasks = {
      { "IsContest" },
      { "ShakeMon", "ANIM_TARGET", "8", "0", "24", "1" },
      { "IsTargetPlayerSide" },
      { "ShakeMon", "ANIM_TARGET", "8", "0", "24", "1" },
      { "ShakeMon", "ANIM_TARGET", "8", "0", "24", "1" },
    },
  },
  ["FOLLOW_ME"] = { sprites = 1,
  },
  ["FORESIGHT"] = { sprites = 1, monbg = 1,
    tasks = {
      { "BlendMonInAndOut", "ANIM_TARGET", "RGB_WHITE", "12", "2", "1" },
    },
  },
  ["FRENZY_PLANT"] = { sprites = 17, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "8", "0", "20", "1" },
    },
  },
  ["FRUSTRATION"] = { sprites = 20, monbg = 1,
    tasks = {
      { "GetFrustrationPowerLevel" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "15", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "3", "0", "9", "RGB_RED" },
      { "SwayMon", "0", "16", "6144", "8", "ANIM_ATTACKER" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "30", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "3", "9", "0", "RGB_RED" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "15", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "3", "0", "9", "RGB_RED" },
      { "StrongFrustrationGrowAndShrink" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "6", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "6", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "6", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "3", "9", "0", "RGB_RED" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "6", "1" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "6", "1" },
    },
  },
  ["FURY_ATTACK"] = { sprites = 4,
    tasks = {
      { "RotateMonSpriteToSide", "4", "256", "ANIM_ATTACKER", "2" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["FURY_CUTTER"] = { sprites = 8, monbg = 1,
    tasks = {
      { "IsFuryCutterHitRight" },
      { "GetFuryCutterHitCount" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "GetFuryCutterHitCount" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "10", "1" },
    },
  },
  ["FURY_SWIPES"] = { sprites = 4,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "5", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "7", "1" },
    },
  },
  ["FUTURE_SIGHT"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "SetPsychicBackground" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=8", "color=RGB_WHITE" },
      { "ScaleMonAndRestore", "-4", "-4", "15", "ANIM_ATTACKER", "1" },
    },
  },
  ["GIGA_DRAIN"] = { sprites = 31, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "5", "1" },
    },
  },
  ["GLARE"] = { sprites = 2,
    tasks = {
      { "GlareEyeDots", "0" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "0", "16", "RGB_BLACK" },
      { "ScaryFace" },
      { "ShakeTargetInPattern", "20", "1", "FALSE" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "16", "0", "RGB_BLACK" },
    },
  },
  ["GRASSWHISTLE"] = { sprites = 14,
    tasks = {
      { "MusicNotesRainbowBlend" },
      { "MusicNotesClearRainbowBlend" },
    },
  },
  ["GROWL"] = { sprites = 6,
    tasks = {
      { "PlayDoubleCry", "ANIM_ATTACKER", "DOUBLE_CRY_GROWL" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "9", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "1", "0", "9", "1" },
      { "WaitForCry" },
    },
  },
  ["GROWTH"] = { sprites = 0,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=8", "color=RGB_WHITE" },
      { "ScaleMonAndRestore", "-3", "-3", "16", "ANIM_ATTACKER", "0" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=8", "color=RGB_WHITE" },
      { "ScaleMonAndRestore", "-3", "-3", "16", "ANIM_ATTACKER", "0" },
    },
  },
  ["GRUDGE"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "GrudgeFlames" },
    },
  },
  ["GUILLOTINE"] = { sprites = 4, bg = 1, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "16", "RGB_BLACK" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "23", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "8", "1" },
    },
  },
  ["GUST"] = { sprites = 2, monbg = 1,
    tasks = {
      { "AnimateGustTornadoPalette", "1", "70" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "7", "1" },
    },
  },
  ["HAIL"] = { sprites = 0,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG", "3", "0", "6", "RGB_BLACK" },
      { "Hail" },
      { "BlendBattleAnimPal", "F_PAL_BG", "3", "6", "0", "RGB_BLACK" },
    },
  },
  ["HARDEN"] = { sprites = 0,
    tasks = {
      { "MetallicShine", "permanent=FALSE" },
    },
  },
  ["HAZE"] = { sprites = 0,
    tasks = {
      { "HazeScrollingFog" },
      { "BlendBattleAnimPal", "F_PAL_BATTLERS_2", "2", "0", "16", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BATTLERS_2", "1", "16", "0", "RGB_BLACK" },
    },
  },
  ["HEADBUTT"] = { sprites = 4,
    tasks = {
      { "ShakeMonInPlace", "ANIM_ATTACKER", "2", "0", "4", "1" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["HEAL_BELL"] = { sprites = 19,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_ATK_SIDE", "0", "0", "10", "RGB_WHITE" },
      { "LoadMusicNotesPals" },
      { "BlendBattleAnimPalExclude", "4", "3", "8", "0", "RGB(12", "24", "30)" },
      { "BlendBattleAnimPal", "F_PAL_ATK_SIDE", "3", "2", "10", "RGB_WHITE" },
      { "BlendBattleAnimPalExclude", "4", "3", "8", "0", "RGB(12", "24", "30)" },
      { "BlendBattleAnimPal", "F_PAL_ATK_SIDE", "3", "2", "10", "RGB_WHITE" },
      { "BlendBattleAnimPalExclude", "4", "3", "8", "0", "RGB(12", "24", "30)" },
      { "BlendBattleAnimPal", "F_PAL_ATK_SIDE", "3", "2", "10", "RGB_WHITE" },
      { "FreeMusicNotesPals" },
      { "BlendBattleAnimPalExclude", "4", "3", "10", "0", "RGB(12", "24", "30)" },
      { "BlendBattleAnimPal", "F_PAL_ATK_SIDE", "3", "10", "0", "RGB_WHITE" },
    },
  },
  ["HEAT_WAVE"] = { sprites = 7,
    tasks = {
      { "BlendParticle", "ANIM_TAG_FLYING_DIRT", "0", "6", "6", "RGB_RED" },
      { "LoadSandstormBackground", "TRUE" },
      { "BlendBackground", "6", "RGB_RED" },
      { "MoveHeatWaveTargets" },
    },
  },
  ["HELPING_HAND"] = { sprites = 2,
    tasks = {
      { "HelpingHandAttackerMovement" },
      { "ShakeMon2", "ANIM_ATK_PARTNER", "2", "0", "5", "1" },
      { "ShakeMon2", "ANIM_ATK_PARTNER", "2", "0", "5", "1" },
      { "ShakeMon2", "ANIM_ATK_PARTNER", "3", "0", "10", "1" },
      { "BlendMonInAndOut", "ANIM_ATK_PARTNER", "RGB_YELLOW", "12", "1", "1" },
    },
  },
  ["HIDDEN_POWER"] = { sprites = 14,
    tasks = {
      { "ScaleMonAndRestore", "-7", "-7", "11", "ANIM_ATTACKER", "0" },
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB(31", "31", "19)", "12", "5", "1" },
      { "ScaleMonAndRestore", "-7", "-7", "11", "ANIM_ATTACKER", "0" },
      { "ScaleMonAndRestore", "-7", "-7", "11", "ANIM_ATTACKER", "0" },
    },
  },
  ["HI_JUMP_KICK"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMonInPlace", "ANIM_TARGET", "3", "0", "11", "1" },
    },
  },
  ["HORN_ATTACK"] = { sprites = 5,
    tasks = {
      { "ShakeMonInPlace", "ANIM_ATTACKER", "2", "0", "4", "1" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["HORN_DRILL"] = { sprites = 15, bg = 3,
    tasks = {
      { "StartSlidingBg", "2304", "768", "0", "-1" },
      { "ShakeMonInPlace", "ANIM_ATTACKER", "2", "0", "40", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "10", "0", "40", "1" },
      { "StartSlidingBg", "-2304", "768", "1", "-1" },
    },
  },
  ["HOWL"] = { sprites = 6,
    tasks = {
      { "DeepInhale", "ANIM_ATTACKER" },
      { "PlayCryHighPitch", "ANIM_ATTACKER", "3" },
    },
  },
  ["HYDRO_CANNON"] = { sprites = 37, monbg = 1,
    tasks = {
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "ShakeMon", "ANIM_TARGET", "10", "0", "40", "1" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
    },
  },
  ["HYDRO_PUMP"] = { sprites = 56, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "40", "1" },
      { "StartSinAnimTimer", "100" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "37", "1" },
    },
  },
  ["HYPER_BEAM"] = { sprites = 54,
    tasks = {
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "4", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "4", "50", "1" },
      { "FlashAnimTagWithColor", "tag=ANIM_TAG_ORBS", "delay=1", "num_blends=12", "color1=RGB_RED", "blend_y1=16", "color2=RGB_BLACK", "blend_y2=0" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "50", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "11", "RGB(25", "25", "25)" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "11", "0", "RGB(25", "25", "25)" },
    },
  },
  ["HYPER_FANG"] = { sprites = 3, bg = 6,
    tasks = {
      { "IsContest" },
      { "ShakeMon", "ANIM_TARGET", "0", "10", "10", "1" },
      { "IsTargetPlayerSide" },
      { "ShakeMon", "ANIM_TARGET", "0", "10", "10", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "10", "10", "1" },
    },
  },
  ["HYPER_VOICE"] = { sprites = 4,
    tasks = {
      { "PlayCryWithEcho", "FALSE" },
      { "ScaleMonAndRestore", "-5", "-5", "5", "ANIM_ATTACKER", "0" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "6", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "1", "0", "6", "1" },
      { "ShakeBattlePlatforms", "x_offset=1", "y_offset=0", "shakes=6", "delay=1" },
      { "WaitForCry" },
      { "PlayCryWithEcho", "TRUE" },
      { "ScaleMonAndRestore", "-5", "-5", "5", "ANIM_ATTACKER", "0" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "6", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "1", "0", "6", "1" },
      { "ShakeBattlePlatforms", "x_offset=1", "y_offset=0", "shakes=6", "delay=1" },
      { "WaitForCry" },
    },
  },
  ["HYPNOSIS"] = { sprites = 6, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(31", "18", "31)" },
    },
  },
  ["ICE_BALL"] = { sprites = 42, bg = 6,
    tasks = {
      { "GetIceBallCounter", "0" },
      { "GetIceBallCounter", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "8", "1", "0" },
      { "GetIceBallCounter", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "10", "1", "0" },
      { "GetIceBallCounter", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "14", "1", "0" },
      { "GetIceBallCounter", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "18", "1", "0" },
      { "GetIceBallCounter", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "30", "1", "0" },
      { "GetIceBallCounter", "0" },
    },
  },
  ["ICE_BEAM"] = { sprites = 48, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "25", "1" },
    },
  },
  ["ICE_PUNCH"] = { sprites = 19, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "9", "RGB(12", "26", "31)" },
      { "ShakeMon", "ANIM_TARGET", "0", "5", "3", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "9", "0", "RGB(12", "26", "31)" },
    },
  },
  ["ICICLE_SPEAR"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "2", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "2", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "2", "1" },
    },
  },
  ["ICY_WIND"] = { sprites = 23, bg = 2, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_ATK_SIDE", "4", "0", "4", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_ATK_SIDE", "4", "4", "0", "RGB_BLACK" },
    },
  },
  ["IMPRISON"] = { sprites = 1, bg = 2, monbg = 1,
    tasks = {
      { "SetPsychicBackground" },
      { "ImprisonOrbs" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "1", "10" },
    },
  },
  ["INGRAIN"] = { sprites = 7,
  },
  ["IRON_DEFENSE"] = { sprites = 1,
    tasks = {
      { "MetallicShine", "permanent=FALSE" },
    },
  },
  ["IRON_TAIL"] = { sprites = 2, monbg = 1,
    tasks = {
      { "MetallicShine", "permanent=TRUE" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_ATTACKER" },
    },
  },
  ["JUMP_KICK"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "5", "0", "7", "1" },
    },
  },
  ["KARATE_CHOP"] = { sprites = 2, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "4", "0", "6", "1" },
    },
  },
  ["KINESIS"] = { sprites = 3, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
    },
  },
  ["KNOCK_OFF"] = { sprites = 7,
    tasks = {
      { "ShakeMonInPlace", "ANIM_TARGET", "0", "3", "6", "1" },
    },
  },
  ["LEAF_BLADE"] = { sprites = 1, monbg = 1,
    tasks = {
      { "LeafBlade" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon2", "ANIM_TARGET", "8", "0", "18", "1" },
    },
  },
  ["LEECH_LIFE"] = { sprites = 16, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "5", "1" },
    },
  },
  ["LEECH_SEED"] = { sprites = 3,
  },
  ["LEER"] = { sprites = 1, monbg = 1,
    tasks = {
      { "ScaleMonAndRestore", "-5", "-5", "10", "ANIM_ATTACKER", "1" },
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "9", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "1", "0", "9", "1" },
    },
  },
  ["LICK"] = { sprites = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "16", "1" },
    },
  },
  ["LIGHT_SCREEN"] = { sprites = 7,
  },
  ["LOCK_ON"] = { sprites = 5,
  },
  ["LOVELY_KISS"] = { sprites = 5,
  },
  ["LOW_KICK"] = { sprites = 4,
    tasks = {
      { "RotateMonSpriteToSide", "6", "384", "ANIM_TARGET", "2" },
    },
  },
  ["LUSTER_PURGE"] = { sprites = 7, bg = 2, monbg = 1,
    tasks = {
      { "FadeScreenToWhite" },
      { "BlendBattleAnimPalExclude", "5", "2", "0", "16", "RGB_WHITEALPHA" },
      { "BlendParticle", "ANIM_TAG_WHITE_CIRCLE_OF_LIGHT", "2", "0", "16", "RGB_WHITEALPHA" },
      { "BlendParticle", "ANIM_TAG_IMPACT", "0", "12", "12", "RGB(0", "0", "23)" },
      { "PlaySE1WithPanning", "SE_M_HYPER_BEAM", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_HYPER_BEAM", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_HYPER_BEAM", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_HYPER_BEAM", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_HYPER_BEAM", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_HYPER_BEAM", "SOUND_PAN_TARGET" },
      { "BlendBattleAnimPalExclude", "5", "2", "16", "0", "RGB_WHITEALPHA" },
      { "HorizontalShake", "ANIM_TARGET", "5", "14" },
    },
  },
  ["MACH_PUNCH"] = { sprites = 2, bg = 3, monbg = 1,
    tasks = {
      { "GetAttackerSide" },
      { "StartSlidingBg", "-2304", "0", "1", "-1" },
      { "AttackerPunchWithTrace", "RGB(8", "9", "28)", "10" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["MAGICAL_LEAF"] = { sprites = 14, monbg = 1,
    tasks = {
      { "CycleMagicalLeafPal" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
    },
  },
  ["MAGIC_COAT"] = { sprites = 1,
  },
  ["MAGNITUDE"] = { sprites = 4,
    tasks = {
      { "IsPowerOver99" },
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "0", "50" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "0", "50" },
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "0", "50" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "0", "50" },
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "0", "50" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "0", "50" },
      { "HorizontalShake", "(MAX_BATTLERS_COUNT + 1)", "0", "50" },
      { "HorizontalShake", "MAX_BATTLERS_COUNT", "0", "50" },
    },
  },
  ["MEAN_LOOK"] = { sprites = 3, monbg = 1,
  },
  ["MEDITATE"] = { sprites = 0, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
      { "MeditateStretchAttacker" },
    },
  },
  ["MEGAHORN"] = { sprites = 7, bg = 3, monbg = 1,
    tasks = {
      { "StartSlidingBg", "2304", "768", "0", "-1" },
      { "ShakeMon", "ANIM_ATTACKER", "2", "0", "15", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "-4", "1", "12", "1" },
      { "StartSlidingBg", "-2304", "768", "1", "-1" },
    },
  },
  ["MEGA_DRAIN"] = { sprites = 23, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "5", "1" },
    },
  },
  ["MEGA_KICK"] = { sprites = 4, bg = 4, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "7", "RGB_WHITE" },
      { "IsContest" },
      { "IsTargetPlayerSide" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "22", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "0", "RGB_WHITE" },
    },
  },
  ["MEGA_PUNCH"] = { sprites = 4, bg = 4, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "7", "RGB_WHITE" },
      { "IsContest" },
      { "IsTargetPlayerSide" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "22", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "0", "RGB_WHITE" },
    },
  },
  ["MEMENTO"] = { sprites = 0,
    tasks = {
      { "InitMementoShadow" },
      { "MoveAttackerMementoShadow" },
      { "MementoHandleBg" },
      { "MoveTargetMementoShadow" },
    },
  },
  ["METAL_CLAW"] = { sprites = 8,
    tasks = {
      { "MetallicShine", "permanent=FALSE" },
    },
  },
  ["METAL_SOUND"] = { sprites = 4, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_ATTACKER", "2", "0", "8", "1" },
    },
  },
  ["METEOR_MASH"] = { sprites = 5, bg = 2,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "5", "0", "20", "1" },
    },
  },
  ["METRONOME"] = { sprites = 2,
  },
  ["MILK_DRINK"] = { sprites = 6, monbg = 1,
  },
  ["MIMIC"] = { sprites = 1,
    tasks = {
      { "ShrinkTargetCopy", "unk0=128", "unk1=24" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=11", "color=RGB_WHITE" },
    },
  },
  ["MIND_READER"] = { sprites = 20, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG", "delay=1", "num_blends=2", "initial_blend_y=0", "target_blend_y=10", "color=RGB_BLACK" },
    },
  },
  ["MINIMIZE"] = { sprites = 0,
    tasks = {
      { "Minimize" },
    },
  },
  ["MIRROR_COAT"] = { sprites = 7,
  },
  ["MIRROR_MOVE"] = { sprites = 0,
  },
  ["MIST"] = { sprites = 7, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATK_SIDE", "delay=8", "num_blends=2", "initial_blend_y=0", "target_blend_y=14", "color=RGB_WHITE" },
    },
  },
  ["MIST_BALL"] = { sprites = 2,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "5", "0", "10", "0" },
      { "MistBallFog" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "3", "0", "16", "RGB_WHITE" },
      { "ShakeMon", "ANIM_TARGET", "4", "0", "70", "0" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "16", "0", "RGB_WHITE" },
    },
  },
  ["MOONLIGHT"] = { sprites = 11,
    tasks = {
      { "AlphaFadeIn", "0", "16", "16", "0", "1" },
      { "MoonlightEndFade" },
    },
  },
  ["MORNING_SUN"] = { sprites = 19,
    tasks = {
      { "MorningSunLightBeam" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_BATTLERS_2", "8", "0", "12", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_BATTLERS_2", "3", "12", "0", "RGB_WHITE" },
    },
  },
  ["MUDDY_WATER"] = { sprites = 0,
    tasks = {
      { "CreateSurfWave", "palette=ANIM_SURF_PAL_MUDDY_WATER" },
    },
  },
  ["MUD_SHOT"] = { sprites = 22, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "46", "1" },
      { "StartSinAnimTimer", "100" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "43", "1" },
    },
  },
  ["MUD_SLAP"] = { sprites = 32,
  },
  ["MUD_SPORT"] = { sprites = 16,
    tasks = {
      { "Splash", "0", "6" },
    },
  },
  ["NATURE_POWER"] = { sprites = 0,
  },
  ["NEEDLE_ARM"] = { sprites = 22,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "18", "1" },
    },
  },
  ["NIGHTMARE"] = { sprites = 0, bg = 3, monbg = 1,
    tasks = {
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB_WHITE", "10", "2", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "3", "0", "32", "1" },
      { "NightmareClone" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "40", "1" },
    },
  },
  ["NIGHT_SHADE"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "NightShadeClone", "85" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "12", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=13", "color=RGB_BLACK" },
    },
  },
  ["OCTAZOOKA"] = { sprites = 5,
  },
  ["ODOR_SLEUTH"] = { sprites = 3, monbg = 1,
    tasks = {
      { "OdorSleuthMovement" },
    },
  },
  ["OUTRAGE"] = { sprites = 23,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER | F_PAL_TARGET", "delay=2", "num_blends=5", "initial_blend_y=3", "target_blend_y=8", "color=RGB(14", "13", "0)" },
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "12", "6", "5", "4" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "40", "1" },
    },
  },
  ["OVERHEAT"] = { sprites = 33, monbg = 1,
    tasks = {
      { "AllocBackupPalBuffer" },
      { "CopyPalUnfadedToBackup", "0", "1" },
      { "CopyPalFadedToUnfaded", "0" },
      { "CopyPalUnfadedToBackup", "1", "0" },
      { "ShakeMon", "ANIM_ATTACKER", "2", "0", "15", "1" },
      { "ShakeMon", "ANIM_TARGET", "10", "0", "25", "1" },
      { "CopyPalFadedToUnfaded", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "3", "0", "15", "1" },
      { "CopyPalUnfadedFromBackup", "0", "1" },
      { "CopyPalUnfadedFromBackup", "1", "0" },
      { "FreeBackupPalBuffer" },
    },
  },
  ["PAIN_SPLIT"] = { sprites = 6,
    tasks = {
      { "PainSplitMovement", "ANIM_ATTACKER", "0" },
      { "PainSplitMovement", "ANIM_TARGET", "0" },
      { "PainSplitMovement", "ANIM_ATTACKER", "1" },
      { "PainSplitMovement", "ANIM_TARGET", "1" },
      { "PainSplitMovement", "ANIM_ATTACKER", "2" },
      { "PainSplitMovement", "ANIM_TARGET", "2" },
    },
  },
  ["PAY_DAY"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "6", "1" },
    },
  },
  ["PECK"] = { sprites = 1,
    tasks = {
      { "RotateMonToSideAndRestore", "3", "-768", "ANIM_TARGET", "2" },
    },
  },
  ["PERISH_SONG"] = { sprites = 19,
    tasks = {
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_PLAYER_LEFT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_PLAYER_RIGHT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_OPPONENT_LEFT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_OPPONENT_RIGHT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_PLAYER_LEFT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_PLAYER_RIGHT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_OPPONENT_LEFT" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_OPPONENT_RIGHT" },
    },
  },
  ["PETAL_DANCE"] = { sprites = 16, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "12", "6", "6", "3" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
    },
  },
  ["PIN_MISSILE"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "2", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "2", "1" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "2", "1" },
    },
  },
  ["POISONPOWDER"] = { sprites = 15,
  },
  ["POISON_FANG"] = { sprites = 7,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "10", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=0", "num_blends=4", "initial_blend_y=0", "target_blend_y=12", "color=RGB(26", "0", "26)" },
    },
  },
  ["POISON_GAS"] = { sprites = 6, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=6", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(26", "0", "26)" },
    },
  },
  ["POISON_STING"] = { sprites = 8, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "5", "1" },
    },
  },
  ["POISON_TAIL"] = { sprites = 8, monbg = 1,
    tasks = {
      { "MetallicShine", "permanent=TRUE", "color=RGB(24", "6", "23)" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "SetGrayscaleOrOriginalPal", "battler=ANIM_ATTACKER" },
    },
  },
  ["POUND"] = { sprites = 1, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["POWDER_SNOW"] = { sprites = 27, monbg = 1,
  },
  ["PRESENT"] = { sprites = 19,
    tasks = {
      { "IsHealingMove" },
    },
  },
  ["PROTECT"] = { sprites = 1, monbg = 1,
  },
  ["PSYBEAM"] = { sprites = 11, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
      { "SwayMon", "0", "6", "2048", "4", "ANIM_TARGET" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(31", "18", "31)" },
    },
  },
  ["PSYCHIC"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "SetPsychicBackground" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "10", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=8", "color=RGB(31", "23", "0)" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "15", "1" },
      { "ScaleMonAndRestore", "-6", "-6", "15", "ANIM_TARGET", "1" },
    },
  },
  ["PSYCHO_BOOST"] = { sprites = 1, bg = 2, monbg = 1,
    tasks = {
      { "FadeScreenToWhite" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG", "delay=2", "num_blends=8", "initial_blend_y=0", "target_blend_y=10", "color=RGB_BLACK" },
      { "ShakeMon", "ANIM_ATTACKER", "3", "0", "240", "0" },
      { "ShakeMon2", "ANIM_TARGET", "-8", "1", "24", "1" },
    },
  },
  ["PSYCH_UP"] = { sprites = 1, monbg = 1,
    tasks = {
      { "BlendColorCycleExclude", "unk0=1", "delay=2", "num_blends=6", "initial_blend_y=1", "target_blend_y=11", "color=RGB_BLACK" },
      { "SwayMon", "0", "5", "2560", "8", "ANIM_ATTACKER" },
      { "ScaleMonAndRestore", "-5", "-5", "10", "ANIM_ATTACKER", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "2", "10", "0", "RGB_YELLOW" },
    },
  },
  ["PSYWAVE"] = { sprites = 12, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
      { "StartSinAnimTimer", "100" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=1", "num_blends=4", "initial_blend_y=0", "target_blend_y=12", "color=RGB(31", "18", "31)" },
    },
  },
  ["PURSUIT"] = { sprites = 2, bg = 3, monbg = 1,
    tasks = {
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "6", "1", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "6", "1", "0" },
    },
  },
  ["QUICK_ATTACK"] = { sprites = 1, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "24", "6", "1", "5" },
      { "TraceMonBlended", "0", "4", "7", "3" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["RAGE"] = { sprites = 4, monbg = 1,
    tasks = {
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB_RED", "10", "0", "2" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "TRUE", "1", "10", "1", "0" },
    },
  },
  ["RAIN_DANCE"] = { sprites = 0,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_BATTLERS_2", "2", "0", "4", "RGB_BLACK" },
      { "CreateRaindrops", "0", "3", "120" },
      { "CreateRaindrops", "0", "3", "120" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_BATTLERS_2", "2", "4", "0", "RGB_BLACK" },
    },
  },
  ["RAPID_SPIN"] = { sprites = 2, monbg = 1,
    tasks = {
      { "RapinSpinMonElevation", "0", "2", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "10", "1", "0" },
      { "RapinSpinMonElevation", "0", "2", "1" },
    },
  },
  ["RAZOR_LEAF"] = { sprites = 12, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "2", "0", "8", "1" },
    },
  },
  ["RAZOR_WIND"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "10", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "2", "0", "10", "1" },
    },
  },
  ["RECOVER"] = { sprites = 25, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=6", "initial_blend_y=0", "target_blend_y=11", "color=RGB(31", "31", "11)" },
    },
  },
  ["RECYCLE"] = { sprites = 1, monbg = 1,
    tasks = {
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB_WHITE", "12", "2", "1" },
    },
  },
  ["REFLECT"] = { sprites = 4,
  },
  ["REFRESH"] = { sprites = 4,
    tasks = {
      { "StatusClearedEffect", "0" },
    },
  },
  ["REST"] = { sprites = 3,
  },
  ["RETURN"] = { sprites = 39, monbg = 1,
    tasks = {
      { "GetReturnPowerLevel" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_COMET_PUNCH", "SOUND_PAN_TARGET" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_MEGA_KICK2", "SOUND_PAN_TARGET" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE2WithPanning", "SE_M_TAIL_WHIP", "SOUND_PAN_ATTACKER" },
      { "PlaySE1WithPanning", "SE_M_VITAL_THROW2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
      { "TraceMonBlended", "0", "4", "5", "1" },
      { "PlaySE1WithPanning", "SE_M_MEGA_KICK2", "SOUND_PAN_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "8", "0", "24", "1" },
      { "PlaySE1WithPanning", "SE_M_MEGA_KICK2", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_MEGA_KICK2", "SOUND_PAN_TARGET" },
      { "PlaySE1WithPanning", "SE_M_MEGA_KICK2", "SOUND_PAN_TARGET" },
    },
  },
  ["REVENGE"] = { sprites = 5, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=0", "num_blends=4", "initial_blend_y=2", "target_blend_y=8", "color=RGB_RED" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "10", "1" },
    },
  },
  ["REVERSAL"] = { sprites = 11,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_BATTLERS", "delay=3", "num_blends=2", "initial_blend_y=0", "target_blend_y=10", "color=RGB_WHITE" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "8", "1", "0" },
    },
  },
  ["ROAR"] = { sprites = 6, monbg = 1,
    tasks = {
      { "PlayDoubleCry", "ANIM_ATTACKER", "DOUBLE_CRY_ROAR" },
      { "ScaleMonAndRestore", "-5", "-5", "10", "ANIM_ATTACKER", "1" },
      { "SlideOffScreen", "ANIM_TARGET", "2" },
      { "WaitForCry" },
    },
  },
  ["ROCK_BLAST"] = { sprites = 7,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "5", "1" },
    },
  },
  ["ROCK_SLIDE"] = { sprites = 21, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "50", "1" },
      { "ShakeMon", "ANIM_DEF_PARTNER", "0", "5", "50", "1" },
    },
  },
  ["ROCK_SMASH"] = { sprites = 10, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "7", "1" },
    },
  },
  ["ROCK_THROW"] = { sprites = 6,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "5", "20", "1" },
    },
  },
  ["ROCK_TOMB"] = { sprites = 5,
    tasks = {
      { "ShakeBattlePlatforms", "x_offset=2", "y_offset=0", "shakes=10", "delay=1" },
      { "ShakeBattlePlatforms", "x_offset=0", "y_offset=2", "shakes=3", "delay=1" },
      { "ShakeBattlePlatforms", "x_offset=0", "y_offset=2", "shakes=3", "delay=1" },
      { "ShakeBattlePlatforms", "x_offset=0", "y_offset=2", "shakes=3", "delay=1" },
      { "ShakeBattlePlatforms", "x_offset=0", "y_offset=2", "shakes=3", "delay=1" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "20", "1" },
      { "ShakeBattlePlatforms", "x_offset=2", "y_offset=0", "shakes=10", "delay=1" },
    },
  },
  ["ROLE_PLAY"] = { sprites = 2, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "0", "16", "RGB_WHITE" },
      { "RolePlaySilhouette" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "2", "16", "0", "RGB_WHITE" },
    },
  },
  ["ROLLING_KICK"] = { sprites = 4, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "18", "6", "1", "4" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "6", "1" },
    },
  },
  ["ROLLOUT"] = { sprites = 1, monbg = 1,
    tasks = {
      { "Rollout" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "30", "1", "0" },
    },
  },
  ["SACRED_FIRE"] = { sprites = 19,
    tasks = {
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
    },
  },
  ["SAFEGUARD"] = { sprites = 3, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATK_SIDE", "delay=0", "num_blends=2", "initial_blend_y=0", "target_blend_y=10", "color=RGB_WHITE" },
    },
  },
  ["SANDSTORM"] = { sprites = 7,
    tasks = {
      { "LoadSandstormBackground", "FALSE" },
    },
  },
  ["SAND_ATTACK"] = { sprites = 32, monbg = 1,
  },
  ["SAND_TOMB"] = { sprites = 20,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "2", "43", "1" },
    },
  },
  ["SCARY_FACE"] = { sprites = 4,
    tasks = {
      { "ScaryFace" },
      { "ShakeTargetInPattern", "20", "1", "FALSE" },
    },
  },
  ["SCRATCH"] = { sprites = 1, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["SCREECH"] = { sprites = 2,
    tasks = {
      { "ShakeMon2", "ANIM_ATTACKER", "3", "0", "2", "1" },
      { "SwayMon", "0", "6", "2048", "2", "ANIM_TARGET" },
    },
  },
  ["SECRET_POWER"] = { sprites = 137, monbg = 7,
    tasks = {
      { "GetBattleEnvironment" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "18", "1" },
      { "CycleMagicalLeafPal" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "46", "1" },
      { "StartSinAnimTimer", "100" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "43", "1" },
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "23", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "17", "1" },
      { "CreateSurfWave", "palette=ANIM_SURF_PAL_SURF" },
      { "SwayMon", "0", "3", "3072", "8", "ANIM_TARGET" },
      { "ShakeMon", "ANIM_TARGET", "0", "5", "20", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "4", "7", "1" },
      { "ShakeAndSinkMon", "ANIM_ATTACKER", "2", "0", "96", "30" },
      { "TranslateMonEllipticalRespectSide", "ANIM_TARGET", "18", "6", "2", "4" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "0", "3", "6", "1" },
    },
  },
  ["SEISMIC_TOSS"] = { sprites = 45, bg = 4, monbg = 1,
    tasks = {
      { "GetSeismicTossDamageLevel" },
      { "MoveSeismicTossBg" },
      { "SeismicTossBgAccelerateDownAtEnd" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "5", "1" },
    },
  },
  ["SELFDESTRUCT"] = { sprites = 10,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "0", "9", "RGB_RED" },
      { "ShakeMon2", "ANIM_PLAYER_LEFT", "6", "0", "38", "1" },
      { "ShakeMon2", "ANIM_PLAYER_RIGHT", "6", "0", "38", "1" },
      { "ShakeMon2", "ANIM_OPPONENT_LEFT", "6", "0", "38", "1" },
      { "ShakeMon2", "ANIM_OPPONENT_RIGHT", "6", "0", "38", "1" },
      { "ShakeMon2", "ANIM_ATTACKER_FORCE", "6", "0", "38", "1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "9", "0", "RGB_RED" },
    },
  },
  ["SHADOW_BALL"] = { sprites = 1, bg = 2,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "8", "1" },
    },
  },
  ["SHADOW_PUNCH"] = { sprites = 2, bg = 2, monbg = 1,
    tasks = {
      { "AttackerPunchWithTrace", "RGB_BLACK", "13" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["SHARPEN"] = { sprites = 1,
  },
  ["SHEER_COLD"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "FrozenIceCube" },
    },
  },
  ["SHOCK_WAVE"] = { sprites = 2, monbg = 1,
    tasks = {
      { "ElectricChargingParticles", "ANIM_ATTACKER", "20", "0", "2" },
      { "ShockWaveProgressingBolt" },
      { "ShockWaveLightning" },
      { "ShakeMon", "ANIM_TARGET", "0", "6", "18", "1" },
      { "BlendBattleAnimPal", "F_PAL_BG", "3", "16", "0", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "16", "16", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "0", "0", "RGB_BLACK" },
    },
  },
  ["SIGNAL_BEAM"] = { sprites = 47,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "25", "1" },
      { "StartSinAnimTimer", "100" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "25", "1" },
    },
  },
  ["SILVER_WIND"] = { sprites = 18, bg = 3, monbg = 1,
    tasks = {
      { "BlendBattleAnimPalExclude", "ANIM_TARGET", "0", "0", "4", "RGB_BLACK" },
      { "GetTargetSide" },
      { "StartSlidingBg", "-1536", "0", "0", "-1" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "4", "4", "RGB_BLACK" },
      { "BlendBattleAnimPalExclude", "ANIM_TARGET", "0", "4", "0", "RGB_BLACK" },
      { "StartSlidingBg", "1536", "0", "0", "-1" },
    },
  },
  ["SING"] = { sprites = 12, monbg = 1,
    tasks = {
      { "MusicNotesRainbowBlend" },
      { "MusicNotesClearRainbowBlend" },
    },
  },
  ["SKETCH"] = { sprites = 1, monbg = 1,
    tasks = {
      { "SketchDrawMon" },
      { "Splash", "0", "2" },
    },
  },
  ["SKILL_SWAP"] = { sprites = 0, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
      { "SkillSwap", "ANIM_TARGET" },
      { "BlendMonInAndOut", "ANIM_TARGET", "RGB_WHITE", "12", "3", "1" },
      { "SkillSwap", "ANIM_ATTACKER" },
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB_WHITE", "12", "3", "1" },
    },
  },
  ["SKULL_BASH"] = { sprites = 6,
    tasks = {
      { "RotateMonSpriteToSide", "16", "96", "ANIM_ATTACKER", "2" },
      { "RotateMonSpriteToSide", "16", "96", "ANIM_ATTACKER", "2" },
      { "SkullBashPosition", "0" },
      { "ShakeMonInPlace", "ANIM_ATTACKER", "2", "0", "40", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "10", "0", "40", "1" },
      { "SkullBashPosition", "1" },
    },
  },
  ["SKY_ATTACK"] = { sprites = 1, bg = 3, monbg = 2,
    tasks = {
      { "GetTargetIsAttackerPartner", "ARG_RET_ID" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_ATK_SIDE | F_PAL_DEF_PARTNER", "1", "0", "12", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "8", "0", "RGB_BLACK" },
      { "HorizontalShake", "ANIM_ATTACKER", "2", "16" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "0", "15", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "15", "0", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_ATK_PARTNER | F_PAL_DEF_PARTNER", "1", "8", "0", "RGB_BLACK" },
      { "BlendBattleAnimPalExclude", "ANIM_TARGET", "1", "0", "12", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "8", "0", "RGB_BLACK" },
      { "HorizontalShake", "ANIM_ATTACKER", "2", "16" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "0", "15", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "1", "15", "0", "RGB_WHITE" },
      { "BlendBattleAnimPalExclude", "4", "1", "8", "0", "RGB_BLACK" },
      { "StartSlidingBg", "2304", "768", "0", "-1" },
      { "StartSlidingBg", "-2304", "768", "1", "-1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "0", "0", "16", "RGB_WHITE" },
      { "AttackerFadeToInvisible", "priority=5", "step_delay=0" },
      { "PlaySE2WithPanning", "SE_M_SKY_UPPERCUT", "SOUND_PAN_ATTACKER" },
      { "ShakeMon2", "ANIM_TARGET", "10", "0", "18", "1" },
      { "PlaySE1WithPanning", "SE_M_MEGA_KICK2", "SOUND_PAN_TARGET" },
      { "AttackerFadeFromInvisible", "priority=5", "step_delay=1" },
      { "BlendBattleAnimPal", "F_PAL_ATTACKER", "0", "15", "0", "RGB_WHITE" },
    },
  },
  ["SKY_UPPERCUT"] = { sprites = 9, bg = 2, monbg = 1,
    tasks = {
      { "MoveSkyUppercutBg", "55" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "6", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "0", "3", "6", "1" },
    },
  },
  ["SLACK_OFF"] = { sprites = 4,
    tasks = {
      { "SlackOffSquish", "ANIM_ATTACKER" },
    },
  },
  ["SLAM"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMonInPlace", "ANIM_TARGET", "0", "3", "6", "1" },
    },
  },
  ["SLASH"] = { sprites = 2,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "18", "1" },
    },
  },
  ["SLEEP_POWDER"] = { sprites = 15,
  },
  ["SLEEP_TALK"] = { sprites = 9,
    tasks = {
      { "SwayMon", "0", "4", "4096", "2", "ANIM_ATTACKER" },
    },
  },
  ["SLUDGE"] = { sprites = 7,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "5", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=1", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(30", "0", "31)" },
    },
  },
  ["SLUDGE_BOMB"] = { sprites = 28,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "15", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=1", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(30", "0", "31)" },
    },
  },
  ["SMELLINGSALT"] = { sprites = 3,
    tasks = {
      { "SmellingSaltsSquish", "ANIM_TARGET", "2" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "6", "2" },
    },
  },
  ["SMOG"] = { sprites = 7, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=12", "color=RGB(26", "0", "26)" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "15", "1" },
    },
  },
  ["SMOKESCREEN"] = { sprites = 13,
    tasks = {
      { "SmokescreenImpact" },
    },
  },
  ["SNATCH"] = { sprites = 0,
    tasks = {
      { "WindUpLunge", "ANIM_ATTACKER", "-12", "4", "10", "10", "12", "6" },
    },
  },
  ["SNORE"] = { sprites = 8, monbg = 1,
    tasks = {
      { "ScaleMonAndRestore", "-7", "-7", "7", "ANIM_ATTACKER", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "7", "1" },
      { "ScaleMonAndRestore", "-7", "-7", "7", "ANIM_ATTACKER", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "7", "1" },
    },
  },
  ["SOFTBOILED"] = { sprites = 9, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "6", "1" },
    },
  },
  ["SOLARBEAM"] = { sprites = 35, bg = 4, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=1", "num_blends=4", "initial_blend_y=0", "target_blend_y=11", "color=RGB(31", "31", "11)" },
      { "IsContest" },
      { "IsTargetPlayerSide" },
      { "CreateSmallSolarBeamOrbs" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "1", "0", "10", "RGB(25", "31", "0)" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "65", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "1", "10", "0", "RGB(25", "31", "0)" },
    },
  },
  ["SONICBOOM"] = { sprites = 4, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "10", "1" },
    },
  },
  ["SPARK"] = { sprites = 24,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER", "delay=-31", "num_blends=1", "initial_blend_y=5", "target_blend_y=5", "color=RGB(31", "31", "22)" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER", "delay=-31", "num_blends=1", "initial_blend_y=0", "target_blend_y=0", "color=RGB(31", "31", "22)" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER", "delay=-31", "num_blends=1", "initial_blend_y=5", "target_blend_y=5", "color=RGB(31", "31", "22)" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER", "delay=-31", "num_blends=1", "initial_blend_y=0", "target_blend_y=0", "color=RGB(31", "31", "22)" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER", "delay=-31", "num_blends=1", "initial_blend_y=7", "target_blend_y=7", "color=RGB(31", "31", "22)" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_BG | F_PAL_ATTACKER", "delay=-31", "num_blends=1", "initial_blend_y=0", "target_blend_y=0", "color=RGB(31", "31", "22)" },
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
      { "BlendColorCycle", "priority=2", "selector=F_PAL_TARGET", "delay=-31", "num_blends=2", "initial_blend_y=0", "target_blend_y=6", "color=RGB(31", "31", "22)" },
    },
  },
  ["SPIDER_WEB"] = { sprites = 17, monbg = 1,
  },
  ["SPIKES"] = { sprites = 3, monbg = 1,
  },
  ["SPIKE_CANNON"] = { sprites = 7, monbg = 1,
    tasks = {
      { "WindUpLunge", "ANIM_ATTACKER", "-4", "0", "4", "6", "8", "4" },
      { "ShakeMon2", "ANIM_TARGET", "3", "0", "7", "1" },
    },
  },
  ["SPITE"] = { sprites = 0, bg = 2, monbg = 1,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=2", "num_blends=6", "initial_blend_y=0", "target_blend_y=8", "color=RGB_WHITE" },
      { "SpiteTargetShadow" },
    },
  },
  ["SPIT_UP"] = { sprites = 24,
    tasks = {
      { "SpitUpDeformMon" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "8", "2" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "8", "1", "0" },
      { "ShakeTargetBasedOnMovePowerOrDmg", "FALSE", "1", "8", "1", "0" },
    },
  },
  ["SPLASH"] = { sprites = 0,
    tasks = {
      { "Splash", "0", "3" },
    },
  },
  ["SPORE"] = { sprites = 9, monbg = 1,
    tasks = {
      { "SporeDoubleBattle" },
    },
  },
  ["STEEL_WING"] = { sprites = 6, monbg = 1,
    tasks = {
      { "MetallicShine", "permanent=FALSE" },
      { "TranslateMonElliptical", "0", "12", "4", "1", "4" },
      { "AnimateGustTornadoPalette", "1", "70" },
    },
  },
  ["STOCKPILE"] = { sprites = 17,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=8", "num_blends=1", "initial_blend_y=0", "target_blend_y=12", "color=RGB_WHITE" },
      { "StockpileDeformMon" },
    },
  },
  ["STOMP"] = { sprites = 2, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "4", "9", "1" },
    },
  },
  ["STRENGTH"] = { sprites = 4, monbg = 1,
    tasks = {
      { "ShakeAndSinkMon", "ANIM_ATTACKER", "2", "0", "96", "30" },
      { "TranslateMonEllipticalRespectSide", "ANIM_TARGET", "18", "6", "2", "4" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
    },
  },
  ["STRING_SHOT"] = { sprites = 23, monbg = 1,
  },
  ["STRUGGLE"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMonInPlace", "ANIM_ATTACKER", "3", "0", "12", "4" },
      { "ShakeMonInPlace", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["STUN_SPORE"] = { sprites = 15,
  },
  ["SUBMISSION"] = { sprites = 9, monbg = 1,
    tasks = {
      { "TranslateMonElliptical", "0", "-18", "6", "6", "4" },
      { "TranslateMonElliptical", "1", "18", "6", "6", "4" },
    },
  },
  ["SUBSTITUTE"] = { sprites = 0,
    tasks = {
      { "MonToSubstitute" },
    },
  },
  ["SUNNY_DAY"] = { sprites = 4, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_BATTLERS_2", "1", "0", "6", "RGB_WHITE" },
      { "BlendBattleAnimPal", "F_PAL_BG | F_PAL_BATTLERS_2", "1", "6", "0", "RGB_WHITE" },
    },
  },
  ["SUPERPOWER"] = { sprites = 8, monbg = 1,
    tasks = {
      { "PlaySE2WithPanning", "SE_M_EARTHQUAKE", "0" },
      { "ShakeMon2", "ANIM_TARGET", "8", "0", "16", "1" },
    },
  },
  ["SUPERSONIC"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_ATTACKER", "2", "0", "8", "1" },
    },
  },
  ["SUPER_FANG"] = { sprites = 3,
    tasks = {
      { "ShakeMonInPlace", "ANIM_ATTACKER", "1", "0", "20", "1" },
      { "ShakeMonInPlace", "ANIM_ATTACKER", "3", "0", "48", "1" },
      { "BlendMonInAndOut", "ANIM_ATTACKER", "RGB(31", "6", "1)", "12", "4", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "7", "12", "1" },
    },
  },
  ["SURF"] = { sprites = 0,
    tasks = {
      { "CreateSurfWave", "palette=ANIM_SURF_PAL_SURF" },
    },
  },
  ["SWAGGER"] = { sprites = 3,
    tasks = {
      { "GrowAndShrink" },
    },
  },
  ["SWALLOW"] = { sprites = 28,
    tasks = {
      { "SwallowDeformMon" },
      { "ShakeMon2", "ANIM_ATTACKER", "1", "0", "8", "2" },
      { "ShakeMon2", "ANIM_ATTACKER", "2", "0", "12", "1" },
    },
  },
  ["SWEET_KISS"] = { sprites = 7,
  },
  ["SWEET_SCENT"] = { sprites = 24,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_DEF_SIDE", "delay=1", "num_blends=5", "initial_blend_y=5", "target_blend_y=13", "color=RGB(31", "21", "21)" },
    },
  },
  ["SWIFT"] = { sprites = 5, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "18", "1" },
      { "ShakeMon2", "ANIM_DEF_PARTNER", "2", "0", "18", "1" },
    },
  },
  ["SWORDS_DANCE"] = { sprites = 1, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "16", "6", "1", "4" },
      { "FlashAnimTagWithColor", "tag=ANIM_TAG_SWORD", "delay=2", "num_blends=2", "color1=RGB(18", "31", "31)", "blend_y1=16", "color2=RGB_BLACK", "blend_y2=0" },
    },
  },
  ["SYNTHESIS"] = { sprites = 6,
    tasks = {
      { "BlendColorCycle", "priority=2", "selector=F_PAL_ATTACKER", "delay=2", "num_blends=2", "initial_blend_y=0", "target_blend_y=16", "color=RGB(27", "31", "18)" },
    },
  },
  ["TACKLE"] = { sprites = 2, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "3", "0", "6", "1" },
    },
  },
  ["TAIL_GLOW"] = { sprites = 3, monbg = 1,
  },
  ["TAIL_WHIP"] = { sprites = 0,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "12", "4", "2", "3" },
    },
  },
  ["TAKE_DOWN"] = { sprites = 5, monbg = 1,
    tasks = {
      { "WindUpLunge", "ANIM_ATTACKER", "-24", "8", "23", "10", "40", "10" },
      { "ShakeMonInPlace", "ANIM_TARGET", "4", "0", "12", "1" },
    },
  },
  ["TAUNT"] = { sprites = 4,
  },
  ["TEETER_DANCE"] = { sprites = 5,
    tasks = {
      { "TeeterDanceMovement" },
    },
  },
  ["TELEPORT"] = { sprites = 0, bg = 2,
    tasks = {
      { "SetPsychicBackground" },
      { "Teleport" },
    },
  },
  ["THIEF"] = { sprites = 2, bg = 2, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "8", "1" },
    },
  },
  ["THRASH"] = { sprites = 3,
    tasks = {
      { "ThrashMoveMonHorizontal" },
      { "ThrashMoveMonVertical" },
      { "ShakeMonInPlace", "ANIM_TARGET", "4", "0", "7", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "4", "0", "7", "1" },
      { "ShakeMonInPlace", "ANIM_TARGET", "8", "0", "16", "1" },
    },
  },
  ["THUNDER"] = { sprites = 14, bg = 2,
    tasks = {
      { "StartSlidingBg", "-256", "0", "1", "-1" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "ShakeTargetInPattern", "30", "3", "TRUE", "0" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
    },
  },
  ["THUNDERBOLT"] = { sprites = 17,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "0", "6", "RGB_BLACK" },
      { "ElectricBolt", "24", "-52", "0" },
      { "ElectricBolt", "-24", "-52", "0" },
      { "ElectricBolt", "0", "-60", "1" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "0", "13", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "13", "0", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "2", "2", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "6", "6", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "2", "2", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "6", "6", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "6", "0", "RGB_BLACK" },
    },
  },
  ["THUNDERPUNCH"] = { sprites = 8, monbg = 1,
    tasks = {
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "15", "1" },
    },
  },
  ["THUNDERSHOCK"] = { sprites = 8,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "0", "6", "RGB_BLACK" },
      { "ElectricBolt", "0", "-44", "0" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "0", "13", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_TARGET", "0", "13", "0", "RGB_BLACK" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "6", "0", "RGB_BLACK" },
    },
  },
  ["THUNDER_WAVE"] = { sprites = 3,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "0", "6", "RGB_BLACK" },
      { "ElectricBolt", "0", "-48", "0" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "6", "0", "RGB_BLACK" },
    },
  },
  ["TICKLE"] = { sprites = 4,
    tasks = {
      { "SwayMon", "0", "6", "1280", "3", "ANIM_ATTACKER" },
      { "RockMonBackAndForth", "ANIM_TARGET", "6", "2" },
    },
  },
  ["TORMENT"] = { sprites = 2,
    tasks = {
      { "TormentAttacker" },
      { "BlendMonInAndOut", "ANIM_TARGET", "RGB_RED", "10", "1", "1" },
    },
  },
  ["TOXIC"] = { sprites = 14,
  },
  ["TRANSFORM"] = { sprites = 0, monbg = 1,
    tasks = {
      { "TransformMon", "0" },
    },
  },
  ["TRICK"] = { sprites = 2,
    tasks = {
      { "StretchTargetUp" },
      { "StretchAttackerUp" },
      { "ShakeMon", "ANIM_ATTACKER", "5", "0", "7", "2" },
      { "ShakeMon", "ANIM_TARGET", "5", "0", "7", "2" },
    },
  },
  ["TRIPLE_KICK"] = { sprites = 6, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "4", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "4", "0", "6", "1" },
      { "ShakeMon", "ANIM_TARGET", "6", "0", "8", "1" },
    },
  },
  ["TRI_ATTACK"] = { sprites = 21,
    tasks = {
      { "ShakeTargetInPattern", "20", "3", "TRUE", "1" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
      { "ShakeTargetInPattern", "20", "3", "TRUE", "0" },
      { "InvertScreenColor", "scenery=TRUE", "attacker=TRUE", "target=TRUE" },
    },
  },
  ["TWINEEDLE"] = { sprites = 4, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "5", "1" },
    },
  },
  ["TWISTER"] = { sprites = 16, monbg = 1,
    tasks = {
      { "ShakeMonInPlace", "ANIM_TARGET", "3", "0", "12", "1" },
      { "ShakeMonInPlace", "ANIM_DEF_PARTNER", "3", "0", "12", "1" },
    },
  },
  ["UPROAR"] = { sprites = 9, monbg = 1,
    tasks = {
      { "UproarDistortion", "0" },
      { "UproarDistortion", "0" },
      { "UproarDistortion", "0" },
    },
  },
  ["VICEGRIP"] = { sprites = 3, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "5", "1" },
    },
  },
  ["VINE_WHIP"] = { sprites = 2,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "6", "1" },
    },
  },
  ["VITAL_THROW"] = { sprites = 5, monbg = 1,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "12", "4", "1", "2" },
    },
  },
  ["VOLT_TACKLE"] = { sprites = 5, monbg = 1,
    tasks = {
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "0", "8", "RGB_BLACK" },
      { "VoltTackleBolt", "0" },
      { "VoltTackleBolt", "1" },
      { "VoltTackleBolt", "2" },
      { "VoltTackleBolt", "3" },
      { "VoltTackleBolt", "4" },
      { "ShakeMon2", "ANIM_TARGET", "10", "0", "18", "1" },
      { "VoltTackleAttackerReappear" },
      { "ShakeMon2", "ANIM_ATTACKER", "3", "0", "9", "1" },
      { "BlendBattleAnimPal", "F_PAL_BG", "0", "8", "0", "RGB_BLACK" },
    },
  },
  ["WATERFALL"] = { sprites = 36, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_ATTACKER", "0", "2", "23", "1" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "17", "1" },
    },
  },
  ["WATER_GUN"] = { sprites = 5, monbg = 1,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "1", "0", "8", "1" },
    },
  },
  ["WATER_PULSE"] = { sprites = 10, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "8", "18", "1" },
    },
  },
  ["WATER_SPORT"] = { sprites = 0,
    tasks = {
      { "WaterSport" },
    },
  },
  ["WATER_SPOUT"] = { sprites = 0, monbg = 1,
    tasks = {
      { "WaterSpoutLaunch" },
      { "WaterSpoutRain" },
    },
  },
  ["WEATHER_BALL"] = { sprites = 28,
    tasks = {
      { "GetWeather" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "8", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "8", "1" },
      { "ShakeMon", "ANIM_TARGET", "0", "3", "8", "1" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
      { "ShakeMon2", "ANIM_TARGET", "2", "0", "8", "1" },
    },
  },
  ["WHIRLPOOL"] = { sprites = 20, monbg = 1,
    tasks = {
      { "ShakeMon", "ANIM_TARGET", "0", "2", "50", "1" },
    },
  },
  ["WHIRLWIND"] = { sprites = 6,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "15", "1" },
      { "TranslateMonEllipticalRespectSide", "ANIM_TARGET", "12", "6", "1", "5" },
      { "SlideOffScreen", "ANIM_TARGET", "8" },
    },
  },
  ["WILL_O_WISP"] = { sprites = 10, monbg = 1,
    tasks = {
      { "AdjustPanningVar", "SOUND_PAN_ATTACKER", "SOUND_PAN_ATTACKER", "1", "0" },
      { "AdjustPanningVar", "SOUND_PAN_ATTACKER", "SOUND_PAN_TARGET", "2", "0" },
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "13", "1" },
    },
  },
  ["WING_ATTACK"] = { sprites = 6, monbg = 1,
    tasks = {
      { "TranslateMonElliptical", "0", "12", "4", "1", "4" },
      { "AnimateGustTornadoPalette", "1", "70" },
    },
  },
  ["WISH"] = { sprites = 5,
  },
  ["WITHDRAW"] = { sprites = 0,
    tasks = {
      { "Withdraw" },
    },
  },
  ["WRAP"] = { sprites = 0,
    tasks = {
      { "TranslateMonEllipticalRespectSide", "ANIM_ATTACKER", "6", "4", "2", "4" },
      { "ScaleMonAndRestore", "10", "-5", "5", "ANIM_TARGET", "0" },
      { "ScaleMonAndRestore", "10", "-5", "5", "ANIM_TARGET", "0" },
    },
  },
  ["YAWN"] = { sprites = 3,
    tasks = {
      { "DeepInhale", "ANIM_ATTACKER" },
      { "DeepInhale", "ANIM_TARGET" },
    },
  },
  ["ZAP_CANNON"] = { sprites = 17,
    tasks = {
      { "ShakeMon2", "ANIM_TARGET", "4", "0", "5", "1" },
    },
  },
}

return Gen3AnimExpect
