#!/usr/bin/env python3
# Copyright (c) 2026 Cedric. All rights reserved.
# Source-available under the Gen2Recomped License (see LICENSE.md).
r"""
THE SECOND SCREEN HAS TWO ENDS AND THEY NEVER MEET.

src/render/SecondScreen.lua writes a frame; mobile/second-display/
SecondDisplayHost.java reads it and writes back taps. Nothing in either tree
imports the other, so the only thing holding them together is that both
happen to say "twelve-byte header, little-endian". That is exactly the shape
of bug this project keeps hitting: the same thing spelled differently in two
files that never meet.

So this checks them against each other, in two tiers:

  TIER 1 (always)  The constants, read out of both files by text. A version,
                   a magic string, a header size or a filename that differs
                   between the two ends fails here and needs no toolchain.

  TIER 2 (javac + texlua)  The bytes. A frame is generated by running the REAL
                   Lua transport, then handed to the REAL Java decoder --
                   compiled against generated stubs of the Android classes it
                   uses, which are written out below. A header the Lua end
                   produces that the Java end will not decode fails here.
                   Skipped, loudly, when either tool is missing.

Usage: python3 tools/second_display_protocol_check.py
"""

import json, os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA = os.path.join(ROOT, "src", "render", "SecondScreen.lua")
JAVA = os.path.join(ROOT, "mobile", "second-display", "SecondDisplayHost.java")

FAILS = []
CHECKS = [0]


def ok(cond, msg):
    CHECKS[0] += 1
    if not cond:
        FAILS.append(msg)
        print("FAIL: " + msg)


def read(path):
    with open(path, newline="") as fh:
        return fh.read()


# ---------------------------------------------------------------------------
# TIER 1 -- the constants, from both files
# ---------------------------------------------------------------------------
def tier1():
    print("-- tier 1: the two ends' constants")
    if not os.path.isfile(LUA):
        ok(False, "src/render/SecondScreen.lua is missing")
        return
    if not os.path.isfile(JAVA):
        ok(False, "mobile/second-display/SecondDisplayHost.java is missing")
        return
    lua, java = read(LUA), read(JAVA)

    def lua_const(name):
        m = re.search(r"SecondScreen\.%s\s*=\s*(.+)" % name, lua)
        return m.group(1).strip() if m else None

    def java_const(name):
        m = re.search(r"public static final \w+ %s\s*=\s*(.+?);" % name, java)
        return m.group(1).strip() if m else None

    lv, jv = lua_const("PROTOCOL"), java_const("PROTOCOL")
    ok(lv is not None and jv is not None and lv == jv,
       "protocol version: Lua says %s, Java says %s" % (lv, jv))

    lm, jm = lua_const("MAGIC"), java_const("MAGIC")
    ok(lm is not None and jm is not None and lm.strip('"') == jm.strip('"'),
       "magic: Lua says %s, Java says %s" % (lm, jm))

    # The header size is a literal in the Lua (four chars plus four u16s) and a
    # named constant in the Java, so it is counted rather than compared.
    m = re.search(r"local header = SecondScreen\.MAGIC(.+?)\n\s*--", lua, re.S)
    u16s = len(re.findall(r"u16\(", m.group(1))) if m else -1
    jb = java_const("HEADER_BYTES")
    ok(u16s == 4, "the Lua header writes %d u16 field(s) after the magic, not 4"
       % u16s)
    ok(jb == "12", "the Java end calls the header %s bytes; four chars plus "
                   "four u16s is 12" % jb)

    for name, jname in (("DIR", "DIR"),):
        lvv, jvv = lua_const(name), java_const(jname)
        ok(lvv and jvv and lvv.strip('"') == jvv.strip('"'),
           "%s: Lua says %s, Java says %s" % (name, lvv, jvv))

    # The three filenames. Lua builds them from DIR; Java keeps the leaf alone.
    for lname, jname in (("HOST", "HOST_FILE"), ("FRAME", "FRAME_FILE"),
                         ("TOUCH", "TOUCH_FILE")):
        lvv = lua_const(lname) or ""
        m = re.search(r'"([^"]+)"', lvv)
        leaf = m.group(1).lstrip("/") if m else None
        jvv = (java_const(jname) or "").strip('"')
        ok(leaf and jvv and leaf == jvv,
           "%s: Lua's leaf is %s, Java's is %s" % (lname, leaf, jvv))

    # The three verbs. A Java that emits "up" for a kind Lua does not accept is
    # a tap that vanishes.
    lua_kinds = set(re.findall(r'kind == "(\w+)"', lua))
    java_kinds = set(re.findall(r'kind = "(\w+)";', java))
    ok(lua_kinds == java_kinds,
       "the touch verbs differ: Lua accepts %s, Java emits %s"
       % (sorted(lua_kinds), sorted(java_kinds)))

    # The identity: Java has to find the directory Lua writes into.
    conf = os.path.join(ROOT, "conf.lua")
    if os.path.isfile(conf):
        text = read(conf)
        m = re.search(r'mobileOs and "([^"]+)"', text)
        ji = (java_const("IDENTITY") or "").strip('"')
        ok(m and ji and m.group(1) == ji,
           "save identity: conf.lua uses %s on mobile, Java looks in %s"
           % (m.group(1) if m else "?", ji))


# ---------------------------------------------------------------------------
# TIER 2 -- the bytes, through both real implementations
# ---------------------------------------------------------------------------
STUBS = json.loads(r"""{"android/util/Log.java": "package android.util; public class Log {\n public static int i(String t,String m){return 0;}\n public static int w(String t,String m){return 0;}\n}\n", "android/database/Cursor.java": "package android.database; public interface Cursor {}\n", "android/net/Uri.java": "package android.net; public class Uri {}\n", "android/app/Activity.java": "package android.app; import android.content.Context; public class Activity extends Context {}\n", "android/app/Presentation.java": "package android.app;\nimport android.content.Context; import android.view.Display;\npublic class Presentation extends Dialog {\n  public Presentation(Context outer, Display d){ super(outer); }\n}\n", "android/app/Application.java": "package android.app;\nimport android.content.Context; import android.os.Bundle;\npublic class Application extends Context {\n  public interface ActivityLifecycleCallbacks {\n    void onActivityCreated(Activity a, Bundle b);\n    void onActivityStarted(Activity a);\n    void onActivityResumed(Activity a);\n    void onActivityPaused(Activity a);\n    void onActivityStopped(Activity a);\n    void onActivitySaveInstanceState(Activity a, Bundle b);\n    void onActivityDestroyed(Activity a);\n  }\n  public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks cb){}\n}\n", "android/app/Dialog.java": "package android.app;\nimport android.content.Context; import android.os.Bundle; import android.view.View;\npublic class Dialog {\n  public Dialog(Context c){}\n  protected void onCreate(Bundle b){}\n  public void setContentView(View v){}\n  public void show(){}\n  public void dismiss(){}\n  public Context getContext(){return null;}\n}\n", "android/content/ContentProvider.java": "package android.content;\nimport android.database.Cursor; import android.net.Uri;\npublic abstract class ContentProvider {\n  public abstract boolean onCreate();\n  public abstract Cursor query(Uri u,String[] p,String s,String[] a,String o);\n  public abstract String getType(Uri u);\n  public abstract Uri insert(Uri u,ContentValues v);\n  public abstract int delete(Uri u,String s,String[] a);\n  public abstract int update(Uri u,ContentValues v,String s,String[] a);\n  public Context getContext(){return null;}\n}\n", "android/content/ContentValues.java": "package android.content; public class ContentValues {}\n", "android/content/Context.java": "package android.content;\npublic class Context {\n  public static final String DISPLAY_SERVICE=\"display\";\n  public Context getApplicationContext(){return this;}\n  public Object getSystemService(String n){return null;}\n  public java.io.File getExternalFilesDir(String t){return null;}\n  public java.io.File getFilesDir(){return null;}\n}\n", "android/os/Bundle.java": "package android.os; public class Bundle {}\n", "android/os/SystemClock.java": "package android.os; public class SystemClock { public static long uptimeMillis(){return 0;} }\n", "android/os/Handler.java": "package android.os; public class Handler { public Handler(Looper l){} public boolean post(Runnable r){return true;} }\n", "android/os/Looper.java": "package android.os; public class Looper { public static Looper getMainLooper(){return null;} }\n", "android/view/Display.java": "package android.view; public class Display {\n  public static final int DEFAULT_DISPLAY=0;\n  public int getDisplayId(){return 0;}\n  public void getSize(android.graphics.Point p){}\n}\n", "android/view/View.java": "package android.view;\nimport android.content.Context; import android.graphics.Canvas;\npublic class View {\n  public View(Context c){}\n  public void setBackgroundColor(int c){}\n  public void invalidate(){}\n  public int getWidth(){return 0;}\n  public int getHeight(){return 0;}\n  protected void onDraw(Canvas c){}\n  public boolean onTouchEvent(MotionEvent e){return false;}\n}\n", "android/view/MotionEvent.java": "package android.view; public class MotionEvent {\n  public static final int ACTION_DOWN=0,ACTION_UP=1,ACTION_MOVE=2,ACTION_CANCEL=3,\n    ACTION_POINTER_DOWN=5,ACTION_POINTER_UP=6;\n  public int getActionMasked(){return 0;}\n  public int getActionIndex(){return 0;}\n  public int getPointerCount(){return 0;}\n  public int getPointerId(int i){return 0;}\n  public float getX(int i){return 0;}\n  public float getY(int i){return 0;}\n}\n", "android/hardware/display/DisplayManager.java": "package android.hardware.display; import android.view.Display;\npublic class DisplayManager {\n  public static final String DISPLAY_CATEGORY_PRESENTATION=\"p\";\n  public Display[] getDisplays(){return null;}\n  public Display[] getDisplays(String c){return null;}\n}\n", "android/graphics/Bitmap.java": "package android.graphics;\npublic class Bitmap {\n  public static class Config { public static final Config ARGB_8888=new Config(); }\n  public static Bitmap createBitmap(int w,int h,Config c){return new Bitmap();}\n  public void copyPixelsFromBuffer(java.nio.Buffer b){}\n  public void recycle(){}\n  public boolean isRecycled(){return false;}\n}\n", "android/graphics/Point.java": "package android.graphics; public class Point { public int x,y; public Point(){} }\n", "android/graphics/Color.java": "package android.graphics; public class Color { public static final int BLACK=0; }\n", "android/graphics/Rect.java": "package android.graphics; public class Rect {\n  public int left,top,right,bottom;\n  public void set(int l,int t,int r,int b){left=l;top=t;right=r;bottom=b;}\n  public int width(){return right-left;}\n  public int height(){return bottom-top;}\n}\n", "android/graphics/Canvas.java": "package android.graphics; public class Canvas {\n  public void drawColor(int c){}\n  public void drawBitmap(Bitmap b,Rect src,Rect dst,Paint p){}\n}\n", "android/graphics/Paint.java": "package android.graphics; public class Paint { public static final int FILTER_BITMAP_FLAG=2; public Paint(int f){} }\n"}""")

CROSS_END = r"""package g2check;
import org.love2d.android.SecondDisplayHost;
import java.io.*;
import java.nio.file.*;

/** Feeds the Java end frames the Lua end wrote, and checks the touch mapping
 *  against the bounds the Lua end enforces. */
public class CrossEnd {
  static int fails = 0, checks = 0;
  static void ok(boolean c, String fmt, Object... a) {
    checks++;
    if (!c) { fails++; System.out.println("FAIL: " + String.format(fmt, a)); }
  }

  /** decodeHeader, but a throw counts as "did not refuse cleanly" rather than
   *  ending the run. The shipping caller wraps it in catch(Throwable), so a
   *  throw is survivable there -- but it must still be REPORTED here, or a
   *  missing length guard looks like a passing test that simply stopped. */
  static int[] decode(byte[] b) {
    try { return SecondDisplayHost.decodeHeader(b); }
    catch (Throwable t) { System.out.println("FAIL: decodeHeader threw " + t); fails++; return null; }
  }

  public static void main(String[] args) throws Exception {
    // ---- the frame the Lua transport produced ----
    byte[] frame = Files.readAllBytes(Paths.get(args[0]));
    int W = Integer.parseInt(args[1]), H = Integer.parseInt(args[2]);
    int expectSeq = Integer.parseInt(args[3]);

    byte[] head = new byte[SecondDisplayHost.HEADER_BYTES];
    System.arraycopy(frame, 0, head, 0, head.length);
    int[] hdr = decode(head);
    ok(hdr != null, "the Java end could not decode a header the Lua end wrote");
    if (hdr != null) {
      ok(hdr[0] == SecondDisplayHost.PROTOCOL, "version read as %d", hdr[0]);
      ok(hdr[1] == W, "width read as %d, Lua wrote %d", hdr[1], W);
      ok(hdr[2] == H, "height read as %d, Lua wrote %d", hdr[2], H);
      ok(hdr[3] == expectSeq, "sequence read as %d after %d push(es)", hdr[3], expectSeq);
      long want = (long) SecondDisplayHost.HEADER_BYTES + (long) W * H * 4L;
      ok(frame.length == want, "the file is %d bytes; this end expects %d",
         frame.length, want);
    }
    // a header from anything else must be refused, not drawn at a wrong size
    byte[] junk = new byte[12];
    ok(decode(junk) == null, "twelve zero bytes decoded as a frame");
    byte[] shortHead = new byte[11];
    System.arraycopy(head, 0, shortHead, 0, 11);
    ok(decode(shortHead) == null, "an 11-byte header decoded");
    byte[] badVer = head.clone(); badVer[4] = (byte) 99;
    ok(decode(badVer) == null, "protocol 99 decoded");
    byte[] badMagic = head.clone(); badMagic[2] = (byte) 'X';
    ok(decode(badMagic) == null, "bad magic decoded");

    // ---- the touch mapping, against the bounds Lua enforces ----
    // A 1280x720 panel showing a 256x192 screen letterboxes to 960x720 at x=160.
    int dl = 160, dt = 0, dw = 960, dh = 720;
    int[] c = SecondDisplayHost.mapPoint(dl + dw / 2f, dt + dh / 2f, dl, dt, dw, dh, W, H);
    ok(c != null && c[0] == W / 2 && c[1] == H / 2,
       "the panel's centre mapped to %s", c == null ? "nothing" : (c[0] + "," + c[1]));
    int[] tl = SecondDisplayHost.mapPoint(dl, dt, dl, dt, dw, dh, W, H);
    ok(tl != null && tl[0] == 0 && tl[1] == 0, "the top-left corner did not map to 0,0");
    int[] br = SecondDisplayHost.mapPoint(dl + dw - 1, dt + dh - 1, dl, dt, dw, dh, W, H);
    ok(br != null && br[0] == W - 1 && br[1] == H - 1,
       "the bottom-right mapped to %s, not %d,%d",
       br == null ? "nothing" : (br[0] + "," + br[1]), W - 1, H - 1);
    // THE LETTERBOX IS NOT A BUTTON. A clamped tap here is a press the player
    // never made, which is worse than a lost one.
    ok(SecondDisplayHost.mapPoint(10, 300, dl, dt, dw, dh, W, H) == null,
       "a tap in the left letterbox was mapped onto the screen");
    ok(SecondDisplayHost.mapPoint(1270, 300, dl, dt, dw, dh, W, H) == null,
       "a tap in the right letterbox was mapped onto the screen");
    // and every mapped point must satisfy the Lua guard: 0 <= x < 256, 0 <= y < 192
    java.util.Random r = new java.util.Random(7);
    int outside = 0;
    for (int i = 0; i < 20000; i++) {
      float px = r.nextFloat() * 1280f, py = r.nextFloat() * 720f;
      int[] p = SecondDisplayHost.mapPoint(px, py, dl, dt, dw, dh, W, H);
      if (p != null && (p[0] < 0 || p[0] >= W || p[1] < 0 || p[1] >= H)) outside++;
    }
    ok(outside == 0, "%d mapped point(s) fall outside the range Lua accepts", outside);

    System.out.printf("%n%d checks, %d failed%n", checks, fails);
    System.exit(fails == 0 ? 0 : 1);
  }
}
"""

GEN_FRAME = r"""-- Writes a frame using the REAL src/render/SecondScreen.lua, so the bytes the
-- Java end is handed are the bytes the shipping Lua produces.
package.path="__ROOT__/?.lua;"..package.path
local FS={}
love={timer={getTime=function() return 1 end},
 filesystem={getInfo=function(p) local b=FS[p]; if not b then return nil end
   return {size=#b,modtime=5,type="file"} end,
  read=function(p) return FS[p] end,
  write=function(p,b) FS[p]=b or "" return true end,
  createDirectory=function() return true end}}
local T=require("src.render.SecondScreen")
local W,H = tonumber(arg[1]) or 256, tonumber(arg[2]) or 192
local px = {}
for i=1,W*H do px[i]=string.char(i%256, (i*7)%256, (i*13)%256, 255) end
local body=table.concat(px)
local img={body=body}; function img:getString() return self.body end
local pushes = tonumber(arg[3]) or 1
for _=1,pushes do assert(T.push(img,W,H)) end
local out=io.open(arg[4],"wb"); out:write(FS[T.FRAME]); out:close()
io.write(("lua wrote %d bytes for %dx%d after %d push(es)\n"):format(#FS[T.FRAME],W,H,pushes))
"""


def tier2():
    print("-- tier 2: a Lua-written frame, through the Java decoder")
    javac = shutil.which("javac")
    texlua = shutil.which("texlua") or shutil.which("lua5.1") or shutil.which("luajit")
    if not javac:
        print("SKIPPED: no javac on PATH, so the Java end was not compiled.")
        return
    if not texlua:
        print("SKIPPED: no texlua/lua on PATH, so no frame could be generated.")
        return
    tmp = tempfile.mkdtemp(prefix="g2sd-")
    try:
        src = os.path.join(tmp, "src")
        for rel, body in STUBS.items():
            path = os.path.join(src, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                fh.write(body)
        for rel, body in (("g2check/CrossEnd.java", CROSS_END),):
            path = os.path.join(src, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                fh.write(body)
        dst = os.path.join(src, "org", "love2d", "android")
        os.makedirs(dst, exist_ok=True)
        shutil.copy(JAVA, os.path.join(dst, "SecondDisplayHost.java"))

        gen = os.path.join(tmp, "gen_frame.lua")
        with open(gen, "w") as fh:
            fh.write(GEN_FRAME.replace("__ROOT__", ROOT.replace("\\", "/")))
        frame = os.path.join(tmp, "frame.bin")
        W, H, PUSHES = 256, 192, 3
        r = subprocess.run([texlua, gen, str(W), str(H), str(PUSHES), frame],
                           capture_output=True, text=True)
        if not os.path.isfile(frame):
            ok(False, "the Lua end wrote no frame: %s"
               % (r.stderr.strip() or r.stdout.strip())[:300])
            return

        out = os.path.join(tmp, "out")
        os.makedirs(out, exist_ok=True)
        files = []
        for dp, _, fs in os.walk(src):
            files += [os.path.join(dp, f) for f in fs if f.endswith(".java")]
        c = subprocess.run([javac, "-nowarn", "-d", out] + files,
                           capture_output=True, text=True)
        if c.returncode != 0:
            ok(False, "the Java end does not compile: %s"
               % (c.stderr.strip().splitlines() or ["?"])[0])
            return
        java = shutil.which("java")
        r = subprocess.run([java, "-cp", out, "g2check.CrossEnd", frame,
                            str(W), str(H), str(PUSHES)],
                           capture_output=True, text=True)
        for line in r.stdout.splitlines():
            if line.startswith("FAIL"):
                CHECKS[0] += 1
                FAILS.append(line[6:])
                print(line)
            elif line.strip().endswith("failed"):
                m = re.match(r"(\d+) checks", line.strip())
                if m:
                    CHECKS[0] += int(m.group(1)) - len(
                        [l for l in r.stdout.splitlines() if l.startswith("FAIL")])
        if r.returncode != 0 and not any(l.startswith("FAIL")
                                         for l in r.stdout.splitlines()):
            ok(False, "the cross-end run failed: %s"
               % (r.stderr.strip().splitlines() or ["?"])[-1][:200])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


tier1()
tier2()
print("\n%d checks, %d failed" % (CHECKS[0], len(FAILS)))
sys.exit(1 if FAILS else 0)
